### ISSUE TITLE
What to do for a subject's page?

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes-Front-End#1020]
- Related to #898, #914, #916, amongst others.

So I was going to being to tackle #898 but I ran into some conceptual problems that I hope the group can help with.

Alex built a a subject's page for Talk (ex. https://www.zooniverse.org/#/projects/aliburchard/wildebeest-watch/talk/subjects/463145), but the issue with using it for #898 is that it's scoped to a single project. It also has project-specific stuff like adding a quick note (which is a good thing).

My question to group is are we OK with me making a subjects page, at something like `#/subjects/463145` and have it pull in as much data as it can from any project that it is a part of, and then like to that page from a collection? I'm not sure what use it would be besides giving me a place to link a subject to from a collection.

Alternatives would be

- Opening the subject image in a new tab for viewing and nothing more
- Making the link goto the uploaded project's Talk subject page.

Not sure I like either of those, but wanted to put this out there for discussion.

@mschwamb, @aliburchard, @DarrenMcRoy, @DarrenMcRoy, @edpaget, etc. thoughts?

**Comment by mschwamb** [comment]
I think collections, hashtags, and conversations on Talk should be gathered onto a single page just like talk 2.0 where if you go there you can see everything going on about it - It's been the most handy thing about Talk 1.0 and Talk 2.0 from a science team perspective. I've used hashtags and people's collections to do data validation and checks on Planet Four data analysis and being able to navigate through Talk has been handy because I also see people's comments. 

So I think having a separate page for collections for a subject that's different from it's Talk subject page is basically either duplicating info or cutting people off from Talk. If the page opens in a new tab I think it would be okay because you can still navigate through you collection if you choose and it's get you into Talk

**Comment by mschwamb** [comment]
I think it's okay to go to the project's Talk page even if there are mixed subjects in the collection (probably as long as it opens in a new tab). I think it makes the focus about discussion and interaction - Especially if the magnifier feature that's in P4 Talk and some of the projects is implemented, I think volunteers will be happy to be redirected to Talk and it might engage them more in discussion. 

Personal opinion here, but I think this is something Talk 2.0 did right in terms of layout - I'd really like to see this duplicated or similar very similar on panoptes Talk for the subjects page.

![screen shot 2015-07-10 at 12 57 42 am](https://cloud.githubusercontent.com/assets/753325/8601467/d743774e-269e-11e5-880c-c6b77a93fcd3.png)

**Comment by chrissnyder** [comment]
Agreed on not wanted them to be different things, and we should actively encourage and push people towards Talk. The problem is because a subject could potentially be used in multiple projects. Yes, I could link to the project that the subject was uploaded from, but that may not be the project that the user collected it from.

**Comment by mschwamb** [comment]
Why can't which project a subject was collected from be stored and then just go to that project's talk subject page even if isn't the one that uploaded it?

**Comment by mschwamb** [comment]
Had another thought to add to this - If a subject is involved in two projects, it has two talk pages anyway - so I'd just add a section to the subject page on each Talk that shows links to the other, so as long as that's there, I think in a collection linking the thumbnail to the Talk subject page from the project that the subject was favorited or collected in would suffice and keep the interconnectivity so if someone is exploring they can find the other discussions about it

**Comment by DarrenMcRoy** [comment]
@mschwamb What do you mean that it has two Talk pages? Do you mean, two Notes threads? Or two subject pages, one on each project? If it's the latter that you're talking about, I think that's actually the question at hand here, if I understand it correctly...

@chrissnyder -- does a subject used in two projects have two subject pages, or just the one, or is that the question being asked here, which we should use?

Sorry, just trying to sort out what I think is some confusion here, certainly for me. :-)

**Comment by chrissnyder** [comment]
For any given subject, you have a URL/page that looks like http://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/subjects/483699 where you can view stuff happening about that subject (current feature set besides the point).

That page makes total sense to link to from http://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/classify because you already are on P4: Terrains.

The problem is that a subject can *belong to multiple projects at once*. In a collection, all you have is a list of the subject's belonging to that collection, not what project the user added them from.

In the meanwhile, I could just hook each subject up to the project they were originally uploaded to, under the working assumption that it's unlikely we'll reuse subjects anything soon.

**Comment by mschwamb** [comment]
I do think it's going to be rare or rather not the majority of projects will reuse a subject from a different project, so for now linking to the subject talk page where the subject was uploaded from would be fine. 

 Say I do reuse subjects from P4: Terrains for another project called P4:CTX (just to give it a name). I collected a subject from CTX (but the subject was uploaded first on Terrains). Then when you click on the subject image form the  collections page  why can't it takes you to CTX talk since that's the project I collected it from? I guess what I don't understand  why the front end can't also store the project I collected the subject in.

**Comment by vrooje** [comment]
Once the main GZ is on Panoptes I'm hoping users will collect subjects from GZ and use them to run their own projects, so even if the majority of projects won't do re-use subjects I suspect the ones that do will be created by the users who use Talk all the time and who would find great value in the kind of cross-linking we're talking about. We know there are users cross-posting between e.g. astronomy projects and Science Gossip, and it would be great if we could make it easier for them to do that and to see what has already been done.

I agree with Meg that Ouroboros Talk does the linkings really well. I could see a science team also finding value in a project-specific view of a subject page, e.g. "show me all the comments this has received on P4T only", but more generally I wouldn't want to wall things off unless it was done in such a way that the between-project walls could very, very easily come down later.

**Comment by mschwamb** [comment]
Pretty sure I mentioned this earlier, but I think it's gotten lost in this thread. So thought I'd clarify one point that might have gotten muddled.  In the scheme for the Talk subject page I suggested I would have a devoted section that would link to other projects' Talk subject page. That would enable people to see it's somewhere else and check those conversations. 

Also in the case of GZ it may not make sense to spawn separate talks for each of those individual projects, but instead have 1 talk. Have 1 talk might not make sense for all projects reusing subjects. For example if we eventually use P4 images on P4: terrains I would want the talks to be slightly distinct since I think volunteers from Terrains would be extremely confused about comments on whether they should draw a fan or a blotch. So I don't think merging shouldn't be by default, but having the links means there is  constructiveness but you know it's discussions related to a different project/task.

**Comment by vrooje** [comment]
I thought we were talking about each subject having a page that any project can link to, versus each (subject, project) pair having a page? In the former the subject page would show everything from all projects (and possibly allow someone to show only matches for a particular project); in the latter you might need a cross-reference to each other project's subject page for that subject.

I'm in favor of the former approach. The issue of whether separate Talks should exist for projects that use subjects collected from a parent project seems like a different discussion.

**Comment by DarrenMcRoy** [comment]
A thought, @chrissnyder -- Why not link from any context-neutral location to the project the object was initially uploaded, and include on the subject page a note like "this image also exists in 3 other projects, click here to go to those Talk pages" ... ?

Similar to how if you type "dog" into Wikipedia, it will take you to the page about *Canis familaris*, but there's also a disambiguation link to all the other things called "Dog."

Would this solve the issue?

**Comment by DarrenMcRoy** [comment]
Closing as consolidated into #1271.
