### ISSUE TITLE
Request: Skip Image function

### ISSUE THREAD

**Issue by frankvitaleiv** [zooniverse/Panoptes-Front-End#1064]
Currently the only way to allow users to skip an image is to make it an answer choice within the workflow and end the classification, which would count as a classification towards retiring the image.  Would it be possible to implement a skip image feature, such as in Science Gossip, so that images that are skipped are not prematurely retired?

**Comment by mschwamb** [comment]
Typically skipping images is not needed. Most times when you make a volunteer make a decision instead of giving an I don't know or skip button, the combined results from the many classifiers give the correct answer. In one of my previous projects we had an 'I don't know' button for one question and it was rarely used. Most people ventured a guess that the button wasn't useful.

**Comment by CKrawczyk** [comment]
You can emulate this functionality by unchecking the "required" box for the first task.  This will allow users to click the "done" button without answering the first question, but I think this would still count towards retiring the image.

**Comment by camallen** [comment]
related to https://github.com/zooniverse/Panoptes/issues/1033

**Comment by chrislintott** [comment]
Close as won't fix. I don't think we should be offering a skip button.
