### ISSUE TITLE
"Number of subjects" doesn't update dynamically

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1128]
The "number of subjects" counter doesn't properly increase when subjects are added or decrease when they're removed, unless the user does a browser refresh.

![screenshot](https://cloud.githubusercontent.com/assets/1066340/8764350/176aecae-2da1-11e5-9d44-fea7d2962a37.png)

This also explains the incorrect '0' in #980.

**Comment by mschwamb** [comment]
I think some of the behavior has changed, but since it's seems very similar to this I haven't opened a new ticket. 

I'm finding this really annoying now that I'm uploading in batches because I want to confirm that everything uploaded and processed before uploading the next batch and to do that I have to refresh the browser each time. 
This is what it looks like after a successful upload of 500 subjects and before I hit refresh

![screen shot 2015-10-09 at 1 12 57 pm](https://cloud.githubusercontent.com/assets/753325/10386325/7736ba78-6e88-11e5-9784-8bea4fdf4ce8.png)

**Comment by camallen** [comment]
what's the problem with refreshing the page? I agree we could add more state tracking to get the counters right but the server is the authoritative source on this, so we'd need a refresh / api call of some description.

**Comment by mschwamb** [comment]
I think most people are used to uploading and seeing some confirmation the data upload was successful. If you don't refresh the browser it doesn't tell you more subjects were added, the first instinct is that something went wrong.  At least now for the few times I've uploaded the first upload, I've thought there was an issue, started a ticket, and then remembered to try refreshing and see if that works. 

Now uploading 12 blocks of 500, I'm trying to be careful to not skip or double upload so keeping track of the number of classifications in the subject set matters. So it's a bit annoying, but yes doable to refresh after every upload

**Comment by camallen** [comment]
fair enough, FYI - you could have another page on the subject set to refresh the counts..

**Comment by mschwamb** [comment]
I didn't want to tempt fate having two instances of the project builder open on the same page at the same time. Maybe there can be a pop-up saying upload complete that you have to close to trigger a refresh. Currently the popup that you can hit pause or start on disappears and there's no other acknowledgement your data actually uploaded.
