### ISSUE TITLE
rectangle and polygon aggregation

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes-Front-End#1157]
The way rectangle and polygon aggregation works is not very computationally efficient. If we want to find all regions that any 3 users have selected out of 15 users (just making these numbers up), I need to look through 15 choose 3 subsets (455) - that number grows pretty quickly as you increase the retirement number. Right now I have dealt with this by using a hard limit of 15 users - this can result in some value being off if the actual retirement rate is greater than 15. If there are cases where we really do need more than 15 users to mark an image with rectangles or polygons, I can implement some better code which should be more scalable. @aliburchard and I agree that for now this is an edge case, and I would want to see the actual case before I spend time on the coding.

**Comment by mkosmala** [comment]
Not sure exactly what algorithm you're using, but I would imagine you could calculate for each pixel how many users included that pixel in a region, keep all pixels that have at least 3 (or however many) users and then draw a convex hull around the groups of kept pixels. This might be slower than your algorithm for small numbers of users, but scales at O(n) instead of O(n!). Just a suggestion.

**Comment by camallen** [comment]
O the notation! couldn't help it.... ;)

**Comment by ggdhines** [comment]
@mkosmala asymptotically your idea would be better but I think there would be some steps involved that would be pretty time consuming - converting an arbitrary polygon into a (possibly large) set of points for each user and then having to repeatedly search through those sets. I'll look into that and other possible solutions when it becomes necessary. (and damn @camallen and his puns)

**Comment by vrooje** [comment]
This problem seems in some ways similar to source detection in astronomical images... in which case I wonder if the code/methods in [Source Extractor](http://www.astromatic.net/software/sextractor) ([Bertin & Arnouts 1996](http://adsabs.harvard.edu/abs/1996A%26AS..117..393B)) might be of use. It might be overkill, though.

**Comment by chrissnyder** [comment]
Not sure what output this issue is aiming for. Sounds like we need to have a conversation in Slack or whatever (if this issue is still relevant).
