### ISSUE TITLE
Getting an error message in creating collaborators

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1196]
I'm getting a "Error: not allowed to create this Role" when adding a "collaborator" but am allowed to anyway.

<img width="1280" alt="screen shot 2015-07-23 at 12 18 27" src="https://cloud.githubusercontent.com/assets/6217406/8849115/f42d8ba6-3134-11e5-8e13-24e2fe9e54c2.png">

**Comment by edpaget** [comment]
@aliburchard this looks like it was due to you not being made an admin for the project's talk section. It successfully added the roles in Panoptes, but not in Talk.

When did you create the project? I'm not sure if something when wrong or if the project was setup before owner roles were duplicated between the project and Talk.

**Comment by camallen** [comment]
@edpaget I migrated that project manually from staging and forgot to setup the talk roles.

**Comment by edpaget** [comment]
:+1: I'll add them

**Comment by aliburchard** [comment]
thanks!
