### ISSUE TITLE
Subject importer breaking when special characters in metadata

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1229]
Our Gorongosa project (for some reason) wants to use "|" in their primary keys (which we need in the  metadata so they can link zooniverse data to their images). When I try to upload Gorongosa images and a manifest, the subject importer reads in this second column with "|" symbols as the filename and breaks.

Note that I have named the FIRST COLUMN as "filename" and it contains the actual filenames (e.g. EK000079.JPG). But the importer is still automatically looking at the second column.

I suppose this is because the importer looks at all possible columns with ".jpg" in them to allow for potential multi-image subjects.  Perhaps we should allow users to specify which column(s) contain image names?

![screen shot 2015-07-27 at 12 24 03](https://cloud.githubusercontent.com/assets/6217406/8904861/e984d6ae-345a-11e5-9cd1-cab4e493be53.png)

**Comment by mkosmala** [comment]
This might be a problem with the formatting of your metadata file. Have you tried using a manifest with the weird character in a text field without a .jpg extension? 

If the importer doesn't accept a weird character in a normal text field, then the issue is either with the encoding of your file (welcome to the hell of file codecs) OR it means the front-end is not properly encoding the text to send it to the back-end.

The back-end does accept weird characters. (Although getting them in there was not easy for me. See https://github.com/zooniverse/Panoptes/issues/1140)

**Comment by aliburchard** [comment]
Weird characters seems okay -- was breaking with the jpg extension.
