### ISSUE TITLE
Rolling out features to us first

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes-Front-End#1237]
Sorry this is what I was trying to communicate on the Standup:

Feature flagged features should only be available to projects owned by the 'zooniverse' user or the 'zooniverse-team' user group, we can then enable the features on a per Project/Workflow basis through flags on the Project or Workflow metadata fields.

**Comment by chrissnyder** [comment]
Would it be a good idea to enforce this through the API, or is showing/hiding different controls in the UI sufficient?

**Comment by edpaget** [comment]
I think it'd be fine to enforce it only through the Front-End.

**Comment by aliburchard** [comment]
Can I just say how much I like this idea? I think it makes a lot of sense for tools that we want to be able to include in PFE projects but are not yet ready to make publicly available - whether because the tool itself is in development (e.g. survey task) or because we haven't yet figured out how to approach aggregation/provide guidance for appropriate usage (e.g. zoom)

**Comment by marten** [comment]
This just came up [in chat again](https://zooniverse.slack.com/archives/general/p1441639181000011). I agree with ed, but probably per-project is enough specificity, you can always refrain from using experimentals even if they are visible for a given workflow.

**Comment by chrissnyder** [comment]
Will be closed via https://github.com/zooniverse/Panoptes-Front-End/pull/1739
