### ISSUE TITLE
Switch the bright yellow for linked Talk comments to a nicer color

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1280]
low in the queue - but I find the highlighter yellow really harsh on the eyes - is there another color that @aweiksnar and @heathv could implement? I think it would really add to the polish of Talk 

https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/8/120?page=3&comment=3029

![screen shot 2015-07-30 at 10 24 28 am](https://cloud.githubusercontent.com/assets/753325/8974706/7ff2adca-36a7-11e5-9c45-21769bb145f9.png)

**Comment by chrissnyder** [comment]
100% agreed, but let's refrain from strictly design related issues, especially in Talk. We are doing a design pass shortly and will have a better solution for this.

Since I don't know if it will be simply a different color or some other method of highlighting a post, I'm going to close the issue. Rest assured we are aware and are working to improve this.
