### ISSUE TITLE
adjusting width of rotated ellipse can cause unwanted behavior

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1306]
I've been trying out some non-Zooteam-created projects for fun and [one of them](https://www.zooniverse.org/#/projects/kmthomas06/texting-the-caribbean/classify) has me drawing ellipses around map text. I think it's an ellipse instead of a box because it sometimes needs to be rotated (and maybe a line wouldn't do):

![screen shot 2015-07-31 at 17 10 05](https://cloud.githubusercontent.com/assets/2357126/9011753/41c37894-37a7-11e5-8b9f-08bcb97d8f32.jpg)

I'm finding that when I try to adjust the width of these ellipses, if I don't drag my mouse exactly perpendicular to the semi-minor axis the whole ellipse rotates, and it's very sensitive to small movements. I'm getting pretty wild twirls.

I don't think the tool is malfunctioning; I just think it's hard to use in this application and I'm not quite sure how we could improve it. Maybe make rotation only work along the long axis?

**Comment by Unskilled** [comment]
Hello team,

When making modifications to an elliptical mark, I also find it difficult to control both the rotation and size at the same time - especially on the semi-major access as vrooje mentioned above.

I'd like to suggest a couple potential solutions for this issue:
When an elliptical mark is selected for modification --
1. Make visible a third handle which allows for control of the rotation.
**or**:
2. Allow for rotation to be toggled on or off in some way.

I think that the first way is more intuitive to me, because having a third handle for rotation is familiar to me. Typically, this is shown as a transparent circle with an outline, rather than a filled circle as we have with the two points.

For additional reference, I initially made a post over on Zooniverse about this issue: https://www.zooniverse.org/#/talk/14/2063

Thank you,

Rick
