### ISSUE TITLE
Thumbnails are cached?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#1332]
Seems the requests to thumbnails are using `Cache-Control: "no-cache"` and are fetching every time from cloud front. Is this desired behaviour? 

![screen shot 2015-08-05 at 09 30 38](https://cloud.githubusercontent.com/assets/295329/9081517/d62585e4-3b54-11e5-9955-f81204d98914.png)

**Comment by parrish** [comment]
Weird.  In Chrome:
```
Pragma: no-cache
Cache-Control: no-cache
```

and in Firefox I'm seeing

```
Cache-Control: max-age=0
```

which are [actually pretty different](http://stackoverflow.com/questions/1046966/whats-the-difference-between-cache-control-max-age-0-and-no-cache) requests.  That said, it looks like Cloudfront is still responding with a cached response:

```
X-Cache: Hit from cloudfront
```

@astopy Can you verify that it's working as intended?

**Comment by astopy** [comment]
After testing this it seems to be working as intended. CloudFront is definitely caching everything, so the requests aren't hitting our Nginx servers. The no-cache headers you're seeing are in the request rather than the response, so the differences are a matter of how each browser behaves. It seems to be that the browser will specify some combination of no-cache/max-age if its cached copy is old (to guarantee that it gets the latest version).

Adding to the confusion is the fact that when objects are loaded from the browser cache, the response headers you see in the inspector are actually the headers from the original (cached) response. In Chrome it seems to be almost impossible to tell if it loaded it from the cache, other than looking at the date header in the response.
