### ISSUE TITLE
users requesting ability to 'go back' and redo classification

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1342]
The most frequent feature request I'm getting is that on the last page of the classification - where the user can review what they have put for the subject - they don't have the option to redo or cancel what they put.

**Comment by camallen** [comment]
@AdrianEvans, a few reasons why it's setup this way:

a) They can go back at any point except after they click “Done”, and 
b) once you click Done you can go see what the rest of the community is saying, so we don’t allow classifications to be changed at that point in order to keep classifications independent.
c) with enough classification data different opinions / mistakes should just be noise, https://www.zooniverse.org/#/projects/vrooje/galaxy-zoo-bar-lengths/talk/22/356?comment=943

**Comment by edpaget** [comment]
I think we can close this issue, since we will not change this behviour.

**Comment by chrissnyder** [comment]
Worth pointing out that while it's unlikely we'll ever allow people to go back and change classifications at a later date, we may change how the end of the classification step works, see discussion in #1345
