### ISSUE TITLE
Tool text not displaying in IE

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1359]
Zooniverse user GizmoMischief is getting buggy behavior in Wildebeest Watch (and more recently Whales) -- the labels are not displaying for marking tools, meaning he has no idea what tools correspond to what feature! see Talk thread here: https://www.zooniverse.org/#/projects/aliburchard/wildebeest-watch/talk/30/282?comment=3670&page=1

He's using a Lenovo ideapad which runs on Windows RT8.1, and using IE 10. Also got a similar report from user tai_shan.

As we don't allow image uploads on Talk, they have not been able to upload screenshots of the error or console messages. I'm requesting the image and console error for upload here.

**Comment by camallen** [comment]
Darren had some good instructions for screenshots here, https://www.zooniverse.org/#/talk/17/1739?scrollToLastComment=true&page=1

**Comment by aliburchard** [comment]
Yup. Didn't want to require them to create accounts on a photo sharing site just to have to write a bug report, so I'll upload for them.

**Comment by eatyourgreens** [comment]
Might be the same problem that's reported in #1333 There's a screenshot on that issue.

**Comment by eatyourgreens** [comment]
Here's IE11 on Win8.1 in VirtualBox.
![panoptes-tools-ie11](https://cloud.githubusercontent.com/assets/59547/9134542/136ac5d2-3cfd-11e5-93fd-82e219c508d7.jpg)

**Comment by yshish** [comment]
The same user in the Penguin Watch reported *"Big black ban across the image - couldn't see all the penguins"* http://talk.penguinwatch.org/#/subjects/APZ0005l9f 
More details from GizmoMischief:
*"sometimes it's on both the image on screen and on the image when I come to the discussion board."
" sometimes it's right down the bottom of the screen so that I can't see camera information, and sometimes it's in the middle of the screen."
"Windows RT8.1 which means I'm limited to using Internet Explorer - RT not being compatible with anything else. I'm going to try restarting my laptop and see if it makes any difference."
"that rebooting seems to have solved the problem for now"*

No newer messages from the user.....

**Comment by DarrenMcRoy** [comment]
@ali  you don't need an account to upload to imgur --  that's one of the things that makes it super useful. :-)

**Comment by ali** [comment]
@DarrenMcRoy Hi, you seem to have tagged/notified me instead of @aliburchard. Remember to use the full username when @-mentioning someone! :rainbow:
