### ISSUE TITLE
Project list is broken

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes-Front-End#1571]
<img width="255" alt="screen shot 2015-09-16 at 3 29 52 pm" src="https://cloud.githubusercontent.com/assets/122990/9917547/d95727dc-5c87-11e5-80ac-28cc5bbd29bd.png">

Is it possible that something that changed with project preferences broke this since zooniverse/Panoptes#1313 just closed?

It seems to be working in staging as well.

**Comment by aweiksnar** [comment]
I've got a PR opened here:  #1561

This was due to manually filtering that list on the frontend. If it gets back a response where all the projects have redirects it will filter those out and think it didn't get anything back. Hard to spot on dev since most activity happens in projects that have been created there

**Comment by parrish** [comment]
Ah, okay.  I'll comment there.
