### ISSUE TITLE
Markdown in answers not parsed in classification summary

### ISSUE THREAD

**Issue by brianaharder** [zooniverse/Panoptes-Front-End#1608]
Purely cosmetic, but it should either be parsed or stripped out so people don't see the raw markdown.  

![markdown in answers](https://cloud.githubusercontent.com/assets/3848095/9997868/4ed25144-6043-11e5-82b7-da6c2d73612e.png)

**Comment by DarrenMcRoy** [comment]
Would also make that summary less maddeningly huge.

We may be overhauling that summary page in general to allow for better interventions, but yes, I totally agree.

**Comment by Jim-Salmons** [comment]
#1529 has substantive comments related to this issue. This "summary page" issue needs a solution. The lack of display of a Classifier's annotations on the image, the non-rendered markdown, the non-truncation of longer text that are instructional/directions and not data, and the tendency for the "Talk/Next" buttons to be pushed off the visible page all contribute to a confusing culmination of an otherwise intuitive workflow.
