### ISSUE TITLE
Add ability to reply to comments directly from Recents page

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1661]
It would be extremely powerful, for everyone, if you could reply to a comment directly from the Recents page without ever having to leave that page.

You could then go through all recent activity and reply to everything that you need to reply to from one page. This is a particular strength of Reddit, for instance -- you can reply to a comment from anywhere that said comment appears, without any unnecessary clickthroughs.

Thoughts? Would this be tough?

**Comment by mschwamb** [comment]
One thing to keep in mind though is that  Talk differs from reddit in one very key way. Talk is object oriented, especially the notes threads, so replying to comments directly without the seeing the subject or the conversation context might not be as handy, because you really need to see the subject and what the person is referring to. Not sure if this fact changes your perspective. At least for me,  I find that I typically want to see the whole discussion thread before replying.

**Comment by vrooje** [comment]
It could be useful, but several times now I've gotten confused and thought a comment was in a different discussion just because I wasn't paying close enough attention. I think it might be a good idea to make people click to see the context...

**Comment by DarrenMcRoy** [comment]
At the very least it would be nice to have a reply button that would take you to the thread and immediately put you in an open reply box.

Would also be nice to be able to be able to upvote from the Recents page. Comments should have similiar functionality wherever they appear, IMO.

**Comment by parrish** [comment]
I intentionally removed it.

It's not helpful to reply to a comment until you know the context of the discussion.

**Comment by parrish** [comment]
I think it's safe to close this.  I think it's a good idea to be required to view a comment in context before replying/upvoting/etc.  We can revisit later on if we'd like.
