### ISSUE TITLE
All the Talk message boards have changed order both on Zooniverse Talk and the project talks 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1665]
I'm not sure if this was supposed to happened but all the Talk boards are in different places. I had set up of P4: Terrains so that the Help thread was first so people saw it without having to scroll if they had smaller screen. Nowt the help board is on the bottom and the notes thread is the top. 

Same thing on Zooniverse Talk the boards are all in a different order. Looks like the boards are being list by the last time there was a post. 

@parrish and @aweiksnar if this a new feature, is there a way to pin the boards so their order doesn't change? I find the reordering very confusing.

**Comment by CKrawczyk** [comment]
I think this is related to the fix for this issue https://github.com/zooniverse/Panoptes-Front-End/issues/1650

**Comment by parrish** [comment]
Yeah, discussion ordering was fixed to properly order by comment creation time.  I did the same for boards since they had been ordered by board creation time (which doesn't make a ton of sense).

I figure either the current behavior or an orderable list is probably the best way to do this.  @DarrenMcRoy definitely prefers the latter.

I'd like to leave it as is for a bit to get some feedback before we try changing it.

**Comment by DarrenMcRoy** [comment]
Feedback welcome on this as we've been discussing it. :-)

**Comment by mschwamb** [comment]
To best honest,  I really hate this feature. It makes Talk confusing and frustrating for me really frustrating for me. Every time I go on things are in a different order. 

 It means that people who are new can't immediately find a help board. It's fine for people who are not new but they have to jump order to find a board they want to review. I had the help specifically where it was to make it easy for new people to report bugs. Now you have to scroll through since it's not immediate.

No other forum tool I've ever used does this.With a recent comments thread functionality there is already a way to see recent threads.  The mods on Planet Four: Terrains don't like it, and complained about this 'bug' already. 

If you are going to keep this, then please add in a feature to sticky the boards into an order.

**Comment by yshish** [comment]
I agree with @mschwamb on that. What I really like on the old Talk are those three fixed boards: Help, Science and Chat. But it's definitely very helpful to have all the discussions under each board sorted by the date/time. 

Btw, I wouldn't create any new boards there. It's too much already.

**Comment by DarrenMcRoy** [comment]
I'm personally not a fan of the Help/Science/Chat structure because it was too rigid. You couldn't change those even if you wanted to. :-) Besides, those weren't actually boards, they were headers that boards went under.

But, as @parrish said, I strongly support the ability for a project team or moderators to order the boards in a static way as they think best.

**Comment by parrish** [comment]
I took a best-of-both-worlds sort of approach in #1672.

Now moderators have the option of choosing between boards ordered by most recent comment or to manually reorder them.

It's available in the moderation pane and looks about like this (drag & drop):

<img width="172" alt="screen shot 2015-09-30 at 2 45 29 pm" src="https://cloud.githubusercontent.com/assets/122990/10204542/fa49dc1e-6781-11e5-86c7-b301a06d72b2.png">

**Comment by DarrenMcRoy** [comment]
Thank you, Michael!! This is perfect!! Can't wait to try it out.

**Comment by mschwamb** [comment]
Thanks very much @parrish

**Comment by parrish** [comment]
This is live now.

By the way, I figured it was good to get this feature out since it seemed to polarize opinion pretty drastically.  Also bonus, this implementation still allows us to test how many people prefer one implementation over the other (since you can switch between time-based/manual ordering)

**Comment by DarrenMcRoy** [comment]
One thing that still bugs me is that there's no "flag" to show if the boards are currently being ordered by activity or are locked into a static order. You can't tell.

I assume that if you are ordering by activity, and then move one board around, everything becomes static-locked?

Could the "order by activity" button appear in a "depressed" or shaded mode if the boards are currently being ordered by activity? Would be clearer what state the boards are currently in.

Thanks!
