### ISSUE TITLE
On the Talk recent comments page - the Subject associated with a Notes post comment shows up even if the note isn't the first post

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1699]
If a reply is in a Notes thread (even if it's in a different board than the Notes), the recent comments page is  showing the  post with the subject attached and showing even though the post is a reply to someone's original post that was associated with the image. 

I'm finding that confusing, because then when you click on the post you see that it's not the first thread in the discussion. 

On the recent comments page it shows like this:

![screen shot 2015-10-05 at 9 33 50 pm](https://cloud.githubusercontent.com/assets/753325/10281714/0ae825d2-6ba9-11e5-9f9b-66da2d608c5e.png)

Looks like this in the  Talk thread:

![screen shot 2015-10-05 at 9 33 57 pm](https://cloud.githubusercontent.com/assets/753325/10281737/3a306408-6ba9-11e5-9f79-317ac5b0beef.png)

~~Sorry @aweiksnar I'd label this, but I've currently lost my collaborator status on the repo~~

**Comment by aweiksnar** [comment]
This was done by design. Since all comments in a notes discussion are tied to that subject, we didn't want to render that image for every comment in the discussion since it would add quite a bit more noise to view that image over and over. 
However, in a recents view, when the rest of the discussion context is not present, rendering out the image above the comment should help users know what the comment was about without needing to visit the thread

**Comment by mschwamb** [comment]
I can see your point, so I'll close. It would be nice if there was a way to know if the post was one of many in a notes thread, but there might be a straightforward way to do that.
