### ISSUE TITLE
Ability to export the survey/filtering CSVs for a workflow

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1772]
Once a workflow has been created with a survey/filtering task, there is currently no way to access the CSVs (choices, characteristics, confused pairs, questions) which made that task.
This means if you want to see how someone else's workflow is constructed, you have no way to do so, and if you want to modify your existing workflow, you can only destroy it and make a new one, and only then if you kept the CSVs.

Can we add a feature to make the uploaded CSVs available for download? Either within the survey task, or via the exports page?

**Comment by chrislintott** [comment]
@aliburchard, comment?

Chris

**Comment by aliburchard** [comment]
I think this would be *really* useful - especially when building projects collaboratively. My impression from @brian-c is that the csvs that project builders upload aren't stored as such, but immediately converted into workflow content -- but it seems like it would be relatively easy to save the csv as well. 

Re: modifying existing workflows - I think creating the ability to modify workflows would be nice, but a LOT of work, and I'm not convinced it's critical. This relatively rigid approach was a compromise to deliver this functionality on a short-ish timeframe. I think that being able to download the csvs would alleviate the inability to modify a workflow because you could download the current csv, make a small modification, and upload the revision.

**Comment by srallen** [comment]
This is now implemented behind an experimental tool feature flag.
