### ISSUE TITLE
"Subjects" statistics includes deleted subjects

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1800]
Noticing that the banner at the bottom of the home page for [Faces of the World](https://www.zooniverse.org/projects/pszmt1/faces-of-the-world) shows nearly 20,000 subjects, even though about 10,000 of those were deleted (and then reuploaded as the second 10,000).

That number is very misleading (flat-out wrong) if it includes images that have been deleted. It's saying that there are twice as many images in the system than there actually are.

**Comment by camallen** [comment]
That subjects count is accurate that project has 20K subjects but you're right @DarrenMcRoy not all of them should be "active". The count that we should probably show (in this case) is the count of links between active workflows and the subjects (set_member_subjects). However there are caveats, let's say the project started with 10K subjects, they had classifications, then deleted the linking between the workflows and the subjects by removing a subject set (limits). Then then uploaded another 10K that were active these then receive classifications too. Would you then count just the second batch of subjects? Counts will most likely be incorrect if we do this.

I think better messaging around deleting a subject set when the user is trying to avoid the limits but also hard deleting orphaned subjects [issue here](https://github.com/zooniverse/Panoptes/issues/1193#issuecomment-125981137) would alleviate these issues. It's that or we modify the way we count things from a set date [issue here](https://github.com/zooniverse/Panoptes/issues/1398#issuecomment-147347083).

Finally I can manually clean these counts up if we need.

**Comment by mschwamb** [comment]
I'd actually vote for removing the subject count from the front page all together. I don't think it's very informative, especially if projects break into different subset sets their data. Right now it counts all subject sets, if you do just active than that's confusing compared the classification count, because the classification count is since the project was live and the subject count will vary every time their is new data set switched to live. Also if you have multiple workflows what does the subject count mean then? I'd actually vote to remove the subject count and just leave the classification count. 

If you wanted to leave a useful statistic up there, I might recommend percentage of live data retired might be better since it gives the same information but gets around the actual number of subjects.

**Comment by camallen** [comment]
Wildcam uses a [percentage complete statistic](https://github.com/zooniverse/wildcam-gorongosa/blob/b441edc4efa0f9f12495559f5148a044ffcc2e84/app/partials/project-metadata.cjsx#L25) i thought was useful, see it here http://www.wildcamgorongosa.org/#/.

**Comment by mschwamb** [comment]
@camallen I think some sort of percentage complete as you referenced makes sense  and is much more informative.

I'm can't quite fully ready the code snippet, but is it also counting the classification count in the completion or if it's calculating this for just the live subject set or all the project subjects. 

I think it should be for the subject set that's live, it's get you around adding data to the site that's not live, and if you add in a small amount of data you get what happens on the [P4 status page](https://api.zooniverse.org/projects/planet_four/status) where it says 87% complete but in reality we're not 87% complete for the current set of live data, just for all the dataset of retired + live.

**Comment by mschwamb** [comment]
I should say I think some sort of percentage complete statistic (not matter how exactly the development team decides to compute that value)  would be more informative and less confusing than the current subject count.

**Comment by camallen** [comment]
> I think it should be for the subject set that's live, it gets you around adding data to the site that's not live. If you add in a small amount of data live, but count completion for everything, you get what happens on the P4 status page where it says 87% complete but in reality we're not 87% complete for the current set of live data, just for all the dataset of retired + live. We move a percentage point every few months. 

I disagree with the above, these stats are project level stats and are shown on the project landing page. Most projects (e.g. P4) are long lived over many iterations of data so excluding the lifetime effort seems inaccurate to me. I agree that we could have a breakdown report that shows per set stats, it's something we want to build especially in the context of project assessment.

**Comment by mschwamb** [comment]
Well I see the the lifetime effort as preserved in the classification count. What does 86% complete mean  for the total subects when you're a long lived project and adding in data each time you hit 100%?

**Comment by camallen** [comment]
I see your point, I guess i'm thinking about which tier of the project we report on. Which is most valuable and which provides more value / incentive to users?

**Comment by mschwamb** [comment]
I think for incentive to users is % completion of live subject data. That way when a research teams sends a newsletter says we're making a big push to finish season 2 which is live, than the percentage complete for subjects is giving you the measure for that at the volunteer community's effort. Then it makes sense when it decreases in size or goes to zero because there's a new data set and we're working towards its completion (I wouldn't remove the number of total project classifications I think it gives a separate measure of effort and volunteer success). A research team should have a blog or a newsletter at that point announcing new data so the chance in counter is explained. And then is starts the incentive again to get the counter to 100%. 

That  value is also handy for research teams because when you're 80%-90%  complete on the live data you better start thinking about adding in new data. Where as when you report completeness based on the all the retired subjects + live data, you have to translate what that to the actual completion rate.

**Comment by DarrenMcRoy** [comment]
One caveat about percentage complete  that we encountered with Wildcam:  since this system serves all subjects at all times (right?),  it won't be until very far into the project that anything will actually be retired.  So Wildcam  was still showing "0% complete" after a week of quite impressive effort.  So displaying completion percentage as (retired subjects)/(active subjects)  might not work here.  It would display as 0% for a very long time, and then suddenly accelerate at the very end of the project, no?

**Comment by CKrawczyk** [comment]
If a project has a fixed retirement limit you can get the % complete with (classification count)/(active subjects * retirement limit), that way it goes up with each classification, not each retirement.  As soon as you move away from fixed retirement limits this becomes a harder number to compute.

**Comment by mschwamb** [comment]
Yeah if you do it based on % of classification counts towards retirement which is I think the way Wildcam does it as @CKrawczyk describes it. All I'm saying is that I think that should be calculated based on classifications of the live subject set not total in the entire dataset ever classified.

**Comment by eatyourgreens** [comment]
Looking at that Wildcam code, I think this line goes to zero as the project reaches completion:
https://github.com/zooniverse/wildcam-gorongosa/blob/b441edc4efa0f9f12495559f5148a044ffcc2e84/app/partials/project-metadata.cjsx#L27
Which would mean that the completion percentage tends to infinity, right? Or have I misread the code?

I think @CKrawczyk has the right formula for calculating progress in a project.

**Comment by DarrenMcRoy** [comment]
Agreed, but as Coleman said, if you -- for instance -- are retiring "nothing here" after 5 classifications, but any animal takes 20, that number becomes literally impossible to compute ahead of time, because you don't know how many photos have an animal. So I don't have a great solution right now.

**Comment by mschwamb** [comment]
well for the not custom projects on the project builder - the retirement rate is set in the workflow. So you know that number, times by the number of subjects in the subject set gets you the total number of classifications you need. Sum up the classification counts for the subjects in the subject set. It would be fairly close to the correct answer.

**Comment by DarrenMcRoy** [comment]
If retirement rates are always fixed, then my concern is a non-issue.

**Comment by CKrawczyk** [comment]
There could also be an issue if different workflows has different retirement numbers.  Each workflow would need its own counter.

**Comment by mschwamb** [comment]
So I would say go with subject completion/retirement, it's simpler and reflects back. The classification count will be there, so I don't think it's a problem for it to show progress as subjects get completed. We tell people it takes multiple classification per images. Especially if the value is labeled something like '% live subjects completed/retired'

**Comment by CKrawczyk** [comment]
@eatyourgreens Looking at that code I can't figure out what it is calculating. It would go to infinity as the project gets close to completion.

**Comment by eatyourgreens** [comment]
@CKrawczyk so it isn't just me that doesn't understand it. I'll open an issue on Wildcam.

**Comment by vrooje** [comment]
I seem to have missed this discussion (oops) but I strongly prefer a completion fraction calculated as
`n_classifications/(sum_over_workflows(n_subjects_in_workflow*retirement_limit_in_workflow))`
because that smoothly approaches 100% at a rate that generally tracks the number of classifications, whereas
`n_retired/(n_retired + n_active)`
tends, for projects where subjects are served randomly, to hang out at 0% until most subjects have (retirement_limit - 1) classifications, at which point it jumps rapidly. That's both unsatisfying for volunteers keeping track, and a recipe for running out of data without anyone noticing*.

*the exception to which is any project watched over by @mschwamb, who has a superhuman ability to stay on top of these things.
