### ISSUE TITLE
Removing subject set does not clear subject set count (stuck at 10000)

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#1895]
I uploaded 10000+ images to a subject set at which point it threw me an error and failed

After deletion of the subject set, as this error was messing with my book keeping, the counter is stuck at 10000 and not cleared.

I can not upload new data as it will keep reporting that I'm out of allowed subjects!!!

Also, I have 30000+ subjects to deal with, if there is a hard limit of 10000 for a project how do I go about this?

===

Adding Subject: R1066148_c_10_2.jpg
Error: 403
   {"errors":[{"message":"User has uploaded 10000 subjects of 10000 maximum"}]}

Tried to pass data:
    {   
        "subjects": {
            "locations": [
                "image/jpeg"
            ],
            "metadata": {
             "#Filename": "R1066148_c_10_2.jpg",
                           "#Row": "10",
                           "#Col": "2"
            },
            "links": {
                "project": "153"
            }
        }
    }

**Comment by camallen** [comment]
@khufkens - This is an API and documentation issue, for reference see:
https://github.com/zooniverse/Panoptes/issues/1147
https://github.com/zooniverse/Panoptes/issues/1124
https://github.com/zooniverse/Panoptes/issues/1120

Deleting subject sets doesn't actually remove the subject as they need to be kept around for talk / data aggregation, etc. Your current limit and upload counts are listed on the subject set page where you import. 

Re limits the initial 10K should be enough to get started, we will then process any requests to increase the limit (e.g. this one). I will bump you limit but i'd suggest not uploading all 30K at once into 1 subject set. You should instead create smaller subject sets where you can activate(link) for a workflow. This way you can create smaller focus sets of subjects that will retire quicker than spreading your classifications over a large subject set, the exact set size is up to you though.

Finally we recommend uploading in smaller batch sizes due to the issues you just experienced, i.e. a subject set upload fails and you need to figure out where the failure occurred. The best structure is to create multiple sets and then upload to those sets in batches of 500 - 2/3 K. The more you upload per batch the more you will have to bookkeep if things go wrong. 

I'll PM you on zooniverse talk and we'll sort out you busted upload and increase you limits.
