### ISSUE TITLE
No link to subject page from subject posted in ZooTalk

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1900]
https://www.zooniverse.org/talk/17/107/?scrollToLastComment=true&page=9

This post is in the wrong place and is pointless, but it did illustrate to me that if you post a linked subject in ZooTalk,  it apparently does not contain a link to the subject page (i.e., "Subject 466244" should be hyperlinked).

**Comment by alexbfree** [comment]
Just curious what was the reason for closure? Seems like a valid point that could still be fixed?

**Comment by parrish** [comment]
Since subjects can be shared across projects, and this comment is in a section not associated to a project, there's no context for what project it should link to.

There are any number of ways that this could be resolved in the future, but the more likely options are
  - Subject pages allow project context switching
  - We require project-based mentions/focuses (e.g. owner/project-name#123456)
  - We use set_member_subject ids instead of subject ids to preserve subject context.

Until Panoptes settles on a subject sharing implementation, it's cart-before-the-horse to try to mess with this.
