### ISSUE TITLE
Inline help text

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#202]
Add help text all over the place, especially the workflow editor.

@aliburchard would you mind drafting up some short notes on anything you'd find confusing coming to this as a scientist?

**Comment by aliburchard** [comment]
@brian-c Alright, (with the caveat that this is the awesomest thing ever) I've gone through from the perspective of a non-zooniverse scientist and written a list of things that I think are confusing. I'm happy to come up with help text in various places, but just not sure yet where those will be or what will be the most useful? Happy to sit down and walk through what I found confusing and figure out how to target text v design and whatnot...

**Generally confusing (to new people)**
* What is a “workflow”? Why do I get multiple workflows? How do I know if I need multiple workflows or just one, with questions that depend on the answers to previous questions? How is a workflow title different than a project title?
* What is an Expert set for Untitled Workflow? (I assume this happens because Expert set needs to refer to something, and the first thing I accidentally created was an untitled workflow. But is this for experts to review? Do we distinguish between experts reviewing to create gold standard data vs when they want to re-evaluate certain images that they know people have gotten wrong (say I saw someone say subject X was a “rhino” on talk and I want to go back and add in an expert answer).
**Editor:**
* The TASK section on the left is pre-populated with a question task. It’s not clear that you can instead start with a marking task (I figured this out by adding a marking task, then deleting the question task) — perhaps some text over the “TASK” section that explains “You can ask people to answer a question or mark various objects” or something
* Unclear that the stuff on the right (main/help text and choices fall under “Task” instead of “workflow”). The hierarchy isn’t immediately apparent. (Perhaps this could be solved with some design (some sort of background colour blocking that clarifies this)
* Starting out, it’s not clear that subsequent questions can depend on answers to previous questions, especially because you have to create new tasks and *then* go back and link them. For example, if I only have one task, the “Next task” gives me that same task or end classification. It’s not clear how this specification links with adding tasks over under “TASKS” to the left. For example, my first task is “are there any wildebeest?” If folks answer “yes,” I want them to answer more questions. If “no” I want them to move on to the  next subject. But as I haven’t yet created the next questions, I don’t get that as an option, and I’m not sure after my first task how I will go back and link them.
* The “save changes” button is over to the left under “task” - I find it a bit confusing, and it’s not immediately apparent to me whether saving my changes with that button pertain to the specific task or the whole thing or what
* Under “Tasks” the various tasks have little symbols to the left of the text. What do they mean? (The only nonintuitive ones I think are multiple choice vs non-multiple choice, which changes from circle to square. Required doesn’t affect the symbols.)
* I find myself wanting to see what this looks like after every change.
* Are tasks presented one at a time to volunteers so that they only see the next task after they’ve completed the current one? Does this depend on whether tasks are dependent on previous tasks? And what does this mean for non-required tasks?
* As a newcomer, I don’t know what “Associated subject sets” means. Something to clarify that this means “ Images you want to classify with this series of tasks.” I suspect a lot of our basic users will only want one workflow and subject set. (I think this is just figuring out user-friendly terminology, perhaps a glossary for new users?)
* Save Changes was blue (so I assumed there were changes to save), but when I clicked it, it said “param is missing or the value is empty: workflows"
* I find myself wanting to shuffle task order over on the left...
* How do I know how to format text/insert a picture into the help text boxes/marking text boxes?
**Question Tasks**
* The “multiple choice” option is confusing. I can have multiple possible answers either way, so I assume that multiple choice means the user can select more than one option? 
* The meaning of “required” as it pertains to the task is unclear. I assume this means that volunteers *have* to answer this question to move on. But I can’t visualise what their experience would look like if they didn’t have to answer it. If they don’t answer it, how do they skip it? 
**Drawing Tasks**
* How come drawing tasks don’t have the same required option?
* What are set up details? A mysterious box opens when I click on it, and now it says (1)...
* Not immediately clear to me that I can add more than one drawing tool (yes, I realize there is a giant plus sign there, but for some reason...)

**Comment by aliburchard** [comment]
@brian-c as per @chrislintott 's suggestions today, I'm going to close this issue and open single issues for the relevant bugs/features. Chris and I will also work on drafting the help text for various places on the site, and deliver that in one go in a separate issue..
