### ISSUE TITLE
mini-ztm branch: zoo font needs to be cache busted

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2020]

**Comment by alexbfree** [comment]
notes from Sarah:
* it’s all bash scripts, check out the bin folder
* places to look are in views/index.ejs and the scripts in the bin folder
* a `rename_with_hash` function is being called in `build.sh`
* there’s also in the root folder a server.coffee and a start.js file

​

**Comment by amyrebecca** [comment]
this issue is a bit confusing because it says two different things:

1. the font needs to load on preview
2. the font needs to be cache-busted

I think that the former can be accomplished without the latter, and it seems like caching fonts would be desirable in terms of conserved bandwidth. Sarah has a solve for the issue with the font loading on preview that doesn't involve cache-busting and i've dropped that into my branch.
