### ISSUE TITLE
Snapshots at Sea problem - Get no buttons to classify if I click talk and done on a subject and then classify again and submit a reply interface stops repsonding

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2048]
The whole interface stops responding and all you see is the image if you classify an image as done & talk and then go back to classify and click done or done and talk cc @aliburchard @brian-c @chrislintott 

![screen shot 2015-12-21 at 11 51 35 pm](https://cloud.githubusercontent.com/assets/753325/11934708/c8803c66-a83e-11e5-8a6e-245880a14945.png)

**Comment by mschwamb** [comment]
A refresh of the browser brought the interface back up. I was using the latest version of mac firefox.

**Comment by mschwamb** [comment]
Replicated it logged in as well.

**Comment by chrislintott** [comment]
And on Chrome.

**Comment by itsravenous** [comment]
Looking at this now. For some reason, when you go back to the classification and click "done", the classification object in the next instance has `completed: true` set, which is why the task area doesn't display. Looking into why that should be now.

**Comment by aliburchard** [comment]
thanks @mschwamb for catching this. @brian-c @itsravenous i'm so sorry for not catching this soon. thank you so much for jumping on this so quickly.

**Comment by itsravenous** [comment]
Also occurs if you load a subject, go to Talk/Research etc then come back and click Done.

**Comment by itsravenous** [comment]
@brian-c calling `@loadAnotherSubject` in  `ProjectClassifyPage#componentDidMount` fixes the problem, but does mean you get a different subject when you navigate back to the classify page. I guess this is fine for when you've hit "Done & Talk" (you want the next subject) but I don't know whether this is acceptable behaviour when simply returning from another project page (i.e. do you want the same subject displayed if you hop over the research page and then come back to classify?)

**Comment by aliburchard** [comment]
@itsravenous hmmm, you may have hit on a bigger (philosophical) question with "do you want the same subject displayed if you hop over the research page and then come back to classify?" -- I think I'm okay with that, but suspect that folks like @mrniaboc @chrislintott and at @vrooje have thought more about that as a universal behavior.

**Comment by vrooje** [comment]
I prefer that it load a new subject if you've navigated away by finishing a classification and clicking the Talk button; if you've navigated away by clicking Done and then another link than Talk I might want to keep the same subject displayed (except with buttons) in order to preserve the user's ability to go to Talk linked with that subject, but I'm not too bothered if that's sacrificed in the name of moving forward with classifications.

I feel like we've discussed this elsewhere but I can't recall where.

**Comment by eatyourgreens** [comment]
@itsravenous I had a play with _Whales As Individuals_. If you start a classification, then hop over to the FAQ, then back to finish your classification, the classify page preserves the subject and your answers so far.

So I guess the expected behaviour is to preserve classification state until you press Done. Would calling `@loadAnotherSubject` in `ProjectClassifyPage#componentDidMount` break this behaviour on existing projects?

**Comment by itsravenous** [comment]
@eatyourgreens it would indeed break that which is obviously not great. I should have mentioned I see this only as a workaround, not a proper fix - the root of the problem is that the `@state` of the classify page component is getting lost when you hop away. I'm not sure how I could have introduced that with this feature, but I must have done. If a quick fix is direly needed for this (and it sounds like it is) we could do the `@loadAnotherSubject` only on projects with this feature enabled, as long as I/we then solve the actual problem later.

**Comment by eatyourgreens** [comment]
@itsravenous that sounds like a better idea than breaking existing projects. It would be very frustrating to start marking an image on a longer workflow, then lose that work because you went to check the FAQ. Also, people might think that their partially-completed classification had been submitted by mistake.

I've had a quick look at the classify page component, but I'm afraid I can't see how it's preserving the classification state either, or where this feature might have broken it.

**Comment by itsravenous** [comment]
@eatyourgreens Thanks for looking into it. If we're all agreed that that's an OK quickfix for now I can submit a PR tonight.

**Comment by eatyourgreens** [comment]
@itsravenous sounds good to me.

Could there be a bug if `loadAnotherSubject` runs before the promises in `saveClassification` have resolved? That's the only thing that occurred to me. https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L239

**Comment by itsravenous** [comment]
@eatyourgreens ah, yeah. I did try making `@saveClassification` return a promise when I was trying to fix this issue, but I ran into more problems. Will look into it.

**Comment by eatyourgreens** [comment]
@itsravenous something like `setTimeout @loadAnotherSubject, 500` might work (I forget the exact syntax for timeouts.)

**Comment by itsravenous** [comment]
I have't! So as far as I can see, `@state.workflow` was always lost when you hopped back; it's just that it didn't have anything depending on it (`@props.project` for some things, but not `@state.workflow`). The classification is still persisted also. So all we need to do is get the workflow back when we hop back to classify. I'm going to try that in cdm.
