### ISSUE TITLE
Get  an error messge when you've completed all the data

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2059]
Volunteer getting that thought the orange band is supposed to show or is this the new messaging system for that ?

Details here: https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/23298?comment=47855

**Comment by camallen** [comment]
@mschwamb this is a backend issue and it sounds like they've seen all available data. I've got a fix for this in a recent PR, after this it should always return some data (most likely seen data if they are power users though). Closing here, please re-open in backend if it's not fixed in the coming days.
