### ISSUE TITLE
If I click on the hashtag on the comment preview on the talk subject page it searches Zooniverse Talk

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2066]
(also same issues as #2065) but this time it also goes to Zooniverse talk

example https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/subjects/1070991

click on the #pancakesindepressions in the first comment

**Comment by alexbfree** [comment]
Note to developers - this differs from #2104 and #2065 as it concerns Zoo-wide talk rather than project specific talk. There seem to be three issues:
1. The route zooniverse.org/talk/tags/mytag doesn't exist, only zooniverse.org/projects/owner/projectname/talk/tags/mytag
2. The automatic generation of links in markdownz component generates search query instead of tags link for hashtags in non-project-specific posts.
3. The hashtag links in the sidebar for non-project-specific talk are pointing to search queries instead of tag links (this is not an issue with project-specific hashtag sidebar).

**Comment by mschwamb** [comment]
To  clarify I'm talking about searching a project talk and it's directing to Zooniverse wide talk when it shouldn't.

**Comment by alexbfree** [comment]
thanks Meg, I updated the above to include that. You just discovered the tip of the iceberg of a series of related issues here :-)

**Comment by mschwamb** [comment]
@alexbfree this is actually residual - all of these link issues in Talk were fixed in Talk a few months ago I think and it seems to have been reintroduced a few weeks ago

**Comment by alexbfree** [comment]
good to know, thanks.

**Comment by mschwamb** [comment]
@aliburchard I noticed you were making a list - a bunch of features like this no longer work in Talk for about a month  now in case that's helpful to point it out in the long list of tickets

**Comment by mschwamb** [comment]
@parrish is there a fix waiting to be deployed on the production version? This is still happening for me

**Comment by parrish** [comment]
Yeah, forgot to link it up.  It's the same issue as #2366.  Fixed by #2604.
