### ISSUE TITLE
Limitation of size of images

### ISSUE THREAD

**Issue by AlexLoosIDMT** [zooniverse/Panoptes-Front-End#2116]
subject images are limited to 600kB which might be a bit too low for many applications...

**Comment by chrislintott** [comment]
If you have specific applications in mind where this is a problem - please let us know.

Chris

**Comment by mkosmala** [comment]
@chrislintott @aliburchard I've got Harvard colleague who wants to do a Notes-from-Nature style project. We're finding that 600kB is going to be too small to do justice to the collection images. In particular, I think zooming (just like in NfN) makes more sense for this project than dividing up images into smaller chunks. Thoughts?

**Comment by aliburchard** [comment]
@mkosmala I was just going to ask someone to look at how big those were  :)

I think that the resolution on 600kb images can be really really good if they're sampled down properly. 

Alex, I'm going to go ahead and close this issue as a wontfix, since we are keeping that limit in place for standard projects because we've learned from experience that 1) 600kb is more than enough for most projects and 2) without that limit, things get messy quick.
