### ISSUE TITLE
Free text search_Talk

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#2126]
Hey all, possibly @brian-c and @parrish in particular. I've had trouble finding specific subjects on Talk, where people have made a discovery or asked a question. I don't see an issue for this, but https://github.com/zooniverse/Panoptes-Front-End/issues/868 (I think) touches on something similar. Is it possible to allow searching without indexing (probably a dumb question)?

**Comment by parrish** [comment]
Right now, it should be returning subject results only when the subject has been commented on.  Otherwise, it doesn't attempt to index subjects.

e.g. this [subject](https://www.zooniverse.org/projects/zooniverse/pulsar-hunters/talk/subjects/1352453) has [search results](https://www.zooniverse.org/projects/zooniverse/pulsar-hunters/talk/search?query=1352453), but this [subject](https://www.zooniverse.org/projects/zooniverse/pulsar-hunters/talk/subjects/1352454) doesn't have [search results](https://www.zooniverse.org/projects/zooniverse/pulsar-hunters/talk/search?query=1352454).

If that's not the behavior you're seeing, then there might be a bug.  Do you have a specific subject/query that's problematic?

**Comment by VVH** [comment]
Thanks @parrish. I think that this is working how it should.
