### ISSUE TITLE
Video task: annotate events as they occur during playback

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#2144]
This is basically porting the Solar Stormwatch 'What's That?' task to PFE. A task which allows you to record the times at which defined events occur during video playback. Stormwatch implemented this as a set of pause/record buttons, displayed after the video player. Pressing a button records the event type and current time of the video. Multiple events can be recorded for each type, so the annotation returned will probably be an array of arrays.

![image](https://cloud.githubusercontent.com/assets/59547/12580913/3de22f48-c42b-11e5-809a-5f49ddddc6c8.png)

**Comment by eatyourgreens** [comment]
Pinging @brian-c and @itsravenous since this probably overlaps with #1965 and #2137

**Comment by itsravenous** [comment]
Yep, so #1965 modifies `<SubjectViewer />` so that it delegates the rendering of a single image/video (and any drawing tools for it) within the subject to `<FrameViewer />`.

I think your controls need to be per-video, in case you have two videos in one subject (or am I over thinking this?), so they would end up being injected into `<FrameViewer />` just as drawing tools currently are (the pause button method would work fine - you could e.g. have a popup come up when you click pause to choose the event to record at that timestamp).

**Comment by brian-c** [comment]
Should I create a separate PR with just the classifier changes needed for the combo task? The combo task itself shouldn't step on anybody's toes, but there are some changes to how tasks report their changes.

**Comment by eatyourgreens** [comment]
@itsravenous I think the marking controls can probably be rendered by the task's `AfterSubject` hook, in which case they should work fine with your branch. Does your branch pass the frame number through to that hook, or does each frame just render the same `AfterSubject` call?

**Comment by eatyourgreens** [comment]
@brian-c that sounds like a sensible approach to me. :+1:

**Comment by itsravenous** [comment]
@eatyourgreens yep, frame number [is included](https://github.com/itsravenous/Panoptes-Front-End/blob/subject_viewer_frame_wrapping/app/classifier/frame-annotator.cjsx#L102) in `hookProps` which is passed to `AfterSubject`. I misspoke before, I meant "injected into `<FrameAnnotator />`".

**Comment by trouille** [comment]
@eatyourgreens Molly Wick of the Environmental Protection Agency in the U.S. is interested in setting up a video project. She asked, "would it be possible to have users watch the video clips and then clicking on a fish when it appears as the video is playing so that the presence, location of the fish, and the timestamp of the video are recorded."

Could you update on if any work has been done towards this? Just wanted to be sure I knew where things stood before talking w/ her. 

My plan is to encourage her to set up a project that doesn't require annotations unless she has plans to fund the development effort or you let me know that we're very close to being able to do video annotations and just a few days of time is needed.

**Comment by eatyourgreens** [comment]
@trouille Solar Stormwatch used a slideshow, instead of video, in the end so this wasn't needed.

I'm going to close this as the last activity here was over a year ago.
