### ISSUE TITLE
"Toggle flipbook mode" not hidden for single image subjects

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2169]
Following some discussion with @itsravenous and @eatyourgreens it was established that the first button under a subject in Talk is called "toggle flipbook mode" and should be hidden for single image subjects. 
Currently it is still clickable, the icon changes but it does nothing for single image subjects.
See for example https://www.zooniverse.org/projects/aliburchard/wildebeest-watch/talk/subjects/464038

**Comment by eatyourgreens** [comment]
Might be a bug in the check to display that button here https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/subject-viewer.cjsx#L89-L92

@itsravenous Should the defaults for `props.allowFlipbook` and `allowSeperateFrames` be `false`?

**Comment by eatyourgreens** [comment]
@itsravenous I had another look at the Subject Viewer, and found it's checking `props.workflow` here too: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/subject-viewer.cjsx#L70

The problem is, the Subject Viewer doesn't get passed a workflow, because it can be used in contexts outside of the classifier, where a workflow wouldn't be defined, only `project`, `subject` and `user`. That might be causing problems on Talk too.

**Comment by itsravenous** [comment]
@eatyourgreens I don't think that line should cause an issue - it's using the existential `?` on `props.workflow`.

**Comment by eatyourgreens** [comment]
I've changed the Subject Viewer in #2172 so that the toggle button isn't shown by default, which ought to fix this.
