### ISSUE TITLE
Missing Subject annotator retired / already seen functionality

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#2170]
@itsravenous @eatyourgreens seems #1965 and 8febdcf72871938c03300c104a8f2fc499dfe602 removed the UI messaging to flag retired / already seen subjects to users...any reason / what's up with that?

**Comment by itsravenous** [comment]
It shouldn't have - I thought I'd kept it on the `SubjectAnnotator`, but sounds like I've maybe lost it in rebasing. I'll check when I'm working (Thurs).

**Comment by camallen** [comment]
We're going to need this ASAP as it's leading to a log of issues with duplicate classifications (wasting volunteer effort), any chance you can get to this earlier / advise which commits had the functionality? 

@eatyourgreens any chance you've got a bit of time to check / work on this?

**Comment by itsravenous** [comment]
Ah yes, sorry, just looked at the commit and `SubjectAnnotator` no longer exists because `app/classifier/index` now just passes `FrameAnnotator` straight to `SubjectViewer`. So we need a way to pass the "badge" into `SubjectViewer` from `app/classifier/index` or just render it in that view instead. I can look at this tonight.

**Comment by eatyourgreens** [comment]
I can look at this today. Changes to the Subject Viewer caused a problem in Talk too #2169 so probably best to abstract this out and either render in the classifier or pass parent context so that the Subject Viewer still works in other contexts.

**Comment by eatyourgreens** [comment]
Should be fixed by #2172
