### ISSUE TITLE
True CSV export / CSV flatfile

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#2198]
Is there a way to get a true (or partially true) CSV export of the classification data?

Although I understand the need for structured data some fields now are buried deep within the current comma separated columns. Mainly using environments not used to dictionaries and or JSON data (R, spreadsheets, ... ) are stuck with a complex workflow for even the most basic enquiries (e.g. which images have been retired?). I feel information such as "subject ID", filename, retired status, should be moved up and be displayed as a separate column rather than buried in Subject_Data. I'm not sure if you could expand the whole file to a flat file CSV, this would be even more convenient (but might blow up the size of the data export). 

For now I'll look into python as it might be more suited for JSON work. But for compatibility reasons a more convenient CSV export would be welcome for sure.

This is the code to recover the filename of a subject in R:

``` R
image_name = unlist(lapply(subject_data,
function(x)unlist(x)[grep("#Filename",names(unlist(x)))]))
```

Similar key information such at retired status can only be extracted using an equally complex command:

``` R
retired_status = unlist(lapply(subject_data,function(x){
  y = unlist(x)[grep("subject_id",names(unlist(x)))];
  if (is.null(y) | length(y)==0){
    return(0) # no retired
  }else{
    return(1) # retired
  }
  }))
```

I haven't looked at the true annotation data but this might be even more challenging to fold out or collapse into an R ingestible data frame.

**Comment by marten** [comment]
All I can say is work is already underway: https://github.com/zooniverse/Panoptes/pull/1553. Although I haven't been able to work on this for a bit (holidays and then other priorities including performance optimizing for being on live tv), I hope to wrap that feature up soon.

Basically we'll be expanding what are now single rows into multiple rows, once for each item in the annotation. We're also going to make the subject information easier to deal with (as long as you only have one subject).

That last parenthetical is the reason it's so complicated right now: internally we're already prepared for dealing with annotations comparing or otherwise relating to multiple subjects at the same time. Which then meant that we had to be able to supply a list of subjects in `subject_data`, because each one will have their own retired status etc. We're not recognising that in doing so, we've made our exports hard to use for 99% of the projects, which only have one subject per classification. This will be fixed.

**Comment by marten** [comment]
Oh, and apart from that, we're also setting up a site with examples of how to process our exports in various languages.

**Comment by khufkens** [comment]
@marten thanks! Didn't find that issue when searching quickly.

What you describe would make handling data far easier (with a slight penalty on file export size). Until then I'll get familiar with some JSON. It's time to brush up on python anyway (need it for other projects), but R compatibility without the complexity would be wonderful (especially for people who are no coding polyglots).

**Comment by mschwamb** [comment]
I can parse the csv with the json in it using python, but I'm becoming the only person in my teams that have time to because it's not a format astronomers and planetary scientists use, and I've been able to parse what all of the coulmns mean, and what the entries in the json format mean.

 Astronomers use fits binary tables and csvs for the most part. And since the json bit is different with the amount of metadata and type of task, I'm finding it takes me a non-negligible amount of time to parse even for the subject data because of the metadata is in json format. I'm finding I'm investing more time in parsing the files and having to explain what content is in them to other team members I have had to do with Ouroboros projects. It would be helpful if this was a straight csv  output

**Comment by khufkens** [comment]
@mschwamb I concur.
You end up with loop after loop after loop to deal with data. Although dictionary keys make this slightly easier than in R, conceptually it remains the same. Hence, I still did everything in R after all (after messing with Python a bit).

If anyone knows a routine to explode a JSON nested list file into a flat table let me know.

**Comment by mschwamb** [comment]
@khufkens I've just written something more generic than I was doing before in python to flatten the subjects csv if you assume that subject sets you're interested in are the same in terms of the amount and type of metadata. Needs some minor tweaks to apply to a different project but might be useful for you. I put it all on https://github.com/mschwamb/p4t_utils I'll be tackling the classifications file

**Comment by camallen** [comment]
@aliburchard does that script @marten helped you write deal with exploding arbitrary json fields?

**Comment by khufkens** [comment]
Thanks @mschwamb, will look into it.

**Comment by aliburchard** [comment]
the script @marten "helped" me write (read: he wrote it on my computer) is just for camera traps but he is actively working on generalizing it!

**Comment by alexbfree** [comment]
linked ticket for the CSV export feature: #2244

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
