### ISSUE TITLE
Design and implement CSV export feature.

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2244]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

**Comment by camallen** [comment]
pretty sure we already have this it just depends on making the api data dumps in a true csv format, no? E.g. https://github.com/zooniverse/Panoptes/pull/1553

**Comment by camallen** [comment]
@alexbfree pretty sure the csv exports already exist in the project builder...?

![image](https://cloud.githubusercontent.com/assets/295329/13467260/5726d874-e095-11e5-9657-32350b91c7a8.png)

**Comment by aliburchard** [comment]
@camallen those are json/csv blobs. For Snapshot (and the other projects) we need true CSVs, which Marten is already working on. 

Specifically for Snapshot though, we need the data out in the same format as our weekly dumps since we don't have the manpower to rewrite our database importation scripts after a move to Panoptes. So I think that's what this addresses -- ensuring that Snapshot data out are in the same format as current dumps.

**Comment by aliburchard** [comment]
oh, sorry, I see you've already addressed that in 1553

**Comment by aliburchard** [comment]
@alexbfree - just chatted with Cam about this. I think this isn't actually a PFE issue. We have an open issue for converting JSON --> CSVs, and there already exists a "csv export" button (1553). So I think this can be closed.

**Comment by marten** [comment]
Keep in mind that we might want to make both the old csv+json monstrosity and the newer csv files available. I'm fine with closing this for now though, we'll cross that bridge when (if!) we get to it
