### ISSUE TITLE
Unable to click to choose between tutorials 

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2581]
On Chrome, on mac. 

It's not allowing me to make a choice between the two tutorials that are available. 
@srallen I've added you as a collaborator on the project I'm trying this on:
https://www.zooniverse.org/lab/2659/workflow/1898

<img width="771" alt="junk" src="https://cloud.githubusercontent.com/assets/4975655/15258362/c353e506-1910-11e6-8eb2-3fbb30aec492.png">

**Comment by srallen** [comment]
The Panoptes issue to deal with the linking error is merged, but currently only deployed to staging. Panoptes deploys to production are done manually and it looks like still needs to be done for the recent merge. It wouldn't be a good idea to do a deploy late on a Friday. We'll need to wait till early next week.

**Comment by trouille** [comment]
OK, I see. Thanks for the clarification.

**Comment by brian-c** [comment]
Ah, I hadn't even thought of that, sorry. That merge can be reverted if it's causing issues.

**Comment by srallen** [comment]
@brian-c I don't think we need to revert. I believe all of the pre-existing tutorials are linked to all workflows on a project when zooniverse/Panoptes#1747 was merged. We should just hold off enabling the tutorial feature on any new projects until it's in production on the back-end. We can ask to have the rake task rerun and Panoptes to be deployed on Monday.

**Comment by mschwamb** [comment]
@srallen and @brian-c  I'm looking at Comet Hunters - the tutorial is showing right now, but the box is unchecked in the workflow - does this mean I need to have to unlive the project and select the tutorial and then make the project live again when the back end is updated  or is this bug mentioned just not showing the tick mark on the project builder.  Thanks.

**Comment by srallen** [comment]
@mschwamb The tick mark will show up correctly when the back-end is deployed. You shouldn't need to unlive it, check, and make it live.

**Comment by mschwamb** [comment]
Thanks @srallen

**Comment by camallen** [comment]
the backend changes are deployed now

**Comment by mschwamb** [comment]
An FYI - On the a project I'm building that is still in development I can now select which tutorial I want for each workflow and get the check mark to show on the workflow page. Comet Hunters on the lab pages still doesn't show a check mark after the backend changes have been deployed, but the tutorial is still showing when I go to the classification interface Is that because the workflow is locked because the workflow is live (and when I unlive it to add new data the check mark will appear) or is there a glitch with how the tutorial is being selected?  I can open a ticket if needed

<img width="496" alt="screen shot 2016-05-16 at 7 04 34 pm" src="https://cloud.githubusercontent.com/assets/753325/15287991/7b1302c8-1b99-11e6-91c6-716ef7eced06.png">

**Comment by srallen** [comment]
@mschwamb I checked tutorial with id #5 and it doesn't have a workflow link, so it probably didn't exist when the initial rake task to link them on the back end happened. I've asked @marten to rerun that rake task. Your tutorial still works because we have a fallback in place to first fetch for workflow linked tutorials and if none are found, to then fetch for project linked tutorials. Once we get all the existing tutorials linked to workflows, though, I'd like to take out that fetch for project only linked tutorials and to direct project builders to the interface on the workflow editor to link them.

**Comment by mschwamb** [comment]
@srallen  Thanks - that tutorial has been there since Comet Hunters launched in December which probably explains why it doesn't have a workflow link.-  I presume the rake task was more recent than that?

**Comment by srallen** [comment]
@mschwamb the tutorial for Comet Hunters is now linked to the workflow for the project. Is it correctly showing the checkmark now in the interface?

**Comment by mschwamb** [comment]
Yes it is correctly showing the checkmark now. Thanks
