### ISSUE TITLE
ETC on Stats page seems to  significantly underestimate the time to completion? Says 12 days I get 115 days

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2593]
@CKrawczyk I had to calculate time to completion for Planet Four: Terrains where we do have all the previous completed subject sets linked in the workflow so the stats should be correct. 

Using the database I find that P4T is in need of 80734 classifications to complete the current live dataset. Using the retired flags from the database csv dump 6007 subjects are still live

Of those subjects that are still live, P4T needs 80734 classifications to get all the subjects live to the 20 retirement limit. I'm just summing up 20- classification count for those subjects that do not have the retirement flag set. 

We're doing about 700 classifications per day, so that's 115 days to completion (80734/700.0) not 12 days as the stats page is suggesting

One thing to note is that for all projects launched in June with panoptes launch, there was a glitch in the retirement on the backend and subjects weren't being retired so there are some subjects that got 400 classifications, so if you're just doing number of classifications the project ever received divided by the total needed to finish all the current data it will always give very skewed results for Planet Four: Terrains and those other projects.

**Comment by mschwamb** [comment]
Maybe this is also sorted by zooniverse/Panoptes#1804 ?

**Comment by CKrawczyk** [comment]
The current calculation takes the number of classifications for the past 14 days (excluding the current day) and calculates how long it would take to retire the current workflow via:

`(14 days) * ((number of subjects * retirement limit) - number of classifications done) / (number of classifications in the past 14 days)`

But as you said the glitch early on means `number of classifications done` is skewed.  Unfortunately with the information currently available via the public api (I can't access the original database since that is not public) this is the best estimate I can think of.  As you siad https://github.com/zooniverse/Panoptes/issues/1804 will likely help with this.

**Comment by camallen** [comment]
just thinking about this, when science teams link new / unlink old data that number of subjects can change but the total number of classifications will never decrease here. Not sure how fixing the retired counters will help with a situation like this.

**Comment by mschwamb** [comment]
so this also means that if I change the retirement count on the project this would also be incorrect?  I've changed the retirement count several times depending on stargazing live and other criteria in the past on projects.  Really unfortunate that these stats are not useful. 

I'd love to advertise the stats page with a blog post I'm not sure what to say since for one of my projects it says we're out of data and the other it says we're going to run out in 14 days which isn't true. I guess I'll hold off for now.  Hopefully in the future there will be a better way of reporting the actual status of the project.

**Comment by mschwamb** [comment]
Thanks @CKrawczyk and @camallen for answering my question
