### ISSUE TITLE
Subject upload via URL in the manifest?

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#265]
How easy would it be to add the ability to put a URL in the manifest for each subject - and get Panoptes to use that as the image source - rather than having to manually upload each image from the local machine?

This wouldn't solve the subject set editing issues, but by giving Panoptes only one file (the manifest) to deal with per subject set at least things like subject duplication, metadata management, etc. become the user's responsibility (though error messages on failed downloads, image types, etc. would be handy, in case the user made a mistake with the manifest).

**Comment by twhyntie** [comment]
Happy to close this for now thanks to the fix in [#281](https://github.com/zooniverse/Panoptes-Front-End/issues/281).

**Comment by vrooje** [comment]
I know this is closed but if there is ever an occasion to re-open it in the
future I'd be wary of potential issues with copyright and permissions
involved in letting people specify URLs instead of having to actually
upload the images. This would be rare, I hope, but if a client tries to use
someone else's data without permission we should at least make *them* be
the ones to steal it, instead of letting them just tell us where to look
and watching us do it for them.

**Comment by twhyntie** [comment]
@vrooje That's an excellent point! :-) I was thinking about file selection for multiple uploads (now fixed) or very large subject sets. If a subject set got so big that being able to avoid storing it locally before uploading became an issue, I guess one would be talking to Zooniverse about setting up an independent S3 bucket (or similar) anyway and configuring that as a special case..

You're right, this is a bad idea.

**Comment by camallen** [comment]
Something to think about in https://github.com/zooniverse/Panoptes/issues/443 and https://github.com/zooniverse/Panoptes/issues/425

**Comment by aliburchard** [comment]
@camallen I didn't totally understand the details of the discussion in zooniverse/Panoptes#443 , but am hoping to have a wildebeest project for the Panoptes soft launch that uses all of the Snapshot Serengeti wildebeest photos. Would certainly be easier to provide urls rather than having to script a download of all the images and then upload them again.

**Comment by camallen** [comment]
@aliburchard that discussion is about pluggable subject storage solutions. So not being locked into s3 locations but being able to have Filesystem, S3 and possibly URL links (possibly whitelisted to control ownership).
