### ISSUE TITLE
Formatting problems with iPad (Landscape)

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2672]
As raised by @mrniaboc :
![img_20160608_115136](https://cloud.githubusercontent.com/assets/1473244/15897231/9ba5a7a8-2d8b-11e6-9049-28cfcbea9065.jpg)

The nav bar (overflowing/overlapping), the projects slider(missing/only one chevron showing), and the projects list (only showing 1 per row?) all need attention

**Comment by alexbfree** [comment]
May be specific to old iOS versions...
https://zooniverse.slack.com/archives/dev/p1465395232000247

**Comment by alexbfree** [comment]
we could consider having a “version not supported” message when we detect an unsupported browser version, rather than carrying on...

**Comment by eatyourgreens** [comment]
A couple of screenshots

iOS 8.4
![image](https://cloud.githubusercontent.com/assets/59547/15900453/7fe2573a-2d97-11e6-8611-1eb4c7b729c9.png)

iOS 9.3
![image](https://cloud.githubusercontent.com/assets/59547/15900504/a4c3757a-2d97-11e6-9be7-b163cf35c2a7.png)

From memory, 9 introduced support for flexbox without the `-webkit-` prefix, so that might be the problem.

**Comment by eatyourgreens** [comment]
Fixed by #2680
