### ISSUE TITLE
stage command deploys master to subdir

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#2696]
As of 855155eb90cd3fbae2b22d9244d1b3f2ad1868e4 running stage on the master branch sets DEPLOY_SUBDIR to "panoptes-front-end/master/" when it should just be "panoptes-front-end/".

**Comment by rogerhutchings** [comment]
Just staged a project, and appears to be working as expected atm

**Comment by srallen** [comment]
This issue was about the staging master deploys going to `master.pfe-preview.zooniverse.org` instead of `pfe-preview.zooniverse.org`. There used to be a separate npm script for the branch deploys, but that got moved I think when we moved to webpack into the script for stage which is what jenkins runs. I don't remember the reasoning for this change, but maybe @amyrebecca remembers.

**Comment by camallen** [comment]
Would detecting master branch [here](https://github.com/zooniverse/Panoptes-Front-End/blob/a7dc9f7dfbb7a561c55e533ae78172316706fe54/package.json#L113) and setting SUBDIR to nothing fix it?
