### ISSUE TITLE
IE not showing subject images anymore

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2701]
Was there a change to how images are displayed? I've got two people now reporting the same thing , that in IE they don't see any subject images on Comet Hunter in the classification interface. The rest of the side loads correctly, but no subject image displays 

Talk discussion [here](https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/60615?comment=119430 )

**Comment by srallen** [comment]
Looks like the IE11 specific flex rule got removed in #2689. @brian-c this last got reported and fixed in #2330 via feature detection of IE11. I think it's a bug in the spec implementation with IE 11. It may be related to the [min-height bug described here](https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items). I don't like it, but I'm not sure of a better way to deal with this outside of the feature detection and specific IE11 fix.

**Comment by brian-c** [comment]
Will investigate, I was messing around in there yesterday.

**Comment by brian-c** [comment]
@srallen I don't think I removed the rule, instead it should now be applied it to all browsers. I checked IE11, maybe not IE 10 though.

**Comment by mschwamb** [comment]
I asked the volunteer who gave the most detail if they could give version numbers for OS and browser, so hopefully you'll have that soon if you check back to the Talk thread later.

**Comment by srallen** [comment]
I'm talking about the removal of L68-69 in `subject-viewer.cjsx` and L51 in `classify.styl`: https://github.com/zooniverse/Panoptes-Front-End/pull/2689/files#diff-7abae5c13f5f8bcb3c2e3dc1eb32cd86L68

The subject viewer is now a small pixel and is not expanding to the height of the parent like it was prior to the IE 11 specific flex prop that I added in #2330.

I wouldn't bother with IE 10. The flex spec is even more broken in that version.
