### ISSUE TITLE
Lock workflow

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Panoptes-Front-End#272]
Allow project owner to 'lock' a workflow so that no changes can be made. Owner can unlock at will.

**Comment by aliburchard** [comment]
I think this will *primarily* protect a project owner against careless collaborators (who might not have fully processed the consequences of changing a workflow). But it also serves to protect a project owner against themselves making a silly mistake.

**Comment by vrooje** [comment]
I agree, good idea.

**Comment by mschwamb** [comment]
if you are in the unlocked state should there be another level of safeguard be another like if you click save it prompts to double check 'do you really want to delete all your previous classifications by hitting save. Click continue to save your changes and reset the classification database '?  (So that it as difficult to hit delete as to save the live workflow) in case of accidental clicks or cats walking across keyboards in this unlocked mode.

**Comment by vrooje** [comment]
Note this may not be as important given that classifications are not
deleted (the current warning isn't accurate), but are instead reported with
a different workflow version.

**Comment by simoneduca** [comment]
I believe the lock is implemented now on the evidence that I can't modify the active workflow I'm a collaborator off. Closing for now, but happy to be overruled if I misunderstood.

**Comment by srallen** [comment]
They're talking about locking the workflow from changes from other collaborators regardless of the state of the project. The current lock is only in place when the project is live and the workflow is active. I'm not sure if this is still really needed since I believe this was requested prior to that change.
