### ISSUE TITLE
Can't create new subject sets through project builder.

### ISSUE THREAD

**Issue by dwright04** [zooniverse/Panoptes-Front-End#2752]
I have 28 subject sets.  I can only see 20 (issue [#1136](https://github.com/zooniverse/Panoptes-Front-End/issues/1136)) of these in the project builder sidebar.  I have a subject set called "Untitled subject set", but I cannot select it from the sidebar to upload subjects, change the name or delete it.  As new subject sets are created with the name "Untitled subject set" ([#1923](https://github.com/zooniverse/Panoptes-Front-End/issues/1923), [#1924](https://github.com/zooniverse/Panoptes-Front-End/issues/1924)) I get the error "Validation failed: Display name has already been taken" and can no longer add new subject sets through the project builder.

![screen shot 2016-06-28 at 15 00 34](https://cloud.githubusercontent.com/assets/7902164/16418308/204fbbf0-3d41-11e6-97e9-97bde64a9de2.png)

**Comment by aliburchard** [comment]
Is this maybe because we don't elegantly handle lots of subject sets? (This is a problem in a number of projects -- and if we start telling teams with hundreds of thousands of images to limit their subject set size to 10s of thousands of images, then this is probably going to happen more and more...)
