### ISSUE TITLE
Layout: Zoo home logo not aligned with rest of project menu bar

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2799]
I noticed that the new top right Zoo home logo isn't correctly aligned with the rest of the project menu bar:
![screenshot 2016-07-18 13 41 34](https://cloud.githubusercontent.com/assets/1473244/16915058/8be61ee8-4ced-11e6-97e1-74ff90f7fb2e.png)

Also, it seems too close to the right hand side of the window. Might be specific to Macs? Since there's always a scrollbar there.

**Comment by alexbfree** [comment]
cc @jwbmartin

**Comment by jwbmartin** [comment]
Yeah it should align

**Comment by MvGulik** [comment]
Seems fine to me.
![image](https://cloud.githubusercontent.com/assets/666868/16929054/1ade6f54-4d36-11e6-855a-9f5c829d5c4d.png)

It seems more a case where one of the menu-bars (main-zoo-bar, or project-bar) seems in need of adopting the formatting or the other.

**Comment by mschwamb** [comment]
I think with the recent design changes (thank you for putting the login/register back in the project space), you want to leave it offset otherwise any project owner added links will get shoved to the next line if the project owner has more than one extra link, where as the offset allows one or two links to fit on the same link as the auto generated panoptes links.  

<img width="1160" alt="screen shot 2016-09-03 at 9 04 15 am" src="https://cloud.githubusercontent.com/assets/753325/18227123/a853a0cc-71b5-11e6-95e3-771173fcde77.png">

In the case of P4:T we have  a site guide and blog as extra links

**Comment by parrish** [comment]
Yep.  Not relevant anymore
