### ISSUE TITLE
World Wide Telescope bugs

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2861]
Testing out Astronomy Rewind and came across a few issues/questions. 

1) 

I thought we had found a fix for if a volunteer marks the axes numbers inside the box they've drawn around the figure itself. Is that not the case? 

In this test (within the old https://www.zooniverse.org/lab/1856/workflow/1700 Workflow 2 for images with sky axes labeled), the WWT button didn't come up as an option when I marked the image as shown. 

<img width="1307" alt="marksinside-nowwt" src="https://cloud.githubusercontent.com/assets/4975655/17454485/44668318-5b5d-11e6-8a60-8b510da744ff.png">

**Comment by trouille** [comment]
The following issues have to do with a new consolidated workflow I made. @wgranger I remember you saying that much of the WWT functionality is hardcoded to go with the existing workflow at that time -- https://www.zooniverse.org/lab/1856/workflow/1700, so it's likely related to me creating a new workflow. 

#2)

In this new consolidated workflow (https://www.zooniverse.org/lab/1856/workflow/2371), one direction in the decision tree just has people saying there are graphs or tables or nothing in the journal page. So there's no WWT output. This causes the workflow to freeze. 

<img width="1236" alt="nowwt-stuck" src="https://cloud.githubusercontent.com/assets/4975655/17454500/e3423216-5b5d-11e6-9370-2aa407302e18.png">

**Comment by trouille** [comment]
#3) 
In this new consolidated workflow (https://www.zooniverse.org/lab/1856/workflow/2371), the other direction in the decision tree is to annotate images that are sky images, with some having axes labeled. But even in this direction of the decision tree, the WWT functionality appears to not work. See the broken image icon in the attached image. 

<img width="1256" alt="wwtbutton-broken" src="https://cloud.githubusercontent.com/assets/4975655/17454510/14fcf4e4-5b5e-11e6-9b64-24d5864bc516.png">

**Comment by trouille** [comment]
#4)
I've created the Astronomy Rewind: Education site. @wgranger you're a collaborator on it. It has a simple workflow just for images that do have axes values and units labeled. But the WWT functionality doesn't work for it either.

**Comment by trouille** [comment]
5) Something funky in the metadata that got uploaded with the pilot subject set for Astronomy Rewind. Check out the 'i' for images at https://www.zooniverse.org/projects/zooniverse/astronomy-rewind/classify?workflow=1701

The problem I saw is that the last row, with publication_year, also has an imageURL that looks like it was just included by mistake.  It's the same imageURL in all image's metadata info.

**Comment by wgranger** [comment]
1) This was originally "fixed" by allowing the classification to continue even if a user placed a mark inside the chart, which confuse the code. The explanation for this is is listed under "Issue with Axis Values" for #2676 .

2) Right. I would assume this bug is popping up because the WWT code is trying to process the annotation based on the steps of the original workflow that was applied to the code and not on the new consolidated workflow. 

3 - 4) Similarly to the second issue, these are popping up if the workflow diverges from the original workflow we used when writing the code. I'm not sure if there's a way around this, but it's worth a conversation with @amyrebecca to see if the code can become more flexible.  

5) I'm going to try uploading this pilot data again. After talking with Andrea last Friday, we determined one (seemingly minor) issue that occurred, so it's possible it could have affected the upload in such a way.

**Comment by trouille** [comment]
For 1 -- OK. I've added additional wording in the instructions for volunteers to mark the axes values outside their original rectangle. Let's see how this goes when we do the beta test - that will tell us whether we need to spend more time seeing if we can make a true fix for this. 

For 2-4: Let's talk Monday -- we'll find a good solution. 

For 5: Great -- Hope it's a simple fix!

**Comment by wgranger** [comment]
Issue #5 appears to be fixed through the most recent subject upload. (set 5516).
