### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2948]
i.e. Urban Wildlife Watch, or Camera Trap Consortium

see https://github.com/orgs/zooniverse/projects/8

**Comment by mcbouslog** [comment]
posting white board notes for reference:
![img_20160915_144232](https://cloud.githubusercontent.com/assets/12118751/18597698/bdf4a14c-7c14-11e6-9b23-45905fe69b15.jpg)

*work in progress

**Comment by trouille** [comment]
@chrislintott @zwolf @parrish @marten spoke more about Federations today. In Zach's brief recap with me, 3 questions came up that would be good to clarify:

1) Do you foresee an instance when a project would need to be part of two federations? I don't, but wanted to know if you had one in mind. This has to do with single table inheritance. 

2) Do you foresee an instance when a federation would need more than one template project? I don't, but wanted to know if you had a scenario in mind. Because a project can have multiple workflows, tutorials, mini-courses, seems a federation could include all needed info in a single template project. (Note: We don't currently support multiple field guides, but perhaps we could if the need arose). 

3) In the image above, the middle column shows the interface that serves double duty as the template UWW project AND the administrative portal for the UWW owner to add new members and make project cards appear on the UWW landing page.

Do you feel strongly whether this is a good choice, or whether it would be better to have a separate UWW template project from the interface where the UWW owner adds new members, etc.?  

There are differing opinions within the back-end devs on which is a better choice. From my understanding, positives and negatives in both options. Do you have a strong opinion? 

We could have a chat about this after the Monday 3:30 BST dev stand-up when @camallen is back in town, if that would be useful to hear pros/cons and reach a decision.

**Comment by chrislintott** [comment]
1. No, I think that's too confusing and would cause problems with permissions, so let's stick to one.
2. I can imagine why that would be needed - for example, Galaxy Zoo federation with a 'classification' template and a 'modelling' one. However, I think we could get away for now with supporting a single template as that's already a huge improvement on where we are. 
3. I think we should split the two, keeping the 'template project' functionality separate from the federation management interface. They're different things really and while they're combined here it would be good to have them split later.

**Comment by trouille** [comment]
Quick question @chrislintott What do you mean by a 'modelling' template?

**Comment by trouille** [comment]
@camallen @marten @parrish @zwolf @chrislintott Here's an updated image to reflect the need for a federation management interface separate from the federation template project. 

In/after Tuesday's standup, it'd be very helpful to talk about this and see if there are pieces of this large effort that Zach can work on this week, prior to ZTM.


![img_20160926_110406888](https://cloud.githubusercontent.com/assets/4975655/18842085/7bac3c74-83d9-11e6-87b3-9cb4bace7d0c.jpg)

**Comment by srallen** [comment]
For Organizations Lab (as a separate single page app that eventually the rest of project builder may migrate to):

- [ ] Review and determine what to do with shared code and components listed in #3302 
- [ ] Setup app boilerplate. Consider adding coffeescript support in case we migrate rest of lab as is.
- [ ] Build out editor functionality for organizations details, visibility, collaborators, about page content. Much can be modeled after project lab. _Is there any functionality missing? I'm basing this off of what I can read in the above image of the white board._
- [ ] Authentication setup initially modeled after Wildcam/Wildcam Lab's setup
- [ ] Deploy to lab.zooniverse.org (and its related staging) subdomain and setup links from PFE to it.

**Comment by mcbouslog** [comment]
Jordan's initial design for organization landing page:
![organization page new](https://cloud.githubusercontent.com/assets/12118751/23908038/d6d93e66-08a0-11e7-8d4e-7e4cbe335464.png)

**Comment by beckyrother** [comment]
Slightly updated Jordan's mockups: 
[Organization Page No Categories.pdf](https://github.com/zooniverse/Panoptes-Front-End/files/965446/Organization.Page.No.Categories.pdf)
[Organization Page.pdf](https://github.com/zooniverse/Panoptes-Front-End/files/965445/Organization.Page.pdf)

And here is a style guide:
[organizations-style.pdf](https://github.com/zooniverse/Panoptes-Front-End/files/965448/organizations-style.pdf)

**Comment by beckyrother** [comment]
Here's the whole flow: 

### From projects page
Organizations will be a tab on the Projects page next to Active, Paused, Finished:
![projects page](https://cloud.githubusercontent.com/assets/1392130/25638536/5b3e52d0-2f4e-11e7-90d2-e9a0e531f066.png)

Organization cards will have slightly different visual treatment to project cards:
![projects page organizations list](https://cloud.githubusercontent.com/assets/1392130/25638586/8b68078a-2f4e-11e7-90f4-93e7e172feca.png)

***

### On Project Home Page
Organization title will be listed above the description on the Project Home Page:
![project home page](https://cloud.githubusercontent.com/assets/1392130/25638661/b401dda6-2f4e-11e7-8cf6-b73bdb7f2d14.png)

***

### Organization Home Page Options
Two options for the Organization Home Page, depending on the number of projects and if they are in different categories:
![organization page](https://cloud.githubusercontent.com/assets/1392130/25638723/ebf7745a-2f4e-11e7-8765-0e47281460a2.png)

![organization page no categories](https://cloud.githubusercontent.com/assets/1392130/25638726/ef243726-2f4e-11e7-91ce-788505f75099.png)

**Comment by trouille** [comment]
@chrislintott Pinging in case you have comments/feedback.

**Comment by mcbouslog** [comment]
I've separated pieces contained in this issue to individual issues in relevant repos. This was originally the "Epic" issue within ZenHub, but in light of the Organization GitHub project and the separate issues I'm going to close this issue. It'll be in the Done GitHub Organization project column for reference, or feel free to re-open if prefer.
