### ISSUE TITLE
the x to close the ellipse marker can be very close to/ on top of the handle to adjust its size

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#296]
I noticed a few times depending on how you draw it the ellipse tool x marker to delete it gets very close to or exactly on top one of the  handles to resize. I can see why you might not want the x to be in the center of the ellipse (the way it is on Planet Four) What about fixing the position of the x so it's always on the opposite side of the ellipse away from the marker and doesn't move?

![screen shot 2015-05-08 at 4 38 26 am](https://cloud.githubusercontent.com/assets/753325/7525454/2cbe76b8-f53c-11e4-89e0-a650799d690a.png)

![screen shot 2015-05-08 at 4 32 25 am](https://cloud.githubusercontent.com/assets/753325/7525461/3d0eb690-f53c-11e4-8369-eb1ec0f1c7da.png)

![screen shot 2015-05-08 at 4 33 39 am](https://cloud.githubusercontent.com/assets/753325/7525462/3d106080-f53c-11e4-927f-3b078e7594cf.png)

**Comment by vrooje** [comment]
Related: for one of the projects we're hoping to launch with it's sometimes hard to draw the marks (lines) as required because the lines need to overlap and the close button is sometimes exactly where I need to draw the second line; or it's big enough, and the line small enough, that I can't move the line.

![screen shot 2015-05-22 at 12 22 08](https://cloud.githubusercontent.com/assets/2357126/7769682/f1b91aa8-007d-11e5-9551-39d23ffce906.jpg)

And here is one that was as close as I was able to get; the smaller line should intersect the large one at the center of each, and I would have liked the smaller one to be even shorter...

![screen shot 2015-05-22 at 12 17 03](https://cloud.githubusercontent.com/assets/2357126/7769702/2cbc4dfa-007e-11e5-933e-3626fecf8355.jpg)

This is also related to #204 - @brian-c I called this an enhancement before but I'm wondering if this is going to seriously affect my classifications for this project.

**Comment by khufkens** [comment]
FYI: I have similar issues when drawing small lines in my "Jungle Rhythms" project (https://www.zooniverse.org/#/projects/khufkens/jungle-rhythms/classify). The X will obscure the feature needed to be marked. Furthermore, it does not serve any purpose at the time.

**Comment by mschwamb** [comment]
I'm playing around with the tools for the ellipse and the circle and I find I get the same thing for the circle, I can rotate it so that the adjust tool is right on top of the x and then I can't get rid of the marker and it's a bit hard to get it to adjust again. 

Also I find it really visually distracting that the position of the x is changing as I resize the ellipse where as the other 2 handles stay in the same relative position on the outside. I think fixing the relative position of the x like the adjustment handles behavior would make it an easier tool to use for both the ellipse and the circle marker.

<img width="296" alt="screen shot 2016-03-20 at 5 41 43 pm" src="https://cloud.githubusercontent.com/assets/753325/13903787/00c8360c-eec4-11e5-9ac3-ac240bba1668.png">

![ellipse](https://cloud.githubusercontent.com/assets/753325/13903804/803d97ce-eec4-11e5-847b-591dc0e680ac.gif)

**Comment by srallen** [comment]
Closed by #2816
