### ISSUE TITLE
making by default any urls in metadata open in a new tab

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2962]
A [request](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/9/81505?comment=160768) from the P4:T volunteers. I could add in the next manifest file the markdown to open in a new tab, but I'm a little wary of adding in markdown as the metdata also shows up in the subject csv dump and its easier to parse without the markdown. 

 If it's easy maybe if there is a url written out in the metadata for  a subject it could default to opening it in new tab if clicked. @parrish what do you think.

**Comment by parrish** [comment]
We actually want to discourage people from adding links that `target="_blank"`.  Granted, the site seems to have mixed opinions on that...

**Comment by mschwamb** [comment]
metadata is an odd case, it's weird to put markdown in there because you also use that metadata in analysis. I though the site filled in the target stuff when it made it a hyperlink?

**Comment by vrooje** [comment]
I've just had a message from one of the volunteers on PRN that he was very happy to have found the metadata button but very sad to have clicked it because the link opened in the same window and the 60+ markings he'd made of damaged buildings were no longer there when he pressed the Back button. 

Just to confirm, I can use markdown in the manifest and specify that links open in a new window/tab? 

I really think that should be the default behavior, or that there should at least be some warning that a classification will be lost if clicking away.

**Comment by srallen** [comment]
We could check for the presence of annotations for classification that haven't been submitted yet and could possibly do two things:
- Save the unfinished classification to Panoptes and load it back up when they revisit the project
- Have a modal pop up warning they're navigating away from the site with an unsubmitted classification and ask if they're sure. We could have this work at a project level.

**Comment by eatyourgreens** [comment]
Is there any particular reason why we don't open links from the metadata in a new tab? We could use a named target if `target=_blank` is annoying.

**Comment by srallen** [comment]
Whenever we've had discussions about link behavior, the consensus from what I remember is to be consistent about not opening in new tabs or overriding typical browser behavior. I don't really care, but would prefer consistency with behavior with internal vs external links. Either they all open in the same current tab or all internal links stay in the same tab and external links go to a new tab.

I think my idea about saving unfinished classifications with projects when navigating away though would have benefits with more than this issue. Transcription projects built with the project builder might like that.

**Comment by eatyourgreens** [comment]
Shakespeares World and OWD warn on [window.beforeunload](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload), if there are annotations in the current classification. From memory, browsers have strict limitations on that event handler, because it's been badly abused by malicious sites, so there's not much you can do beyond ask a Yes/No question. For example, you probably couldn't fire an API call to save classifications before leaving the page.

We should definitely be consistent about links and new tabs. It varies from project site to project site. The top-level navigation on Shakespeares World is really bad, opening everything in a new tab.

**Comment by eatyourgreens** [comment]
From an accessibility point of view, new tabs should be avoided, since they break the back button which can lead to confusion in getting back to the original page. 

That said, they do make sense when following a link would interrupt or destroy work in progress eg. opening a help page when filling out an online form. I think classifying on Zooniverse falls into this category.

**Comment by srallen** [comment]
Perhaps then the simple solution is to have a Yes/No modal if they have an unfinished classification to confirm they want to navigate away. We won't be saving the classification, but at least we can warn it will be lost. I think it will be more involved to try to implement certain link behavior in certain contexts.

**Comment by vrooje** [comment]
I agree and I like the idea of a named tab, which volunteers could just keep open and which would change as they click. We'd have to message that to them via Talk or a tutorial (or both) but that's fine.

**Comment by camallen** [comment]
is it worth thinking about sessions storage for a classification / subject id combo that stores the json rep as it's annotated? Think how github stores your text for issues, etc that persist on page reloads, etc. 

This can be reloaded on page refresh though the subject may not be available still so might need to cache that as well. Note caching brings with it other issues :( 

Personally i despise sites that open new tabs for me.

**Comment by eatyourgreens** [comment]
@camallen that's exactly what OWD does. I think Condor Watch and Shakespeares World do the same thing too.

I'm not sure PFE has been set up to load and render existing annotations, so that might be a sticking point for some of the tasks.
