### ISSUE TITLE
In Zooniverse-wide Talk boards, a subject mentioned in a comment should provide a link to the subject's Talk page.

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#3011]
## Expected behavior

In Zooniverse-wide Talk discussions, any subjects included in a comment using Talk's "Linked Image" functionality should provide a link back to the subject's Talk page. This is currently working for subjects mentioned in project-specific Talk discussions, where the Subject ID provided above the image links to the subject's Talk page (e.g., https://www.zooniverse.org/projects/zooniverse/decoding-the-civil-war/talk/432/62337).  
## Current behavior

_Please include any error messages from the browser console and/or screenshots_
In Zoo wide Talk discussions, a mentioned subject does not provide a link back to the subject's talk page. In the image below, the Subject ID text above the image should link to the subject's talk page.
<img width="250" alt="should_subject_link" src="https://cloud.githubusercontent.com/assets/7684729/18452889/631ccae8-7902-11e6-9753-270f8a82453d.png"> 
## Steps to replicate

For an example, see the following talk comment: https://www.zooniverse.org/talk/68/1138?comment=90389
## Additional information

Reported by @mrniaboc.
- **Operating system:** OS X El Capitan
- **Browser:** Chrome, Safari, Firefox

**Comment by parrish** [comment]
This is an unfortunate side-effect of a premature feature implementation in Panoptes:  since subjects can be shared between multiple projects, a project can't be implied without the comment being left in a project context.

Ideally, a non-project oriented subject page would exist that would show/switch between multiple project contexts.

There would definitely need to be some design effort to present that page in some sensible manner.

In the meantime, we're just not attempting to build links for those subjects.
