### ISSUE TITLE
Organizations: Talk

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3012]

**Comment by mcbouslog** [comment]
see https://github.com/zooniverse/Talk-Api/issues/121

**Comment by eatyourgreens** [comment]
I don't think the Talk API needs any changes, but the organisation lab should create a new Talk section called `org-${organisation.id}`, with boards, and then a new instance of Talk should be rendered for that section ID.

At the moment, Talk code is hardwired to use `project-${ID}` as section identifiers, so that code would need to be replaced and generalised. Maybe pass in the section ID as a prop when rendering a new instance of Talk for a project/organisation.
