### ISSUE TITLE
What is ' You can create a list of suggested tags to use.' on the Talk project builder page and where does it get shown?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3049]
I saw this. It looks new and handy, but I don't know how it works or where it shows on Talk. 

<img width="829" alt="screen shot 2016-09-17 at 10 50 08 am" src="https://cloud.githubusercontent.com/assets/753325/18610900/a5b00cce-7cc4-11e6-822b-a4a538025505.png">

@parrish can you tell me how it works? Thanks!

**Comment by parrish** [comment]
It's basically a way of encouraging tag use.  Suggested tags get a slightly higher weight in autocompletion results as well as populating the default list of tags when you first type `#`.  Ideally this should also cause tag usage to converge more readily too.

e.g. If you wanted to encourage "transit" rather than "transits" or "transiting", you could add it as a suggested tag that would tend to autocomplete before the others.

**Comment by mschwamb** [comment]
Gotcha. Thanks. I might add in a line to summarize what you said in a PR so it's clearer in the project builder if that's okay with you.
