### ISSUE TITLE
Images for help text and content pages

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#306]
I'm trying to include images in the help text and content pages. As far as I understand from the markdown tutorials, if I want these to display for everyone, the images need to have a URL somewhere. Where can I put these images online so that they are otherwise private but have URLs? I am currently doing this for Zooniverse-sponsored projects, but we will also need to provide guidance for science teams. @camallen @brian-c @rogerhutchings @perry thoughts? (You last two seem to have a lot of images at your disposal...)

**Comment by mkosmala** [comment]
I've built a separate GitHub project and I keep my images there and reference them in the Markdown. I believe the developers are working on arbitrary images uploads so that you'll be able to do this pretty seamlessly at some point.

**Comment by aliburchard** [comment]
Oh that's interesting -- I'd never even thought about using GitHub! Jim pointed out that I could create links to images stored in dropbox, so I've been using that as a temporary solution, but the arbitrary image upload would be really cool. Thanks :)

**Comment by mkosmala** [comment]
Yeah. See: https://github.com/zooniverse/Panoptes/issues/443
It's closed. But I'm not sure of the status on the back-end to support arbitrary images. It's definitely not there yet on the front-end.

**Comment by mkosmala** [comment]
Oh, also the idea to use GitHub was Ed's, but I think it's really only good as a temporary solution. Image loads are not super fast. I haven't tried hooking up a service like 'cloudflare' as Ed recommended, but if Season Spotter goes live before arbitrary image uploads are implemented, I likely will.

**Comment by edpaget** [comment]
@mkosmala I'm not sure we have plans to allow images uploads unattached to specific things like projects avatars or subject locations. That pull request was more about having a generalized way to support those kind of uploads. 

I'm sure we should eventually implement something like that, but there really isn't anything coming soon.

**Comment by mkosmala** [comment]
@edpaget Oh, okay. Well, the avatar and background image are obviously most important (especially for speed of loading). The other use I'm finding is that I need images in my help pop-ups. I suspect that many projects will need/want images in their help documentation. Up to you guys to decide how much support to provide for that.

**Comment by mschwamb** [comment]
I was going to ask about this as well. I think you want a permanent solution on aws because postdocs and scientists leave projects and you don't want to have to reply on their public dropbox folder or a github repo that they may delete.  

I think  having to reply on dropbox or github to show images is problematic especially for help content. Also since things like github and blogs do allow you to upload images, I think science teams are going to expect that this service exists. It's also asking science teams to learn another service and rely on that third party working.

**Comment by chrissnyder** [comment]
Going to reiterate what Ed said. The value for allowing teams to add images to content/descriptions/help dialogs is clear, but it's not on the immediate roadmap.

**Comment by michaelaye** [comment]
Is it not on the roadmap because you are fine with using external services as image servers and would rather spend resources on other issues? Because to me it looks like it is a very principle requirement to have explanations in image form to tell the Citizens what to do. I just don't see that working without using images/graphics.

**Comment by edpaget** [comment]
Now that we have some extra time this is going to be supported. See https://github.com/zooniverse/Panoptes/issues/848

**Comment by mschwamb** [comment]
@chrissnyder this was closed but this feature does not exist on the current preview version of the site. It should be reopened.

**Comment by brian-c** [comment]
Looks like the link got lost in a merge. I'll have a fix up shortly.

**Comment by mschwamb** [comment]
Thanks @brian-c
