### ISSUE TITLE
Add "Finished" banner to retired and out-of-data projects.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#3069]
The idea is to make the search of a project quicker. Adding the banner to the project's avatar is the first step.

Secondly, I suggest to have a submenu under /projects, like the "About Us" page, with the tabs "All" and "Finished". I think it'd would be helpful to have a third tab "Your stats". This would make the users stats page https://www.zooniverse.org/users/user/stats more visible (I didn't know it existed!) 

Thirdly, I suggest we enable project owners to retire their own projects in the project builder.

Please share any thought, pros and cons here.

**Comment by eatyourgreens** [comment]
If we don't want to waste volunteers' time, then I think the default view (All?) should filter out finished projects too.

👍 to allowing project owners to manually retire their projects. I think this is a decision that should be delegated to the people who run a project rather than, say, Zooniverse stepping in and retiring projects for people.

**Comment by simoneduca** [comment]
@eatyourgreens Regarding your first point, do you mean we shouldn't display finished projects with a banner, under the "All" tab?

**Comment by eatyourgreens** [comment]
@simoneduca yeah, I think the projects that you see listed when you first visit the projects page should be projects that need volunteer help. @vrooje suggested moving finished projects to the end of the list. I'd suggest removing them if you can navigate to them in a separate tab.

I think a mixed list of projects, some of which are labelled 'Finished' and some aren't, would just look bad.

**Comment by simoneduca** [comment]
I agree it might look bad and I'd be happy to have finished projects in their own page, but I thought @marten had some good reasons for having the "mixed" of un- and finished projects. Perhaps he could remind us here.

**Comment by mschwamb** [comment]
Should there be two labels? Out of data/paused and Finished. Because if you're out of data the project might not be done. The team might need to upload more. That way finished would really mean the project is finished.

**Comment by simoneduca** [comment]
I think two labels would look very messy. I appreciate the ambiguity though. Perhaps three tabs: "all", "outofdata" and "finished" is a good compromise?

**Comment by mschwamb** [comment]
I like the three tabs idea.  I think 'all' will be confusing if that's just active projects. Maybe call it 'active' or 'live'? Out of Data, I'd call "paused"

**Comment by jwbmartin** [comment]
I like the idea of adding a banner to completed projects avatars on the projects page and then have them pushed to the end of the list my reasoning being this:

You got into a room with three doors. One door you open goes to a beautiful garden. One door opens to a window where you can see the garden but not actually access it while the other door just opens to a brick wall. Wouldn't your immediate response be "Why the hell are these other two doors even here? Like, really!? Why did the architects, contractors, etc even take their time and resources to create these other two doors?" 


Don't make things that just lead to dead ends.

**Comment by simoneduca** [comment]
@jwbmartin Do you mean that, say, the "finished" tab would be a dead end? If so, why?

**Comment by jwbmartin** [comment]
@simoneduca because we would be showing volunteers a bunch of projects they can't contribute to

**Comment by camallen** [comment]
But they still need to be able to use those project cards to find the project status, navigate to talk, etc so from a discovery / data lookup point of view it's useful. Knowing that they don't need any classification help right now is important too.

**Comment by simoneduca** [comment]
@jwbmartin that's true. On the other hand, some users may be interested in looking up something about a project that's been finished and they used to contribute to. The tab would make that easier than going at the bottom of a big project list.

**Comment by jwbmartin** [comment]
Then why do we have a search/filter bar?

**Comment by simoneduca** [comment]
Some people may prefer clicking once on say "Finished" tab than typing in the name of a project; perhaps they can't remember it exactly.

**Comment by jwbmartin** [comment]
So you are saying that we have a good number of users who will want to see a finished project, remember that it's finished but not remember the name of it, and won't be willing to look at the filters we have on the left-hand side?

**Comment by mschwamb** [comment]
Sounds like the finished tab could be a filter. 

If you're in the default view, you show all  projects instead of 'most recently launched'  but still order by the launch date if you're live and put the retired at the end sorted by launch date.

then add retired as a filter to the top left filter which would only show retired projects
then add a live/active projects filter to the top left filter which only shows live/active projects

then if you go into a subcategory like 'biology' could can show the live projects first and then show the retired 

Also for researchers it's good to know how many Zooniverse projects there were. Like currently no one knows that Solar Storm Watch and Whale.FM existed unless you go to the publications page.  I definitely checked around on the Zoniverse home page in early talks about Planet Hunters because I wanted to know what I was getting into and see what the Zooniverse had produced previously and check those sites out.
