### ISSUE TITLE
Single Choice Tasks Default to "Done"

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3120]
## Expected behavior

If a next task is defined on the workflow, the "next" button should be available instead of "done" on task load.
## Current behavior

_Please include any error messages from the browser console and/or screenshots_
Upon first loading a project (with a next task) the green "next" button defaults to "done" when an answer hasn't been selected and a single choice question task is being used.
<img width="531" alt="screen shot 2016-10-11 at 7 53 56 pm" src="https://cloud.githubusercontent.com/assets/14099077/19293746/8955ee32-8fec-11e6-8e4a-7f3821ddb5e9.png">
## Steps to replicate

Create  workflow.
Choose a single choice task with a next task defined (not "end of classification").
When that single choice task loads, on the classifier, "done" is the default.
## Additional information
- **Operating system:**
- **Browser:**
  Chrome

**Comment by beckyrother** [comment]
If the underlying issue here is the worry that users will be influenced by the knowledge that there is a second question following one of these answers but not the other, both answers need to say "Next". 

Clicking Next should go to: 1, the next question, or 2, a [confirmation screen](https://invis.io/QUCCD1P8J#/233176332_05-Confirm). 

@srallen @trouille @wgranger Does this solve the issue?

**Comment by srallen** [comment]
I think the underlying issue is more that radio button tasks are not required when 99% (if not 100%) of the time they probably should be. I was also speculating that there may be a potential to introduce bias if it's revealed that there may be a branching decision tree, but I wouldn't 100% take my word for it (this is why we need an archive of past knowledge gained since I can't remember past conversations). Also, is the idea you're proposing is a pre-submission confirmation screen of the classification? I vaguely remember that being also a potential issue with introducing doubt with the volunteer, even though some volunteers ask for it.

**Comment by eatyourgreens** [comment]
I'm not sure if this is the same problem being discussed here, but Penguin Watch had a problem where people were accidentally clicking Next without selecting an answer to the first Yes/No question. In that case, clicking Next would submit an empty classification and you wouldn't be able to correct your mistake.

**Comment by beckyrother** [comment]
The confirmation screen appears in some projects but not others. This seems like a good case for some interviews or a survey – like Jim said, a confirmation screen would help in cases like that where they accidentally clicked next.

**Comment by beckyrother** [comment]
Agree that the radio buttons should be required.

**Comment by srallen** [comment]
If the radio button is always required, then the task buttons are disabled until a selection is made, so accidental submission should no longer be an issue.

Separately, I just want to clarify in case it isn't clear. Some projects have classification summaries which are shown post-submission of the classification. None of the projects allow you to go back after submission. We've never done a pre-submission confirmation screen for any of the projects and like I said, I think there is a reason for that, but I can't recall exactly what that is. Maybe @eatyourgreens would know.

**Comment by beckyrother** [comment]
Got it, I wasn't sure when the actual submission happened. Made that screen because I saw that screen – don't want to change any workflows, just updating style. 

So let's make the radio buttons required, and if an issue arises we'll address it then; I can't think of a reason that a radio button wouldn't be required.
