### ISSUE TITLE
How should the project completeness be calculated? section too much text and unclear if it applies to the project or the workflow. Maybe move it out of the workflow and onto another project builder page. 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3190]
There's a huge amount of text that basically keeps you from seeing the bottom buttons (the delete visualize, and test this workflow). It's a huge amount of text and it's kind of confusing to have it there because it says it is for the project  but is sitting in each workflow. 

Perhaps there should be a stats page in the project builder that can have settings rather than having this tacked onto the workflow pages or this should be on the visibility page? I think the visibility page would be better and then the amount of text is okay. 

To me it's unclear if this check box applies to the workflow or the entire project. Also for a new project builder how this impacts the workflow is unclear so I think it would be better to not have this in where you're actually constructing the workflow.

**Comment by CKrawczyk** [comment]
This is a per-workflow setting, that is why it is sitting in the workflow editor (I will change the name of the section to reflect this).  I don't think this should be a project setting since each workflow can have different retirement rules, and a project builder might want the stats for each workflow to be reported differently.

I could move the section lower down the page if you think it is confusing where it is, but seeing as the page already has enough content that a user has to scroll to get to those buttons anyways I don't see this as a big issue.  That being said, I do like the idea of putting this option on the visibility page.

**Comment by mschwamb** [comment]
Yeah it wasn't clear from the text that is was per workflow. I think the visability page would be better and have check boxes like the active workflows because currently I have to make my workflow inactive to change this setting.  Where it is now, it's the only setting that has no direct impact on the workflow classification interface design/behavior so I think it will be confusing to new project builders.
