### ISSUE TITLE
CSS bug on front bage

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Panoptes-Front-End#328]
Top level of projects visible (Chrome  42.0.2311.135) 

![screen shot 2015-05-14 at 11 45 50](https://cloud.githubusercontent.com/assets/423607/7639264/6d6f53d8-fa2f-11e4-84bb-5b4caf0a8225.png)

**Comment by srallen** [comment]
@chrislintott, this is actually intentional and a work in progress design. The idea was to give site visitors an indication that there is more content to scroll down to. The project cards 'snap' into place once you reach the point there are supposed to be on the page. I'm working with @heathv to iterate on the idea. Suggestions are welcome.

**Comment by brian-c** [comment]
I suggest setting the height of the hero are to something like `90vh` and allowing the featured projects area to peek up on its own.

**Comment by chrislintott** [comment]
I thought it might be - making sure they don’t overlap with the ‘Get Started’ button (maybe just by moving it up) will help.

**Comment by chrissnyder** [comment]
Outdated.
