### ISSUE TITLE
notify project owner/collaborators(?) when workflow completes

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#3443]
## Expected behavior
when workflow reaches 100% completeness - project's owner/collaborators are notified

related, but possibly should be it's own issue - give project editors option of once workflow is 100% complete automatically Hide on Stats Page

**Comment by srallen** [comment]
First request is back end either via Sugar for a notification or Panoptes for an email. Second one should be doable now on front end.

**Comment by mschwamb** [comment]
related to #1703 - can you have it notify specific collaborators on the project? Not always the project owner is the one doing the data processing. Currently all notifications go to the project owner.

**Comment by mschwamb** [comment]
this would be really useful to have at least the project owner get an email. I just hit this case and it's only because I check every few  days that I know.

**Comment by mschwamb** [comment]
I'm not sure what this state label is,  but this would be really useful.

**Comment by marten** [comment]
There is no way PFE will be able to do this. This should be a Panoptes issue, so I'm going to close this now.

@mschwamb The stale label (and bot) simply cleans up old issues. If an issue hasn't been worked or even commented on for 4 months, the usefulness of keeping it around as an open issue in Github is really really low. We're not saying that these issues aren't useful or important. They're probably all great ideas, but we have more great ideas than time. We're just saying that if nobody has managed to do them in 4 months, we're not likely to come back to it. Sometimes we do, but it won't be because it was somewhere in a list of 300 open issues, so there's no use in keeping it open here.
