### ISSUE TITLE
Could the subject_set name be shown somewhere/somehow?

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/Panoptes-Front-End#358]
This can be either a good or bad idea, because one should not tell the Citizen too much about the data set to avoid bias, but in testing I would find it really useful to be able to check from which subject set the current tile has been taken.

**Comment by mschwamb** [comment]
I don't think you want to give thst information to volunteers classifying but maybe in a beta or test mode?

**Comment by michaelaye** [comment]
On the other hand, the name of the subject set could be rendered meaningless to the citizen (some ID), but something we can look up using a table.

**Comment by vrooje** [comment]
I found this useful recently, but did it with a bulk rename of images so that each image name in a subject set had a code specific to that subject set. Not meaningful unless you know to look for it (though users could reverse engineer it), and easy to do.

Perhaps useful as a stopgap before an actual if (user.collaborator==True) {subject_set.show()} type code is implemented.

**Comment by michaelaye** [comment]
That's an excellent piece of pseudocode there! It shows so efficiently and coherently what my issue title fails so miserably at. ;)

**Comment by mschwamb** [comment]
@srallen  This can probably be closed. There is now the ability for metadata to show on talk a project owner can add a field in the metadata csv to label the subjects that won't show in the classification interface but only show on Talk so I think there's a solution in place.

**Comment by mschwamb** [comment]
closing since this can be down with the metadata options in the csv file

**Comment by mschwamb** [comment]
and I had suggested that this ticket be put in. The current features already implemented satisfy this feature.
