### ISSUE TITLE
Add ability to configure frequency of mini-course prompt

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#3611]
## Expected behavior
Add ability to configure frequency of mini-course prompt in mini-course editor.

## Current behavior
Mini-course is prompted every 5 classifications, as it has been hard coded to.

**Comment by lcjohnso** [comment]
Reopening this issue as there's been some renewed interest in minicourse use, and would benefit from this added config option.

Suggestions:
- Keep default as 5 unless config option says otherwise.  Currently configured here (see #2651): https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/index.cjsx#L26
- Need to add configuration on Project Builder workflow config page
- Perhaps store `minicourse_prompt_frequency` (or similar) config param in workflow configuration?

cc @srallen

**Comment by camallen** [comment]
We are looking at combining another use case where we want a message shown at set classification count intervals, e.g 
> As a project owner I want to present my volunteers with a congratulations message when they hit the target of 10, 25 and 50 classifications on my project.

**Comment by eatyourgreens** [comment]
One option would be a comma-delimited list of values in the project builder, saved as an array. Then the logic for showing a message is either every N classifications for a single integer, or when the current count is in the array for an array.

**Comment by srallen** [comment]
We could certainly use the workflow configuration object, but I'm thinking a config object would be a better fit on the tutorial resource. It'd be a small migration for the database on Panoptes.

**Comment by wgranger** [comment]
Configuration blobs should now be available on tutorial resources, so we can start moving on this in the frontend.

**Comment by camallen** [comment]
ON staging only until we deploy to production next week (17th August 2020).

**Comment by wgranger** [comment]
Another question before building this out. I'm assuming a project owner will set the `minicourse_prompt_frequency` tag on the project builder, so there will need to be some sort of editing option there.
