### ISSUE TITLE
Zooniverse logo looks weird in some browsers 

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#365]
Might be solved by making the whole word an image, rather than having the logo in the middle of text?

![zoo-home1](https://cloud.githubusercontent.com/assets/5321335/7723882/330ed632-fee4-11e4-9a68-a66728bf0483.jpg)

**Comment by astopy** [comment]
Having the whole word be an image would also be better for accessibility, so we can set alt text on the whole thing.

**Comment by srallen** [comment]
I initially had it up as an image and recently changed it to be letters + svg since it would be easier to style if the background changes regularly as @heathv mentioned in #205. It's also in the footer as a different color, so easier to style there too. However, if the vertical-align prop isn't consistent between browsers and the accessibility is a concern, I'll switch it to a set of images.

**Comment by brian-c** [comment]
I'd keep the whole thing as an inline SVG component with the fill set to `currentColor` so we can use it anywhere.

**Comment by srallen** [comment]
:+1: I'll have a PR up shortly.
