### ISSUE TITLE
URL can interfere with subject name in manifest

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#3752]
## Expected behavior
subject name/id will be recognized and not tripped up by URL in another manifest column

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Certain URL formats seem to trip up the recognition of the subject ID. To be clear the subject ID and the URL are in separate columns in the manifest. Location of columns does not seem to change the issue.

My suspicion is that the presence of ".jpg" anywhere in the manifest is the issue, but it is not clear why the URL is selected over the image name column.

An example that does not work as expected:
Row 1 of manifest: 
Column Name = ImageName, Value = 58f7720800cf79585c8b4a77.jpg
Column Name = imageURL, Value = http://sweetgum.nybg.org/images3/2137/310/02614976.jpg

An example the does work as expected:
Row 1 of manifest: 
Column Name = ImageName, Value = 58090ec700cf790d548b63dc.jpg
Column Name = imageURL, Value = http://bisque.iplantcollaborative.org/image_service/image/00-wxWr8HydxeaBuVJzmMjcCU?resize=4000&format=jpeg

Here is a screen, note that the name in the URL seems to have preference over the name in the image name column. 
![urlnamemismatchexample](https://cloud.githubusercontent.com/assets/2152565/25537105/662367a0-2bfa-11e7-8a39-39d95ecb307b.jpg)

## Steps to replicate
I can supply manifests and images/subjects of both types for testing

## Additional information

- **Operating system:**
OS X 10.11.6 (15G1421)

- **Browser:**
FireFox 52.0.2 (64-bit)

**Comment by srallen** [comment]
We identify subject file names for uploading by identifying the allowed extension type using a regex: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/subject-set.cjsx#L323

Since a subject can have multiple media sources, then in your example, both `imageName` and `imageURL` are identified as sources for the subject. 

In your second example, the URL isn't being found as a subject source because a valid extension is not found.

The UI interface in the lab also hasn't been built to handle subjects that are only using externally hosted media. Basically what's happening is that the URL is identified as a file to upload, but it fails because those files are missing, thus the error. 

It looks like it is your intention to use an externally hosted media source, so I would suggest using our python client instead to create subjects: https://github.com/zooniverse/panoptes-python-client

Or using our CLI tool: https://github.com/zooniverse/panoptes-cli

**Comment by denslowm** [comment]
Just to be clear 100% clear, we want to use the URL as an external resource. For example, when a volunteer clicks "i" they are presented with various resources one of which is a link the original image. As you noted, sometimes those URLs end in an image file extension. 

 I am happy to use the the Python client or the CLI. Are you saying that I could include the URL in the same format without issue using these tools instead?

**Comment by srallen** [comment]
I misunderstood since I thought you wanted to use the external URL as the subject media source. We don't have a convention for the manifest CSVs and we've written the UI to just look for strings ending in the allowed extension types. Using the python client to write a script to precisely set the subject location and its metadata sounds like what you need to do. There is a basic example script for subject set creation and subject upload in the python client readme.

**Comment by denslowm** [comment]
OK, I'll give that a try. I've leave it up to you if we want to leave this open or not in the meantime.

**Comment by srallen** [comment]
Ok, sounds good. If you find that writing a python script works for you, it's best for our API if you batch subject creation and linking to subject sets into 500-1000 batches at a time and keep track in a log or database what you've done.

**Comment by denslowm** [comment]
Do you mean 500-1000 per upload or per new subject set? I ask because we frequently have subjects that are larger than this.

**Comment by camallen** [comment]
The python client will do this for you if you provide it a list of subjects to SubjectSet.add function [here](https://github.com/zooniverse/panoptes-python-client/blob/9abadd1953ccca4c472ccf8294a45f9eef550e2e/panoptes_client/subject_set.py#L31). 

There is also added some documentation about adding externally hosted media resources https://github.com/zooniverse/panoptes-python-client/wiki/Upload-externally-hosted-media-resources

**Comment by srallen** [comment]
@denslowm I mean to batch the uploads in 500-1000 subjects at a time. If you have more than that, just offset where you started last time and do the next 500-1000. And you can write your script to use a preexisting subject set. You don't have to make a new one each time.

**Comment by camallen** [comment]
Long term we should add this to the panoptes cli tool but here is an example script for just what @srallen is referring too, https://github.com/zooniverse/panoptes-python-client/wiki/Batch-upload-external-subjects-from-a-CSV-manifest-with-error-handling

**Comment by denslowm** [comment]
Great, this is very helpful. I'll give this a try very soon. Thanks.
