### ISSUE TITLE
Internet explorer bug: video playback options below the fold

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3765]
## Expected behavior

video playback speed buttons should be above the fold for all browsers. They are except for Internet Explorer. 

Here is an image of what it looks like in Chrome, which is correct. 

![screen shot 2017-05-05 at 8 43 41 pm](https://cloud.githubusercontent.com/assets/4975655/25768937/9c259dc6-31d3-11e7-9eac-2f5828f89fa2.png)

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

The playback speed buttons for video projects on Internet Explorer are below the fold. 
![screen shot 2017-05-05 at 8 39 53 pm](https://cloud.githubusercontent.com/assets/4975655/25768912/68e2a3dc-31d3-11e7-8eeb-64d99995847e.png)

This came to attention of the research lead because of comments in Talk where users didn't realize there were playback speed options. Figured out it was browser differences. 

## Additional information

- **Operating system:**
Mac, but using an internet explorer emulator in Chrome

- **Browser:**
Internet Explorer 11. The IE emulator just let me test in 11. I haven't tested in older versions of IE.

**Comment by srallen** [comment]
Just FYI, we don't support previous versions of IE.

**Comment by shaunanoordin** [comment]
I saw the IE signal. D:

Issue: in IE11, the _video playback speed buttons_ appear 'below the fold'. (i.e. below the first screen the user sees, meaning user needs to scroll down to realise there are extra buttons to press)

Analysis: This is *not* a browser-specific issue, but is instead related to the *dimensions* of any given browser window. Due to the CSS layout, if a browser window is _too "long/wide"_ (i.e. the ratio of width to height is too large) then any element that's "too low" on the page can appear below the fold.

![screen shot 2017-05-09 at 14 59 05](https://cloud.githubusercontent.com/assets/13952701/25858962/0c1cda50-34d5-11e7-9243-ef2eaf59a519.png)
_Win7+IE11 with window dimensions of approximately 921x649_

![screen shot 2017-05-09 at 14 59 32](https://cloud.githubusercontent.com/assets/13952701/25859051/40db24ae-34d5-11e7-8e3c-5488614f4023.png)
_Win7+IE11, but this time the window has been made wider to approximately 1023x646_

![screen shot 2017-05-09 at 15 00 23](https://cloud.githubusercontent.com/assets/13952701/25859083/5498c2b2-34d5-11e7-8d81-f9baa5431cd4.png)
_OSX+Chrome58 at 1059x597_

![screen shot 2017-05-09 at 15 00 43](https://cloud.githubusercontent.com/assets/13952701/25859104/6476acf8-34d5-11e7-894a-4ddf89c704c0.png)
_OSX+Chrome 58 at 1133x595, showing that the issue is not browser-specific_

Status: This is not an IE bug, but the layout issue is real. I have no recommendations other than re-examining the logic of layout CSS.

**Comment by srallen** [comment]
@shaunanoordin thanks for taking a look. I would have guessed this was depending on screen resolution and size rather than browser. 

This is a layout/design question. Pinging @beckyrother for consideration with the video player in the classifier. However, we need to keep in mind regardless of design that we won't be able to guarantee everything will always be in view for everyone since this is a variable we can't control for. People just need to remember to scroll, especially in IE/Edge where the native scroll bar behavior is to be always visible so that is a good indicator if there is more content.

**Comment by beckyrother** [comment]
Thanks @srallen and @shaunanoordin. You're right, we can't control for every browser height. I'm hoping the new classify iteration will prevent this from happening for the most part – my goal is to keep the image at a consistent height based on the average viewport height (643px) based on user data from Marten. Honestly beyond that there's not a lot we can do (open to suggestions if there are things I'm not thinking of).

**Comment by srallen** [comment]
@beckyrother I was thinking that the video subject viewer could have a sidebar of custom controls if they're enabled like image subjects have if pan and zoom is enabled. The playback speed controls could fit there? I'm not sure about the play button and the scrubber. I think it's standard to have those at the bottom of the video.

**Comment by eatyourgreens** [comment]
We could play around with using the browsers play and scrubber controls too. I can't remember why I added custom controls for play/pause and scrubbing. Maybe the browser's controls are unreliable?

Also, changing playback speed is unsupported on Android, so those radio buttons do nothing there.

**Comment by srallen** [comment]
@eatyourgreens My guess is that the subject viewer's SVG layer was interfering with the controls.

**Comment by eatyourgreens** [comment]
I think that's it, but that code is all gone now, so we can experiment with getting rid of those custom controls.

**Comment by beckyrother** [comment]
I wouldn't recommend moving the video controls away from the bottom – that's pretty standard. @eatyourgreens do you mean removing the playback speed controls altogether?

**Comment by srallen** [comment]
@beckyrother he means use the native HTML5 video player controls instead of the custom ones we built. We disabled the native controls and built a custom play button and scrubber below the video  because the subject viewer had a SVG layer on top rendering over the video preventing the button events for the controls to fire correctly. We've been working on making so the SVG layer only render for image subjects and not for other types. I'm not sure if the native video controls have controls for playback speed, though. 

@eatyourgreens do you know if there are controls for play back speed we can enable if we switch back to the native controls?

**Comment by eatyourgreens** [comment]
There aren't any native controls for playback speed, as far as I know. Support for that varies and we'll have to use our own custom controls to change speed.

**Comment by eatyourgreens** [comment]
@beckyrother @srallen I've staged a branch that uses `<video controls=true>` at https://native-video.pfe-preview.zooniverse.org/

I can open a PR for that change if you'd prefer to discuss it there. I notice that Chrome's video controls include a download button for the video file, which people might not like.

**Comment by srallen** [comment]
I think the native controls look a lot better and will be less overhead for us for the video subject viewer. I'm for it 👍 

As of Chrome 58, they added in a non-spec `controlsList` property to control whether or not that download button shows up.
https://bugs.chromium.org/p/chromium/issues/detail?id=675596
https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist

I was gonna wait until Chrome 59 to remove the CSS hack workaround I put in place for Chimp&See to hide that button so hopefully most folks are on either version 58 or 59 by that point. I think if we implement the native controls on PFE, we'll need to include the CSS hack to hide the download button since most project owners probably wouldn't like that even though we don't really stop anyone from downloading videos. I can understand the opinion that having the button there looks like we're promoting downloads.

**Comment by eatyourgreens** [comment]
Cool. I've opened #3781 with that branch.

Only thing I've noticed is that scrubbing the video with the keyboard is more tricky with the native controls than it was using a HTML slider.

**Comment by beckyrother** [comment]
Commented on #3781 but i'm all for using native controls. thanks for taking a look at this!
