### ISSUE TITLE
No pagination for workflows

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#3807]
## Expected behavior

According to #3651 there should be pagination on the new workflows page.

## Current behavior

<img width="994" alt="screen shot 2017-05-17 at 12 05 12" src="https://cloud.githubusercontent.com/assets/428423/26151089/236b5248-3af9-11e7-806b-bffcb51816de.png">

[Reported on talk](https://www.zooniverse.org/talk/18/335228)

## Additional information

- **Operating system:** Safari 10.1
- **Browser:** macOS 10.12.4

**Comment by srallen** [comment]
I suggested putting that off from the initial refactor because we need to figure out how to make the drag reordering work with the pagination: https://github.com/zooniverse/Panoptes-Front-End/pull/3651#discussion_r109955592

I'm thinking defaulting to the paginated view and have a button to toggle a view to display all the workflows with the drag reorder functionality?

**Comment by srallen** [comment]
BTW, I think that talk report is referring to pagination of the subject sets on the workflow editor page, which we still need to do too. Another idea is to instead have a search field where you type in the name of the subject set you want to link and a button to add as well as list only the linked subject sets rather than paginating all the subject sets and having checkbox toggles.

**Comment by camallen** [comment]
@srallen +1 to a search field, that would be super useful!

If we want whole name matches then passing the `?display_name=set display name` should work out of the box as per [here](https://github.com/zooniverse/Panoptes/blob/4827d8d55c45c88be3b2cb803057a8327188aad0/app/serializers/subject_set_serializer.rb#L11). 

Adding fuzzy / full text searching will require a little work but should be fairly easy to add.

**Comment by eatyourgreens** [comment]
Text matching also works for [subject set metadata fields](https://github.com/zooniverse/diagnosislondon/blob/master/app/choose-subject-set.cjsx#L37).

**Comment by srallen** [comment]
Noting that the workflows page now has a toggle to change the view between a paginated list and list for reordering since #3908. However, I'll leave open because the subject set pagination on the specific workflow page is still not fix which I think was what the original comment on Talk was asking for.

**Comment by srallen** [comment]
Closing to open a specific issue about the pagination of subject sets on the workflow edit page.
