### ISSUE TITLE
Move the classifier summary state into Redux

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3825]
I managed to [break the skip summary feature](https://github.com/zooniverse/Panoptes-Front-End/pull/3824) by messing up a boolean in the `task-nav` component. This has a busload of conditionals in there that could be simplified by passing everything into Redux (workflow, mostly, maybe feedback too) and treating it as a state machine which returns the components that ought to be shown.

ref #3824

**Comment by eatyourgreens** [comment]
`TaskNav` currently handles all the logic around keeping track of the current task in a workflow, because of React's insistence on keeping event handlers next to the elements that trigger them. This is a pain when components higher up the tree want to use the current task.

:+1: from me to moving all that out into a store.
