### ISSUE TITLE
Shortcut task does not clear survey annotations

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#3832]
## Expected behavior
Selecting "nothing here" should clear any existing identifications for a survey task.

## Current behavior
"Nothing here", on Snapshot Wisconsin, can be selected in addition to any existing identifications, and is submitted alongside them with the classification.

![Survey task showing both Deer and No Animals Present selected](https://cloud.githubusercontent.com/assets/59547/26587248/b8924156-4549-11e7-9352-e44593af86aa.png)

![Classification summary showing that the badly formed classification is submitted to Panoptes](https://cloud.githubusercontent.com/assets/59547/26587299/d34c80e2-4549-11e7-9397-85ee0644a47c.png)

## Steps to replicate
https://www.zooniverse.org/projects/zooniverse/snapshot-wisconsin/classify
Select "No animals present" in addition to any identified species. It doesn't seem to matter if you select the shortcut before or after identifying animals.

**Comment by wgranger** [comment]
This was a conversation we had when the shortcut button was created. Originally, the button cleared all annotations for a task, but we changed the task to persist annotations and record both. There should probably be a toggle somewhere in the project builder that allows a the task to persist or clear annotations when the button is toggled.

**Comment by eatyourgreens** [comment]
Turns out this how it supposed to work :man_shrugging:

**Comment by simoneduca** [comment]
I think [volunteers are confused by how this is supposed to work](https://www.zooniverse.org/talk/17/588612) and so I'm reopening the issue. We can't just tell them "you're wrong, that's how it's supposed to work!".
From the Talk post above:
>Normally, if marking ’No animals present’ , it disables automatically possible animal identifications chosen. And vice versa. Now though that does not happen. Meaning that system allows both into same classification

**Comment by srallen** [comment]
I don't think there's anything we can do about it because the shortcut task label can be whatever the project team sets it to be. On some projects it might be 'Nothing here' which is confusing as to why it doesn't clear annotations out, but on others it might be a additive or one that isn't necessarily either/or annotation like 'human present'. If the shortcut had remained its original purpose to just be a 'nothing here' button, then it would have worked in this way. I think in the future, the survey task should support a specific 'nothing here' type checkbox and the shortcut task should be deprecated because it functionally is basically just a multiple choice task in combo with something else.

**Comment by eatyourgreens** [comment]
Interesting how actual usage of the shortcut has differed from the initial spec: a single answer task that skips you to the end of the classification.
