### ISSUE TITLE
Display workflow ID in URL

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#3855]
It would mean Google Analytics could track traffic to a specific workflow and @aliburchard would be super delighted.

**Comment by eatyourgreens** [comment]
Notes from Nature links to URLs by ID. I think there's a setting you can enable on the admin pages.

**Comment by srallen** [comment]
The workflow query param is how workflow selection used to work for projects. I removed it because of Gravity Spy's workflow promotion. Undoubtably users would figure out which workflow id matched with higher levels and just promote themselves and essentially break the promotion algorithm. NfN is the only project that really needed it to allow volunteers to use workflow selection this way since they have a separate site for selection. Also, if you are a project owner, collab, or admin with that mode on, you can select workflows this way. I'd be really wary of enabling it for other projects because of unintended consequences: one example I can think of is leaking that an a/b split with two different workflows is happening for instance (which also Gravity Spy did).

Is there another way that it can be tracked by google without putting it in the URL?

**Comment by rogerhutchings** [comment]
Yeah, you can trigger a custom Google Analytics event with the workflow ID: https://developers.google.com/analytics/devguides/collection/analyticsjs/events

**Comment by rogerhutchings** [comment]
Maybe using something like https://github.com/react-ga/react-ga?

@aliburchard what exactly do you want to track?
