### ISSUE TITLE
Can't delete subject sets in admin mode

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#3929]
## Expected behavior

Clicking delete should send a delete request with `admin=true`.

## Current behavior

The request doesn't include the `admin=true` param, so the API returns a 404.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by srallen** [comment]
If I'm remembering correctly, on slack we determined that this was in combination an issue in the js client and with Panoptes? I'm gonna close this since it's not an issue in PFE. The JS client is undergoing a rewrite, so as soon as that's available we can check if there are still any further issues with the API that need addressing.
