### ISSUE TITLE
Steelpan-vibrations - numbers of fringes in antinodes aren't visible

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#3996]
## Expected behavior
In the classification, second step asks how many fringes (bright or gray circles) are enclosed in the marked antinode region and the count should be set on a scale. The number shown on the scale should be displayed in a box but they aren't.

## Current behavior
The number is not visible as seen on this screenshot:
![ysh_screenshot_2017-08-23_19-07-25](https://user-images.githubusercontent.com/7211888/29628923-565fcd06-8837-11e7-9042-f0216957e4aa.png)
Hovering over the box for number displays small arrows, possibly they obscure the numbers when the cursor is elsewhere as the left edge of the figures is visible.

## Additional information

- **Operating system:** Linux x86_64
- **Browser:** Chromium 58

**Comment by vrooje** [comment]
I'm getting this too, in OS X / Chrome 59.0.3071.115

![screen shot 2017-08-24 at 10 29 24 am](https://user-images.githubusercontent.com/2357126/29679964-f80d01d4-88b7-11e7-8482-e0e551d28a6d.jpg)

Scrolling through, I can tell the text isn't completely absent - it's just being obscured by something, as though the box is too small or its margins are too big. I can sort of guess at what number is being displayed underneath everything that's obscuring it because I can just barely see the left side of it.

Also, the position of the mark on the scale doesn't align with "1" when the number selected is 1, nor with "11" when the number selected is 11.
