### ISSUE TITLE
Point tool feedback doesn't display in demo mode

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4024]
## Expected behavior
The point tool drawing task should show feedback at the end of a classification, if point tool feedback `[type, x, y, tol, successMessage, failuremessage]`is defined for a set of expected points `[feedback_1…feedback_N]` in the subject metadata.

## Current behavior
![Screenshot showing a mark in the correct place, plus subject metadata. No feedback is displayed.](https://user-images.githubusercontent.com/59547/29625567-fd1cc202-8823-11e7-9837-c545bf84e91c.png)
Here `feedback_1` is defined for a point at (167, 52) with a radius of 80px. `feedback_2` is also defined, but the point values have been left empty. A point has been placed at (152, 156) but the success message for `feedback_1` isn't triggered.

## Steps to replicate
I _think_ this is caused by turning on demo mode when testing.

## Additional information

- OSX 10.11
- Chrome

**Comment by simoneduca** [comment]
Are those empty values supposed to be filled in by the project owner?

**Comment by eatyourgreens** [comment]
Presumably, but why isn't it showing the success message for `feedback_1`?

**Comment by simoneduca** [comment]
No idea yet.

**Comment by aprajita** [comment]
@eatyourgreens - is this using the original workflow?
leaving feedback_2 empty gave rise to the default messages defined in the project builder (as described in #3858), so i am not sure this is the cause of the lack of feedback in this instance. I had the same problem as you and simone that's why I made a duplicate workflow with the same subject set and that didn't have the same problem with missing feedback. I think something just got messed up in that particular workflow somehow.

**Comment by eatyourgreens** [comment]
@aprajita I think this is a bug that you accidentally triggered somehow with the original workflow. The new workflow doesn't have the bug, but if you can create a workflow that doesn't show feedback, then somebody else will also do that in the future.

**Comment by eatyourgreens** [comment]
NB, in my screenshot above, I don't even see any default feedback for the classification.

**Comment by aprajita** [comment]
hi again @eatyourgreens, thanks.

Yes I get exactly the same as you on that workflow, no default no feedback for anything.

As i mentioned in #3858, I didn't make any changes to the workflow between it working and not working. It used to show exactly the same as in the new workflow with Feedback_2 defined (i.e. the conflicting feedback messages etc - that's what prompted me to start that issue).  And then this original workflow stopped showing feedback at all without my intervention. So not sure what the cause is but I don't think it's feedback_2 being blank as wouldn't the same would be seen in the new workflow with the same subject set?

Just to summarise:
this is the workflow with issues
https://www.zooniverse.org/lab/1434/workflows/4257
**Note this also has a conflict with hide classification summaries - these are shown even though this option is ticked and summaries should be hidden**

this is the duplicated workflow
https://www.zooniverse.org/lab/1434/workflows/4817
where it works with either the same subject set as 4257 (12717) or the slightly modified one where the feedback_2 metadata has been cleared apart from one subject (14526)

i checked the setup for both workflows and they are the same in the project builder. 

I've also now selected the original dataset with feedback_2_type defined but empty in both workflows and they behave differently. so if it was feedback_2 empty triggering this, then the two workflows would behave the same I think.

for the original workflow
![image](https://user-images.githubusercontent.com/1917970/30110763-1ce2aa5e-9303-11e7-89de-06a2441fc1e2.png)

for the duplicated workflow
![image](https://user-images.githubusercontent.com/1917970/30110750-0dccee1c-9303-11e7-8676-be989532538e.png)

**Comment by eatyourgreens** [comment]
The summary showing, when it should be hidden, might be related to #3825

**Comment by eatyourgreens** [comment]
Hi @aprajita thanks for the links. I'm not getting any success message feedback on workflow 4817 either, and one subject has just shown the failure message, even though the marked point is inside the circle.

![Screenshot showing Space Warps feedback. The marked point is inside the feedback circle but the message shown is a big red FAIL.](https://user-images.githubusercontent.com/59547/30112844-a75a6c88-930a-11e7-9dac-a5d0668496bd.png)

**Comment by aprajita** [comment]
ah ok...i am seeing both on this same subject - how odd!
![image](https://user-images.githubusercontent.com/1917970/30112966-04d7b6f4-930b-11e7-9b9f-56a00fb7f158.png)

**Comment by eatyourgreens** [comment]
Maybe the bug is that demo mode turns off the success messages? It shouldn't do that.

**Comment by aprajita** [comment]
hi @eatyourgreens
great that you discovered it was demo mode, this solves it for workflow 4817 
but still nothing for either of us on workflow=4257, or do you see feedback there now too?
thanks, a.
