### ISSUE TITLE
Experimental feat "Allow workflow query"

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#4042]
## Expected behavior
If experimental feature "Allow workflow query" is checked, anyone should be able to access workflows via url with query params.

## Current behavior
<img width="290" alt="screen shot 2017-09-14 at 10 49 13" src="https://user-images.githubusercontent.com/8989606/30424344-971775a8-993d-11e7-95a1-ef1b8a25d5e3.png">
Can't access https://www.zooniverse.org/projects/vrooje/planetary-response-network-and-rescue-global-caribbean-storms-2017/classify?reload=0&workflow=4969 unless admin mode is on or I am a collaborator on the project.

- **Operating system:** OS Sierra 10.12.6
- **Browser:** Chrome

**Comment by simoneduca** [comment]
Question: why do we need to check project preferences here https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/index.cjsx#L188? This returns `true` for me for the above project, but I don't think it should because I haven't selected that workflow, I've only tried to access the url directly. It might just be me not understanding how this works, but it'd be great to clarify it a little given how hard to read that chain of if blocks is.

**Comment by eatyourgreens** [comment]
I don't think the feature itself is broken. Notes from Nature's [workflow links](https://www.notesfromnature.org/active-expeditions/Herbarium) all work.

Is the workflow in question public, or only available to project owner and collaborators? That would explain why it works in admin mode.

**Comment by eatyourgreens** [comment]
@simoneduca that's an `unless` so it will return true if your selected workflow, stored in your project preferences from your last visit, is not `selectedWorkflowID`, which is correct for your situation?

**Comment by eatyourgreens** [comment]
The javascript console has this message `No workflow 4969 for project 5187` so the link doesn't work because that workflow isn't public.

**Comment by camallen** [comment]
All workflows are public if a project is public. The UI is injecting the `active=true` state flag here https://github.com/zooniverse/Panoptes-Front-End/blob/289fa67b2e3f0c76d8328c444f8b6ce427c488d1/app/pages/project/index.cjsx#L181

Unless you have roles (which ones?) on the project. That means you can't just share a test workflow URL with people. i think there is a use case for sharing non-active workflow links (we had one this morning) with testers, small group of trusted volunteers, etc.

**Comment by eatyourgreens** [comment]
#3648 gives the background for checking user roles before setting `active=false`.

**Comment by srallen** [comment]
Ok, so I should have clarified yesterday that we only load active workflows except if you are admin, owner, or collaborator on the project even with the `allow workflow query` experimental flag. The current workflow loading behavior is:

1. Load a workflow by query param if param is present and the project has `Allow workflow query` enabled and the workflow is active. Notes from Nature uses this.
2. Load a workflow by query param from the project builder using the view workflow button if you are the owner or collaborator. This removes the `active: true` from the API call.
3. Load the workflow in the project's default configuration and if it is active
4. Load the workflow in the user's project preferences settings property and if it is active. This is how Gravity Spy pushes user workflow level promotion
5. Load the workflow in the user's project preferences preferences setting and if it is active. This is set when a user loads the workflow and supports the ability to go from talk and back to classify and ensures that the same workflow loads
6. Load a random active workflow linked to the project
7. On subsequent loads, if a workflow is made inactive, then we clear out that workflow from the user's project preference preferences or settings properties if they are stored there. In the project builder, workflows made inactive are cleared out of the default config if they were default (we need to fix this in the Admin UI). 

Originally all workflows loaded by query param regardless of activeness, since activeness came later as a concept. Here's a bit of history of how the above complicated set of states and conditions for loading a workflow came about:

- In #2572, storing the workflow in the user project preferences was added to ensure that the same workflow is loaded when going between the homepage, talk, and the classifier
- In #2622, I added the default workflow for the project so that we could ensure that the beginning level workflow for Gravity Spy would be loaded first and for non-logged in users.
- In #2668, we added a conditional to check to make sure that the workflow is active before loading the workflow because we now had issues with inactive workflows being loaded as default or from user project preferences when the project owner doesn't want this happening.
- In #3003, I did major refactoring of how workflows are loaded including removing the ability to load workflows by query param (https://github.com/zooniverse/Panoptes-Front-End/pull/3003/files#diff-83addd0f5535ee9ffe878b365f61712bL121). This was because with loading by query param in place as it was, volunteers could potentially cheat the workflow level order on Gravity Spy and break their machine learning algorithm.
- I unknowingly broke Notes from Nature by removing loading by query param, so we added it back in #3029 with the gatekeeping of putting it behind the experimental feature flag.
- In #3648 we added back being able to load a workflow from the project builder using the query param the requiring the user to be an admin/owner/collaborator

Being able to send out a link to an inactive workflow for testing or for expert classifications does sound like a use case, but I'm hesitant to change the current behavior. Apparently the test workflow button was broken for about 6 months before anyone noticed and being able to load a workflow using query param by anyone regardless of activeness hasn't worked for a long time too and only noticed now.

If being able to load an inactive workflow for an active project is needed and PRN Is a good case of that, then I would suggest we add the tester role to the allowed roles that can load by query param in the conditional check. I'd be concerned about letting anyone be able to load an inactive workflow by query param even with the gatekeeping of the experimental flag since this could potentially have issues with clearing out workflows properly out of user project prefs in some cases when the project would want that to happen, but also wants loading by query param (i.e. Notes From Nature).

There's a lot of history here, so I think I'll take a moment to add a file to the how-to-zooniverse repo so that the history of these features are documented and I think it'd be a good idea for us to do that with the rest of the features in the experimental tool list.

**Comment by simoneduca** [comment]
Thanks for taking the time to do this Sarah.
