### ISSUE TITLE
Spectrogram support for audio files in the PFE subject uploader

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#4045]
## Expected behavior

The ability to associate a spectrogram with an audio file, so it plays like:

https://audio-subject.pfe-preview.zooniverse.org/projects/hughdickinson/testing-audio-subjects/classify

Below is a code snippet from Hugh. It may be that this is closed to non-admins and/or it's not the right approach. Yunpeng, the researcher interested in this functionality, will post here his experience. 

========

from panoptes_client import SubjectSet, Subject, Project, Panoptes
import glob
import os
import pandas as pd
import numpy as np
import re

Panoptes.connect(username='hughdickinson', password='****', endpoint='https://panoptes-staging.zooniverse.org', admin=True) # not sure if admin is mandatory
project = Project.find(id=1751)

subjectSet = SubjectSet()
subjectSet.links.project = project
subjectSet.display_name = 'Testing Combined Subjects'
subjectSet.save()
subjects = []
#for subjectPath in subjectPaths:
subjects.append(Subject())
subjects[-1].links.project = project
subjects[-1].add_location('/path/to/spectrogram/image/test.png')
subjects[-1].add_location({'audio/mp3':'https://panoptes-uploads.zooniverse.org/staging/subject_location/f6724922-5286-449e-89ce-44a11b079810.mpga'})
subjects[-1].save()

subjectSet.add(subjects)
print('Done')

========

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

New function request.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Spectrograms were added in #3878 but I think you have to manually edit the subject locations. See the discussion on that PR. Each subject needs a frame that points to URLs for an audio file and an image file. The project builder only generates one file URL per frame, I think.

**Comment by li-yp** [comment]
Thanks @trouille for providing the sample code! I tried to run the code but ended up with an error:

python2 zoo.py 
Traceback (most recent call last):
  File "zoo.py", line 10, in <module>
    project = Project.find(id=4846)
  File "/home/yp/anaconda2/lib/python2.7/site-packages/panoptes_client/project.py", line 29, in find
    return cls.where(id=id, slug=slug).next()
  File "/home/yp/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 478, in where
    return cls.paginated_results(*cls.http_get(_id, params=kwargs))
  File "/home/yp/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 445, in http_get
    headers
  File "/home/yp/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 191, in get
    endpoint=endpoint
  File "/home/yp/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 154, in json_request
    endpoint
  File "/home/yp/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 101, in http_request
    token = self.get_bearer_token()
  File "/home/yp/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 362, in get_bearer_token
    if not self.login():
  File "/home/yp/anaconda2/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 340, in login
    response.json().get('error', 'Login failed')
panoptes_client.panoptes.PanoptesAPIException: Invalid email or password.

4846 is my project id. And I have changed the username and password to mine. There is no place I see to input the email address. And my Panoptes CLI should have been set up properly as I can create subject set from it. What should I do now?

Thanks!

**Comment by camallen** [comment]
@li-yp Change the code from the staging api to the production one e.g.
```
# it defaults to the production api endpoint since ver 0.9 
# https://github.com/zooniverse/panoptes-python-client/blob/ecde5b0f011385da836fba6b2106efa637a40e55/CHANGELOG.md#09-2017-06-20)

Panoptes.connect(username='YOUR_USERNAME', password='YOUR_PASSWORD')
project = Project.find(id=4846)
```

**Comment by eatyourgreens** [comment]
Maybe we should move the python conversation to [zooniverse/panoptes-python-client](/zooniverse/panoptes-python-client).

This issue could be used to discuss how to add multiple media files to a single subject location via the project builder. It seems like it would be a useful feature to have in PFE.

**Comment by li-yp** [comment]
Thanks @camallen  The upload is working now after the change if I use local copies of the mp3 file and the png file. The newly created subject set only contains the png file.

Apparently I should use the link to the mp3 url of instead of a local location. But I don't know how to get the mp3 url like https://panoptes-uploads.zooniverse.org/staging/subject_location/f6724922-5286-449e-89ce-44a11b079810.mpga'

It would be great to know how to obtain the audio urls in batch as we may upload hundreads of mp3/spectrograms.

Thank you all so much for your help on this issue.

**Comment by eatyourgreens** [comment]
@li-yp I've opened zooniverse/panoptes-python-client#125 to ask if this can be done.

**Comment by li-yp** [comment]
Many thanks @eatyourgreens Is it possible to know the audio_url for just one single audio file, so that I can first experiment with creating some work flow with a single mp3 and spectrum png? Multiple subjects can be added later when the feature is added.

**Comment by eatyourgreens** [comment]
@li-yp Have you uploaded the audio files? If so, you should be able to see the URLs in the subject object that's returned from the Panoptes API.

It may look something like `subject.locations = [{'image/jpeg': image_URL}, {'audio/mpeg': audio_URL}]` where each file has been uploaded to a separate frame in the subject viewer.

For the audio player to work, both files need to be on the same location in the locations array
`subject.locations = [{'image/jpeg': image_URL, 'audio/mpeg': audio_URL}]` so that the subject viewer knows to render them in a single frame, rather than as a slideshow.

**Comment by li-yp** [comment]
@eatyourgreens I uploaded the audio files using the Project Builder with Firefox. Previously the upload was unsuccessful either with Chrome or the Panoptes API. The issue was discussed in https://github.com/zooniverse/Panoptes/issues/2458

Since they are uploaded using the browser. I don't see any returned URLs.

Now, they have been uploaded. What is the command to returen the URLs in the subject object with the API? I am sorry that I am still unfamiliar with the Panoptes API.

**Comment by eatyourgreens** [comment]
@li-yp Looking at the usage examples in the Readme file for [zooniverse/panoptes-python-client](/zooniverse/panoptes-python-client) I _think_ the code you'd use to list your subjects is something like:
```python
subject_set=SubjectSet.find(1234)
for subject in subject_set.subjects:
    print("%s," % (subject.locations))
```
where you would replace `1234` with the ID of your subject set.

**Comment by li-yp** [comment]
Thanks,  @eatyourgreens ! This prints the subject locations. However, it seems to print locations of every subject in every subject sets under that project. For me, I have multiple subject sets there because of the ongoing testing of features. It is hard for me to track which subject the printed locations are associated with.

Is there a way to specify which subject set I am printing the names of its subjects? I don't seem to find a solution from the Readme there.

**Comment by camallen** [comment]
@li-yp you can print the subject_set links as such
```
subject_set=SubjectSet.find(1234)
for subject in subject_set.subjects:
    print("%s," % (subject.locations))
    print("%s," % (subject.links.subject_sets)) # this is a list of all the sets a subject is a member off
```

**Comment by li-yp** [comment]
Thanks, @camallen  But subject.locations always outputs "[<SubjectSet 2>],", although I have multiple Subject Sets.

The number of iterations is also much more than the number of subjects in all the Subject Sets there. As an experiment, I deleted all but two Subject Sets. So, there are now only one Subject Set with 9 mp3 files, and the other Subject Set with 1 spectrogram png file. Still, when I execute the following code, the number of iterations is a few hundreds. And the subject locations all indicate png files. Do the commands below retrieve all subjects in the project even after they are deleted?

project = Project.find(id=4846)
subjectSet = SubjectSet()
subjectSet.links.project = project

for subject in subjectSet.subjects:
    print("%s," % (subject.locations))
    print("%s," % (subject.links.subject_sets)) # this is a list of all the sets a subject is a member of

**Comment by eatyourgreens** [comment]
@li-yp looking at [the code example I posted](#issuecomment-330616926) you need to use `SubjectSet.find(id)` to get your specific subject set, by ID number, before iterating it through its subjects.

**Comment by li-yp** [comment]
@eatyourgreens  Ahh, I was not careful in reading your sample code. It now works! I will experiment with associating the mp3 and the png files and create a workflow. Many thanks!

**Comment by eatyourgreens** [comment]
@li-yp 👍

**Comment by eatyourgreens** [comment]
@li-yp by the way, zooniverse/panoptes-python-client#125 has been updated to add this as a feature in release 1.1. With that release, you should be able to upload multiple files in a single call to `add_location`, so something like `subject.add_location(['/path/to/audio.mp3', '/path/to/image.png']) would upload both files as a linked pair for your subject.

**Comment by li-yp** [comment]
@eatyourgreens That feature would be great so that I can easily upload multiple pairs of audio/spectrogram. When will the release1.1 be available?

There are some problems after I created a workflow with the single mp3 and spectrogram that I uploaded and associated. In the "MULTI_IMAGE OPTIONS" of the workflow, I choose "Show separate framews as single row (side by side). What I get have the bottom part of the figure duplicated, which looks like the following:
![screenshot from 2017-09-20 18-35-42](https://user-images.githubusercontent.com/26939384/30658509-d16b8fd8-9e32-11e7-9294-1c8932a87e51.png)

Is there a way to correct this? I am also slightly confused by the options of "Single row (side by side)", "Grid (2col)" and "Grid (3col)". I don't see any differences when I choose either of them, but I am wondering whether the first one means "Single column"?

**Comment by li-yp** [comment]
@eatyourgreens  Another feature that would be extremely helpful is adding a verticle line sliding through the spectrogram when the audio plays. So, it plays like this: https://audio-with-image-subject.pfe-preview.zooniverse.org/projects/hughdickinson/testing-audio-subjects/classify

Is there an easy way to achieve that?

Cheers!

**Comment by eatyourgreens** [comment]
Hi @li-yp that feature is already present in the code.

**Comment by eatyourgreens** [comment]
Hi @li-yp sorry, I meant that our javascript (this github repo) already has code to track current position with a red line in the spectrogram image. It was added in #3878.

Uploading multiple files for a single subject frame will be supported in version of 1.1 of the Python client, which will probably be released in November.

**Comment by eatyourgreens** [comment]
@li-yp I'm not sure what's going on with the layout of the classification page, but your subjects have 2 frames in the locations array. One for the audio, one for the image:
```javascript
subject.locations = [
    {'audio/mp3': audio_file_URL}, 
    {'image/jpeg': image_file_URL}
]
```
For the audio player to work, the subject should have one location in that array, which contains both file URLs:
```javascript
subject.locations = [
   {'audio/mp3': audio_file_URL, 'image/jpeg': image_file_URL}
]
```
I think the code @trouille posted is wrong. When you add the file locations, you need to be doing something like
```python
subject.add_location({'audio/mp3': audio_file_URL, 'image/jpeg': image_file_URL})
```
which will add a single frame that contains both files.

**Comment by eatyourgreens** [comment]
I've opened #4054 about the problem with the progress marker.

**Comment by li-yp** [comment]
Thanks @eatyourgreens . However, the command subject.add_location({'audio/mp3': audio_file_URL, 'image/jpeg': image_file_URL}) does not lead to a subject.locations in the format of [{'audio/mp3': audio_file_URL, 'image/jpeg': image_file_URL}] . I only get the location with the audio there, without the image.

Basically, what I do is that I created a subject set with a mp3 file and a subject set with a png (spectrogram) file. They are both added successfully, and I can view them in the project builder without problems.

Then, I use a command like subject.add_location({'audio/mpeg': 'https://panoptes-uploads.zooniverse.org/production/subject_location/ca0d3af0-0666-4d4b-8142-2a064df798de.mpga', 'image/png': 'https://panoptes-uploads.zooniverse.org/production/subject_location/edda53b8-38a2-4159-a90e-1f4f18a659db.png'}) to create a new subject set.

However, if I retrieve the address of the subject in this new subject set, I only get [<SubjectSet 14943>],
[{u'audio/mpeg': u'https://panoptes-uploads.zooniverse.org/production/subject_location/ca0d3af0-0666-4d4b-8142-2a064df798de.mpga'}]

The png file is missing.

Subsequently, the workflow using this new subject set only shows the audio player.

**Comment by trouille** [comment]
@li-yp As Jim wrote, "Uploading multiple files for a single subject frame will be supported in version of 1.1 of the Python client, which will probably be released in November."  This will allow you upload your audio subjects as pairs of linked files. Until then, it's probably best to pause on your efforts of linked audio + spectrogram files. With an experimental tool like this (audio in the project builder) that isn't part of our currently funded efforts and deadlines, the time scale for deployment is a little slower. I appreciate your patience and willingness to jump in and try while the code is under development.

**Comment by trouille** [comment]
Note: https://www.zooniverse.org/projects/yli/humbug is the project @li-yp is working on.

**Comment by trouille** [comment]
@li-yp Actually, before we pause, could you try uploading just a standard manifest.csv file that lists both the audio and image files for each subject? See https://www.zooniverse.org/help near the bottom of the page for an example manifest.csv with two files for a single subject.

**Comment by li-yp** [comment]
@trouille Thank you very much for your help and the coordiation. It works using Firefox and a manifest.csv that lists both the audio and image files for each subjects! I think that the key here is using Firefox instead of Chrome, as I probably had tried to this method and unfortunately with Chrome.

Basically the first two rows of the manifest looks like this:

subject_id | !image_name | !audio_name | !label |  
1 | a.mp3 | a.png | 3 |  

The only thing missing now is the progress marker. @eatyourgreens pointed out that the 
progress marker is rendered behind the image so that it is invisible. https://github.com/zooniverse/Panoptes-Front-End/issues/4054

Thanks!

**Comment by eatyourgreens** [comment]
@li-yp do you see the progress marker on the staging branch to fix that bug?
https://fix-audio-player.pfe-preview.zooniverse.org/projects/yli/humbug/classify?env=production

**Comment by li-yp** [comment]
@eatyourgreens Yeah, the progress marker is there! This is perfect. When can this be released? Cheers.

**Comment by eatyourgreens** [comment]
@li-yp #4054 is waiting for someone to check and review it. They may ask for changes, but once it has been approved and merged to master, deployment to zooniverse.org will happen within 30 minutes.

**Comment by li-yp** [comment]
@eatyourgreens This is fantastic. Thanks Jim for making all of these happen and your patience in teaching me those useful Python client commands!
