### ISSUE TITLE
Refreshing /classify switches a not signed-in user from their selected workflow to a different workflow

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#4065]
## Expected behavior
If a user selects a workflow and refreshes the page, the user should remain on the selected workflow.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
If a user is not signed-in, selects a workflow, and refreshes the page, a user can be switched to a different workflow. 

## Steps to replicate
On a project that allows volunteers to select a workflow (e.g., https://www.zooniverse.org/projects/laurasoul/fossil-atmospheres and https://www.zooniverse.org/projects/asimenstad/dcw-phase-2-demo), select a workflow and, once you are on the /classify page, refresh the page. The workflow switch doesn't happen on every refresh, so you might need to refresh the page a few times before the workflow switches.

## Additional information

- **Operating system:** Windows 10, MacOs
- **Browser:** Edge, Chrome

**Comment by srallen** [comment]
This is expected behavior if the user is not signed in. Currently, the selected workflow for a non-signed in user is stored in a temporary project preferences using the javascript client cache. Here's when they're created:

https://github.com/zooniverse/Panoptes-Front-End/blob/11ff09941b4168b8fbf4ad10fb08b49acdb4856f/app/pages/project/index.cjsx#L165-L169

If a non-signed in user refreshes the page, then it's a new session and that bit of javascript code runs again. If someone wants to keep their preference, then they need to sign in, so the preferences are saved to the server.

When a non-signed in user navigates directly to the classify page, then this order of workflow selection happens:

1. Use the workflow specified in a query param, if the project is enabled to use workflow query params
2. Use the project default workflow
3. Select randomly from the active workflows

We could consider using localStorage for users who aren't signed in, but my gut feeling is that might be a bad idea since it'd require a lot of manual cache management on our part to make sure it gets invalidated correctly in various scenarios.

**Comment by eatyourgreens** [comment]
You could store temporary preferences in sessionStorage, so that they don't persist when the browser closes.
