### ISSUE TITLE
Panoptes Planet Four

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4068]
Features needed to transition P4 from Ouroboros to Panoptes:

- [ ] a fan tool: the ice cream cone drawing tool where you can drag from a starting point outward. We did Panoptes triangle tool isn't close to this.  
![fans-3](https://user-images.githubusercontent.com/753325/30874526-5b2d885e-a28c-11e7-92c3-55e3777c4c26.jpg) 

Blotch tool is already available in panoptes. Ellipse drawing tool is sufficient for our blotch marking needs. 

less important:  

We find that the subject images show significantly smaller in panoptes. The P4 website had the marking tools on a side bar and subject image took up the full field of view. Currently in panoptes half the screen real estate is taken up by the drawing tool menu. We could add pan and zoom, but given the behavior of most volunteers not drawing when there are obvious sources we are concerned this would make even less volunteers mark and it significantly increase the classification time per subject. I'm not sure there is a solution or we would need to cut the images into smaller chunks). 

<img width="1122" alt="screen shot 2017-09-26 at 7 46 43 am" src="https://user-images.githubusercontent.com/753325/30875422-35d8942e-a28f-11e7-8a5b-485fbca5d03f.png">

<img width="1124" alt="screen shot 2017-09-26 at 7 46 40 am" src="https://user-images.githubusercontent.com/753325/30875406-23d81cf4-a28f-11e7-9c0f-e4f3f415925c.png">

both are showing P4 subject images

same thing for the Milky Way Project

![screen-shot-2013-05-08-at-9-22-55-pm](https://user-images.githubusercontent.com/753325/30876154-7ba8aac8-a291-11e7-8c4a-fd172812f38d.png)

<img width="1148" alt="screen shot 2017-09-26 at 8 01 59 am" src="https://user-images.githubusercontent.com/753325/30876176-870f5ae2-a291-11e7-9ff4-d24fb709e707.png">

we would like test out a 'none of the above present' or 'nothing to mark' button as an option to add to a drawing task, so volunteers can say explicitly there is nothing present in the image.  Currently there is no way with drawing tasks to indicate there was nothing to mark .We found that people don't mark when they are clear sources in Planet Four.  Someone not marking gives no information about what is the image unlike multiple choice decision trees. This was one option we would like to beta test if it existed to see if we engage people better in the task. We also plan to beta test asking 'are there seasonal fans and blotches? yes/no" before asking people to draw as another possible setup.

**Comment by mschwamb** [comment]
@chrislintott as requested

**Comment by michaelaye** [comment]
There's a lot of unused space in the drawing tool menu between the name of the tool, and the counters for how many have been drawn. If that would be compressed the display could be made bigger I guess? I would consider this a good option for all projects, we don't want the volunteers to squint (or use more complicated zoom tools) to be able to see things. It always has to be made as easy as possible to keep volunteers engaged.

**Comment by michaelaye** [comment]
Here's the space I mean (added a white box).

<img width="1122" alt="added_box" src="https://user-images.githubusercontent.com/69774/30880396-b7fe00d0-a2bf-11e7-92ae-00900605d136.png">

**Comment by beckyrother** [comment]
Hi @mschwamb and @michaelaye! Thanks for your comments! We're definitely on the same page about the classifier – totally agree that the space could be used a lot more effectively. 

The Zooniverse team are actually working on a redesign of the entire interface right now, and we're hoping to move into development within the next few months. If you're interested, [here's a click-through prototype](https://invis.io/GZBZCHLPB#/230707676_Page-Tutorial-First). Being a prototype, it doesn't show every possible action, but holding the Shift key will show you what's clickable. This prototype goes through a question task; drawing tasks will function a bit differently but will look visually similar. 

We've gotten quite a lot of feedback about the size of images, so to address that, you'll notice we've added an "expand image" button in the toolbar. I'd love to hear your thoughts about that functionality. I've also moved the field guide to a more visible place in the interface – with all the work that goes into creating the field guide, I want to make sure volunteers can find it easily. Now, it's a draggable popup that can stay on the screen while the user is classifying, making it easier to compare the subject to field guide examples. 

You'll also notice that the background image has been replaced by a solid, neutral color. This improves legibility of the questions and tool options, as well as makes the subject the main focus of the page. I didn't want to take away from a project's individual personality (one of my favorite things about Zooniverse!) – these background images aren't gone, but moved to the bar behind `Project Name` and the project navigation, and a smaller box near the bottom. 

There's a few other fun things in there, like a Dark Theme requested by a few researchers in the case of very light-colored subjects, the ability to see recently classified subjects in order to go back and discuss on Talk, and additional stats that may be of interest. 


I'll be sharing all this in Talk in the coming weeks, but I'd love to hear your feedback! You can reply here, or my email is becky@zooniverse.org if you'd prefer to email me directly. 

Thanks again!
Becky

**Comment by mschwamb** [comment]
@beckyrother thanks for the reply. Thanks for this. The expand image feature I don't think solves this issue. It's actually not something I'd want it my Zooniverse projects, but that's my preference for a few reasons. I can see it being useful for transcription projects, but for marking, if people have pan or zoom or click to really be able to see things then I worry less people will mark. I hope the pan, zoom, big version, will be toggles in the project builder to turn on and off in the interface like most of these features are now. 

It also adds, more complexity to data reduction.  I think, It's one of the reasons that most of the Ourboros projects don't have that ability, and went to having big images from the drawing projects that took up all the screen real estate. I know that people have different screen sizes, but having to make volunteers to always click the button see these features to mark isn't helpful as well. From Planet Hunters, I know most people don't actually use these features, so most times people are going to use the default setup to mark, especially if going to the larger view mode doesn't stay going to the next classification.

The new design looks great visually. It's definitely improves on the current setup.  I think it's still optimized for decision trees.  The image is bigger, but I think there's a lot of unused space where you could make the image bigger that's being used for a pretty top header and large project logo that could be shortened to make it easier to see features to mark. 

<img width="1280" alt="original" src="https://user-images.githubusercontent.com/753325/30929416-31d2b10e-a35a-11e7-80d0-df36ff2062b9.png">

<img width="1280" alt="screen shot 2017-09-27 at 7 46 05 am" src="https://user-images.githubusercontent.com/753325/30929419-33e5ad52-a35a-11e7-83e3-674d04347b0e.png">

To me looking at Ouroboros drawing projects, they look different than design tree classification interfaces. It seems like if there is going to be this front-end redesign that it could be up to  project owner to select  having the expand mode as default the project graphical layout for the classification interface if they need it say for drawing or  select to set up their project with the smaller view and include the ability to expand the subject be options.  But maybe that's not feasible. Even increasing the subject image display area in the current prototype I think would be extremely helpful for drawing projects and might be enough.

**Comment by michaelaye** [comment]
I agree with Meg: if the volunteers would have to expand the image every time for each new subject again to do good marking work, it will be considered a nuisance and some (not all of course) will drop off the project. It should be as easy as possible for them, with the least amount of clicks required, no mental barriers, just doing the task. These things of course might differ from task to task, so configurability by the project owner would be awesome, but if that's not possible, I would always vote for the larger display space.

**Comment by beckyrother** [comment]
Hi Meg and Michael,

Thanks so much for your comments. The interface is designed to fit in common screen sizes, so you can scroll down a bit to hide the project header and the screen real estate should feel better. And you're right, we definitely don't want to add complexity or more steps to the workflow, so we're also going to work on adding keyboard shortcuts to speed things up. That's a great point about keeping the larger mode view from classification to classification. 

In regards to functionality, we're not going to take away any of the features that are currently available. Project owners will definitely still be able to configure the tools in the same way they do now.

**Comment by mschwamb** [comment]
@beckyrother  I was trying to say that if the header was smaller you could make the image larger in the same viewport. From a science team perspective, I'd rather my project name be smaller and a bigger subject image displayed.  

 It seems we''ll have to have think about cutting the full frame HiRISE images into smaller chunks because we will lose resolution with panoptes since the subject image will be smaller than what is shown on the current Planet Four. That would solve the problem, but means it will take longer to process the same about of HiRISE images. Definitely something we can live with. 

If there's any way the subject image can be a bit bigger in the new design from currently in the design, I think that would be helpful for many projects including Planet For.

**Comment by beckyrother** [comment]
I see what you mean. I did an audit of common screen sizes and found that a volunteer's average viewport height is 648px, so that's what this screen height is based on. Keep in mind that with responsive web design, these images will scale in a way that I'm not able to demonstrate with this InVision prototype. The current interface actually does a good job illustrating this: when you resize the browser window, the header stays the same height and the image gets bigger.

**Comment by camallen** [comment]
@mschwamb i just had a look at both planet four site vs a current zooniverse project (https://www.zooniverse.org/projects/sandiegozooglobal/wildwatch-kenya) using responsive view port mode 800 w x 648 h as per @beckyrother's data.

In those screen dims, it seems that the rendered image is actually bigger in zooniverse.org at that screen size as it takes up all the available space compared to planet four which has the tools selection on the left. 

I know this isn't an ideal comparison (what screens have 800w?) as having the tools available next to the image seems ideal and also the zooniverse.org layout changes considerably with with the viewport width. Judging layouts in different view ports is hard but agree that we should do as much as we can with the most real-estate. Also in fairness to Meg, switching the width to 975 w x 648 h shows a marked layout difference in favour of P4.

800 w x 648 h
------------------
![image](https://user-images.githubusercontent.com/295329/30973840-038f5b5a-a466-11e7-8565-32aa08f3ac8c.png)

![image](https://user-images.githubusercontent.com/295329/30973853-0ec4fbb0-a466-11e7-8791-ad8b6e2839f3.png)

975 w x 648 h
------------------
![image](https://user-images.githubusercontent.com/295329/30974179-e51a348c-a466-11e7-92ed-056e5ba5f9b1.png)

![image](https://user-images.githubusercontent.com/295329/30974190-eb9506b6-a466-11e7-9808-67dd8cd96275.png)

**Comment by eatyourgreens** [comment]
Not so fast, stale-bot!

**Comment by michaelaye** [comment]
Planet Four is notoriously difficult to do on tablets and phones, do you have data indicating that desktop use is in decline even for Planet Four?

**Comment by eatyourgreens** [comment]
@michaelaye I imagine @mschwamb has data for P4:ridges on Panoptes. I think we store the viewport pixel dimensions on each classification, and also the user-agent so that you can filter for mobile classifications.

Anecdotal, I know, but much of the Talk feedback we get during events like StarGazing Live seems to be from people who were classifying on tablets.

**Comment by mschwamb** [comment]
@eatyourgreens P4 I think can't tracks this as much. At least that info isn't in the csv data dumps. My anecdotal experience is that when it's a drawing task they use the desktop since it's hard to be as precise with fingers on an tablet. I think for question tasks which the stargazing live project was people can easily do on tablet, so lots more do.

**Comment by mschwamb** [comment]
I'm going to close this and just open a ticket for the fan tool since I think the discussion that item is can easily get lost in this discussion.
