### ISSUE TITLE
Make an actual news page. 

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4090]
## Expected behavior
The inconsistency of link behavior in the header is unexpected. It should be consistent and the news link should link to a page that has Zooniverse News. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The News link in the header is a drop down that includes the link to the Zooniverse blogs.

Note: I discussed this with @beckyrother when doing the initial building the reusable header for the Zooniverse-React-Components repo. The News link is left off of the initial build of this header because of the proposed change. For us to make this change, we'll need a basic wireframe and content for the page.

**Comment by trouille** [comment]
@beckyrother Do you have a design of what this 'news' page would look like? And/or is it redundant to having the news feeds on the landing page (but maybe that kind of redundancy is OK)?

**Comment by beckyrother** [comment]
We had talked about this because currently News is the only menu item with a dropdown menu. I don't necessarily want to create an entire new page for this, since we already have both a long-form blog and the daily zoo blog. 

Open to suggestions about this; I don't have a lot of background knowledge about the two blogs and don't want to prioritize one over the other. Maybe we can sit down and talk about it after Member's Night?

**Comment by srallen** [comment]
@beckyrother sounds good. Maybe the section on the home page is sufficient and the dropdown menu can just be removed from the header?

**Comment by trouille** [comment]
@mrniaboc Please see above. Do you have thoughts on the 'news' tab in the zooniverse header? 

Note: There are links directly to Daily Zoo and Blog in the footer, and the landing page has the news feed from those. 

Would you be able to see in our current Google Analytics what fraction of people actually scroll down on our landing pages? What fraction currently click on the 'News' tab?
