### ISSUE TITLE
the text subTask modal changes size when re-opened

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#4095]
## Expected behavior
The text input in a subTask modal should stay consistently sized each time the subTask is opened.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The text input in a subTask modal is the correct size when initially opened. However, if a volunteer re-selects and opens a subTask modal, the size of the text input is greatly increased.

## Steps to replicate
On a project with a drawing task with a transcription subTask (e.g., decodingthecivilwar.org):
1. Draw a line
2. Provide a transcription for that line
3. Press "Ok" on the transcription modal
4. Re-open the modal by selecting the drawn line

## Additional information

- **Operating system:** MacOS
- **Browser:** Chrome

**Comment by eatyourgreens** [comment]
Seems to be caused by inline styles added in 4232ca22. We should check with @mcbouslog before removing that.

**Comment by eatyourgreens** [comment]
This is still a bug, caused by the dynamic sizing code referenced above.

**Comment by eatyourgreens** [comment]
Still a bug, and since the classifier redesign, text boxes now show up too small when the component initially mounts.

**Comment by snblickhan** [comment]
[Screen recording](http://tinypic.com/r/2d9zeap/9) of a related bug dealing with text subTasks -- in this case, text box isn't auto-resizing to fit the text, and doesn't fix itself until you start typing.

**Comment by mcbouslog** [comment]
I think the issue is that `@refs.textInput.scrollHeight` [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/text/index.cjsx#L105`) is undefined even after `componentDidMount` [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/text/index.cjsx#L69), causing the initial sizing issues with or without an annotation present. 

In `updateHeight`, adding a scrollHeight > 0 conditional check solves for first load, but not if annotation already completed and volunteer is going back to review annotation. 

I think I need to convert the text task to ES6 and use the [new ref functionality](https://reactjs.org/docs/refs-and-the-dom.html).

**Comment by eatyourgreens** [comment]
Setting a minimum of 1 row on the text area (#4754) has, at least, fixed the issue where it was showing up as zero height when the popup first appears.

**Comment by eatyourgreens** [comment]
If there's already an annotation, then the initial height (or minimum height?) should be calculated from the annotation text, rather than set to 1.
