### ISSUE TITLE
Error: Couldn't find project

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#417]
Hi there

Since today I can't seem to 'View' the demo projects I created in Panoptes, although I can edit

e.g. http://demo.zooniverse.org/panoptes-front-end/#/projects/Aprajita/FaceWarps
http://demo.zooniverse.org/panoptes-front-end/#/projects/Aprajita/SpaceWarpsRings

Any ideas what might be wrong?

Thanks very much
Aprajita.

**Comment by edpaget** [comment]
I'm not sure if this will work because your projects are private, but if you try with your name lower-cased as in http://demo.zooniverse.org/panoptes-front-end/#/projects/aprajita/FaceWarps are you able to see it. 

We're in the process of making urls more consistent, and somethings might not be fully working on our demo site yet.

**Comment by aprajita** [comment]
Thanks @edpaget, that works! 

Should I re-register on panoptes with a lower case username?

Thanks
Aprajita.

**Comment by edpaget** [comment]
Nope your name should be fine. @brian-c was still working on adapting the site to use the new regularized urls. Everything should be handled automatically when he's done.

**Comment by aprajita** [comment]
OK, thanks @edpaget!
