### ISSUE TITLE
Weird dashed box appears over  navigator menu title for the page you're on if you click to another tab in Firefox and come back

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#423]
Not sure if the title makes any sense, but in the latest version of Firefox (38.0.1) on OS X Yosemite when
I navigate to a page for a project (let's say science page _ and then say go to any open tab in my browser and then go back to the Zoonvierse project this weird dashed outline box is now surrounding the world science. 

Screenshot is below after I come back to the Talk from viewing another tab in my Firefox browser 

![screen shot 2015-05-27 at 6 48 22 am](https://cloud.githubusercontent.com/assets/753325/7835388/270ee444-043e-11e5-96b8-7978862f4eaa.png)

This doesn't happen in Chrome or Safari - just Firefox

**Comment by eatyourgreens** [comment]
That's the browser's default indicator for the element that currently has keyboard focus. You might be able to turn it off through Firefox's accessibility settings, otherwise go into the browser config through about:config, search for browser.display.focus_ring_width and set it to 0 to get rid of it.

**Comment by mschwamb** [comment]
Thanks. I'll close the issue then.
