### ISSUE TITLE
Add schemas for drawing tool annotations

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#4478]
Related to #4423 

Following on from @mschwamb's Zoominar earlier today, I propose adding JSON schemas for all drawing tools.

1. For each tool, we create a [JSON Schema-compliant](http://json-schema.org/) spec, which includes a description of each property and a note saying where the origin is.
1. When a drawing tool is used in the classifier, a copy of the spec for that tool gets appended to the classification object.

This would mean that:

- Researchers know exactly what the data means when using exports
- Caesar can work to a spec when crunching classifications, rather than inferring from mark type
- Specs can be used to test drawing tools in the front end

**Comment by eatyourgreens** [comment]
Adding additional data to the classification exports sounds painful. We're already trying to reduce them in size. Could Caesar get the annotation schema from the workflow?.

**Comment by mschwamb** [comment]
What about adding a version id and somewhere else the annotation schema is like a wiki/read the docs linked on the project builder export page

**Comment by mschwamb** [comment]
Could this be added to the workflow contents export so it doesn't bog down the classification export with more stuff? I don't know actually know what the different between the workflow contents export and the workflow export is? Interestingly the drawing tool/type isn't listed in the workflow contents export (e.g. "T1.tools.4.label":"Fan Tool")

 I would suggest  a version id for marking tools be added (assuming all drawing tools in panoptes are still the original version?) because we had to have that in P4 when the bug in the fan tool was identified well into the project where it was measuring the incorrect angle. You could use the stored info to compute the correct angle, but you needed to know what classifications needed that applied. 
 So a marker version id was added to differentiate between what we had to correct in terms of measuring spread and what was measured with the corrected drawing tool.

**Comment by eatyourgreens** [comment]
More generally, each task should have a description of its annotations. I'm not sure if that should be a separate issue or incorporated into this one.

@mschwamb the workflow contents export is used by translations and contains the primary language version of your workflow text. At the moment that's English for all workflows. You can see an example of a workflow in two langiages, on a live project, at [Snapshot Hoge Veluwe](https://www.zooniverse.org/projects/y-dot-liefting/snapshot-hoge-veluwe).

**Comment by mschwamb** [comment]
I do think it's hard for project owners to have to figure out what annotation tool provides, since there isn't documentation. Sending people to the data digging github repo isn't really the answer especially since some of the info isn't update what changes are made.
