### ISSUE TITLE
Add External links to not just the project landing page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4501]
I've showed a few people the Planet Four: Ridges and Planet Four: Terrains websites and no one ever made it down to the external link pages. It's my usual test of new features to see responses for myself. They all clicked on the 'get started' button and wanted to dive into the project. 

Can you at least put the external links somewhere else as well since there's very little chance someone is going to see them who's new to the site? Perhaps they could be added to Talk somehow? @beckyrother

**Comment by beckyrother** [comment]
Hi @mschwamb, we removed these external links because based on the survey I sent out a few months ago, the home page was the only place people were clicking on them. In order to keep the width of the nav bar at a minimum and prevent the options from folding into a drop-down menu, it was determined that the links should stay just on the home page.

I wonder if a compromise could be reached. Would just the Blog link be sufficient to put back in the nav bar? I certainly do not want to discourage people from maintaining the rest of their social media but it seems Blog is the most cause for concern. I still worry that on some projects this may be enough to push it back into the drop-down menu, but I suppose we could test it to find out.

@srallen what do you think?

**Comment by mschwamb** [comment]
What about them having their own little space with just icons on the home page only and if projects have additional external links that aren't social or a blog that could go into the new section you developed? In Ouroboros projects, the rss symbol was used for the blog? 

What about having the icons below the 'Get Started button' ?

<img width="1043" alt="gz_social_below" src="https://user-images.githubusercontent.com/753325/39854086-b06eeb96-53c1-11e8-938e-8dcaf17f3542.png">

or the way Galaxy Zoo 4 did with the social media icons  and blog link on a separate line but having it only appear on the home page. 

<img width="1043" alt="screen shot 2018-05-09 at 7 44 33 pm" src="https://user-images.githubusercontent.com/753325/39854060-8638a718-53c1-11e8-85e0-91eb8b1f291e.png">

**Comment by mschwamb** [comment]
I'd like to see this issue not be stale
