### ISSUE TITLE
Classifier for Galaxy Builder doesn't load subjects on iOS

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#4542]
## Current behavior

![img_1578](https://user-images.githubusercontent.com/428423/39209412-a7d628de-47fd-11e8-9e0d-afe6e18e091f.png)
![screen shot 2018-04-24 at 20 21 36](https://user-images.githubusercontent.com/428423/39209437-aa86b8a0-47fd-11e8-9cf5-297af20efe39.png)

## Additional information

Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1

**Comment by eatyourgreens** [comment]
This is a subject viewer bug. Talk subjects don’t load either.

**Comment by eatyourgreens** [comment]
Even if you can’t classify without webGL, you should be able to comment on a subject.

**Comment by tingard** [comment]
Android too I think? This is expected behaviour - the model is too complicated for mobile devices for some reason.

A fix would be to be more clever with the way I set up my rendering commands, but time constraints meant I had to shelf that idea.

To be honest I'm confused as to why it's complaining, so will do some digging. The best fix I can think of for now is to catch the error and display some kind of text fallback
