### ISSUE TITLE
"Need some help with this task" doesn't look like a button that one can click on

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4583]
@beckyrother I understand the design changes but honestly the need some help with this task doesn't look a button to me and it's not clear what it does when one moves a mouse over it. As a project owner that really concerns me that people aren't clicking on the help button anymore because it doesn't look like a button where the tutorial now looks like something very clickable 

The help button aka the 'Need some help with this task' is as just important as the tutorial even more so because it goes into detail about how to do the task. As a project owner this change really concerns me. 

<img width="1099" alt="screen shot 2018-05-01 at 11 31 24 pm" src="https://user-images.githubusercontent.com/753325/39516283-3a14974a-4d98-11e8-87ea-370cc4cc127d.png">

**Comment by mschwamb** [comment]
Feel free to close as no next fix, but to me it wasn't apparent that the need some help with this task was a link or something I could click on.

**Comment by srallen** [comment]
It is styled to have hover and focus styles and switches to the pointer cursor. I'm not sure we can know the click rate without analytics tracking of that specific click event. This wasn't tracked before the style updates, so we wouldn't have anything to compare it to unless we did a specific new a/b test with a visibility split for the button styles.

The mini-course button and the theme switching button are styled the same way, for what it's worth. I'd like to wait for more information before making a change. I'll leave this open for now since having analytics on this is a good idea.

**Comment by beckyrother** [comment]
@mschwamb This button behaves in the same way as text links throughout the site, with an underline hover state. I'd argue that it's more accessible now than the previous iteration's grey box. 

Good idea about analytics on links within the classifier – we've been sending surveys to find information but having solid numbers would be good.
