### ISSUE TITLE
Discussion: What types of projects are there, and what do we call them?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#460]
Hey all,

I think it would be good for us to lock down a definition of exactly what types of projects there will be in the new Zooniverse under Panoptes, and what each one is called.

As I understand it, right now there seem to be four types of projects:

1. Only accessible to designated people/user names that you select.
2. Accessible to anyone with the link, but not promoted in any way.
3. Accessible to anyone with the link and listed on the site in a special page with other Type 3 projects.
4. Undergone a rigorous review process and promoted as an official Zooniverse project. (User projects alongside in-house-built projects.)

I'd propose the following as a starter idea: 1. Private Project, 2. Beta Project, 3. Community Project, 4. Certified Project.

This is, however, slightly different from the current plan, as I understand it from @chrislintott 's Panoptes Policies draft, which had 2. as "Private Project," 3. as "Beta Project," and 4. as "Zooniverse Project." (Type 1 didn't have a name.) So my proposal would shift the definitions somewhat.

What are people's thoughts? Are there other types of projects that I'm missing? What do folks think of these names? @vrooje had some thoughts in the Panoptes Policies document... do these ideas address those?

Thanks!!

**Comment by brian-c** [comment]
I believe this was settled in #240, which I'm working on implementing right now.

**Comment by whyte** [comment]
Personally I think they need further discussion.

The term 'playground' project I find a tad patronising, especially given that there is no reason why these projects won't have very serious goals. For instance civic projects or research projects that scientist or educators might choose to do with small group. It's just they won't be promoted to the wider Zooniverse community or have been through peer review. 

Also we will certainly be using the project building functionality with Adler teen interns and volunteers. I cringe at the thought of trying to convince them they are doings something worthwhile in a 'playground'.

I vote we shift the language to 'community project'.

**Comment by DarrenMcRoy** [comment]
I think that the types of projects look good, but there may be room for further discussion/changes with regards to their front-facing definitions?

**Comment by DarrenMcRoy** [comment]
Okay, so, an update, having talked with @chrislintott and gotten a better idea of types of projects, these are the four that we have:

1. **Private Project** - only accessible to designated people/user names that you select.
2. **Independent Project** - accessible to anyone with the link, but not promoted by Zooniverse in any way.
3. **Beta Project** - available on a 'Beta' page on the site, otherwise not promoted. (These are projects that intende to eventually graduate to Zooniverse Project status.)
4. **Zooniverse Project** - undergone a rigorous review process and promoted as an official Zooniverse project (user projects alongside in-house-built projects).

This is slightly different from what I had above in that the only projects that ever appear on our site anywhere are ones that either have gone through a review, or plan to eventually. More cute, educational, or experimental projects (what I had called "Community" projects, and are here called "Independent" projects -- that name could probably go either way -- it won't be "Playground" @whyte, so no worries there! -- but, yes, "civic projects or research projects that scientists or educators might choose to do with small groups," those) would not appear anywhere on the site, not even on a designated page for them. (@chrislintott says that could change eventually if we see good Independent/Community projects, or interest for the feature).

Based off of @brian-c 's visibility page and what I read in #204, there appear to be two other settings projects can technically be in: beta-private and Zooniverse-private, since "private" is a switch can be applied to the basic, beta, and even Zooniverse stages of projects. This is apparently intentional, for projects that are being retired, or have a more limited beta, or other use-cases? Even certified Zooniverse projects should be able to be private?

Overall, I would say that this model that we are now working with emphasizes "becoming a Zooniverse project" as the intended end goal and general project raison d'etre, over just having your project online somewhere, which I rather like. :+1:  I do have a concern that there will be projects that will end up in the Beta stage on a more permanent basis; we may want to consider how long a project can hang in Beta if it becomes clear that it will never attain full certification.

Sorry for taking a while to get on board with this. It seems like there has been good work done so far. Thanks everyone, and thanks for helping me get on board with this. Discussion still welcome!

**Comment by vrooje** [comment]
Interesting. If we separated public/private we could re-frame the public-facing text like: "There are 3 types of projects: Independent, Beta, and Zooniverse. [Description of those.] Your project can be private, or you can open it to the public. While it's technically possible to have any type of project be private, the majority of Beta or Zooniverse projects will be public so that volunteers don't have to be individually added by the research team before they can participate."

Somehow this seems simpler to me.

I also like the idea of calling the final stage a Zooniverse Project, so that that has a specific meaning that is different from "a project built on the Zooniverse".

**Comment by DarrenMcRoy** [comment]
If that is indeed the model we're going with, @vrooje -- that is infinitely more succinct and understandable. I am 100% on board with that, as long as we do intend to allow Beta and Zooniverse projects to have private modes!

**Comment by aliburchard** [comment]
We can certainly ditch the term "playground" but it was never intended to be used for projects that were at the stage of collecting data. See the table in #240 that makes the distinction between "playground" and "live non-zooniverse"  (or more aptly termed "independent"/"community project", as @whyte suggested). But "community" and "independent" simply replace "live non-zooniverse," NOT "playground."

"Playground" is a bit of an artificial distinction -- all it means is that users are in a "building/tinkering" mode and the "lock" or "live" key is set to "false" so that workflows are not locked to changes, and classifications don't count towards retirement (though see #273). 

Allowing users to switch into some sort of "live" mode starts (or re-starts) counting towards retirement and locks the workflow so that project builders can't accidentally make workflow changes that effectively delete all their classifications.  Note that classifications aren't actually deleted, but that the aggregation engine will no longer automatically include them, and I suspect most users want to use the built-in aggregation.

**Comment by aliburchard** [comment]
Also, I don't think we plan to have Beta and Zooniverse projects that are "private" (not as a general rule - we can make exceptions under certain circumstances on a case by case basis, I imagine.)  We can have "playground" and "independent/community" (i.e. Live, Non-Zooniverse projects) projects that are private where project builders are collecting classifications, counting towards retirement, etc, but I think the point of going through the approval process is so that we can make sure the broader Zooniverse community isn't being spammed with half-built projects. So us spending time approving projects that remain private doesn't make much sense.

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes/pull/946
