### ISSUE TITLE
More invalid annotations breaking exports

### ISSUE THREAD

**Issue by zwolf** [zooniverse/Panoptes-Front-End#4606]
_or, The Revenge of Malformed Annotations_

See. #4401 for the backstory, this is the same project (3414, AACWS). One classification out of ~35k in their new workflow caused the whole export to fail. Here's the offender:

```
{
  "id": 99326695,
  "project_id": 3414,
  "user_id": null,
  "workflow_id": 6177,
  "annotations": [
    {
      "task": "T1",
      "value": [
        {
          "task": "T5",
          "value": "Alfred Light"
        },
        {
          "task": "T7",
          "value": [
            {
              "value": "b976466b565c4",
              "option": true
            }
          ]
        },
        {
          "task": "T8",
          "value": "40 "
        },
        {
          "task": "T9",
          "value": [
            {
              "value": 5,
              "option": true
            },
            {
              "value": "e0fa2ec32ec82",
              "option": true
            },
            {
              "value": "6a02f2a5e1313",
              "option": true
            }
          ]
        }
      ]
    },
    {
      "task": "T2",
      "value": [
        {
          "task": "T10",
          "value": "dark"
        },
        {
          "task": "T11",
          "value": "Gray"
        },
        {
          "task": "T12",
          "value": "dark"
        },
        {
          "task": "T13",
          "value": [
            {
              "value": "96fbf1cb4fa7c",
              "option": true
            },
            {
              "value": "Bristo",
              "option": false
            },
            {
              "value": "Penua",
              "option": false
            }
          ]
        },
        {
          "task": "T14",
          "value": "Farmer"
        }
      ]
    },
    {
      "task": "T22",
      "value": [
        {
          "task": "T21",
          "value": []
        },
        {
          "task": "T16",
          "value": []
        },
        {
          "task": "T17",
          "value": ""
        },
        {
          "task": "T18",
          "value": ""
        },
        {
          "task": "T19",
          "value": ""
        }
      ]
    },
    {
      "task": "T22",
      "value": [
        {
          "task": "T21",
          "value": [
            {
              "value": "17e6ef6867bec",
              "option": true
            },
            {
              "value": "33ac8a1fa74e9",
              "option": true
            },
            {
              "value": "53ccd89936df5",
              "option": true
            }
          ]
        },
        {
          "task": "T16",
          "value": [
            {
              "value": "4996395408fd6",
              "option": true
            },
            {
              "value": null,
              "option": false
            },
            {
              "value": "d67629b72405f",
              "option": true
            }
          ]
        },
        {
          "task": "T17",
          "value": "Cant M'blung"
        },
        {
          "task": "T18",
          "value": "3"
        },
        {
          "task": "T19",
          "value": ""
        }
      ]
    }
  ],
snip
}
```

Didn't put it behind a gist this time cause whew let's all just appreciate that annotation for a second. API side, I think I'm going to associate this classification with a different workflow just so I don't have to delete it. That'll at least let exports run, but these dropdown tasks are a quagmire we need to wade through to make sure this doesn't keep happening.

cc: @mcbouslog

**Comment by mcbouslog** [comment]
A classification from this workflow should have 3 annotations, not the 4 shown above. The combo task T22 is duplicated, the first time with all default annotations, the second with actual annotations. I'm not sure how that happened given [this code in classifer.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/classifier.jsx#L220), but will look into more this week.

The first instance of T22 consists of all default annotations for the dropdown tasks, so it appears the dropdown tasks never mounted. If they had, `componentDidMount` would have called `setDefaultValues` and the annotations would have been updated to reflect `[{ option: false, value: null }, { option: false, value: null }, { option: false, value: null }]`.

**Comment by camallen** [comment]
@zwolf - I think originally we wanted to know more why this happened so we did error. However, now it appears after we investigate we don't really know why. Code change in pfe? Browser issue? Random sun activity? Stray wizard magic? 

Should our dump processor be more lenient towards these errors and report them but skip them from the dumps instead of failing?

**Comment by mcbouslog** [comment]
If the dump processor could fail gracefully when the dropdown is an empty array (it's default annotation) it would prevent the hangup we saw with this export. It's not a solution or an explanation like I want to provide, but that's all I've got.

I couldn't reproduce the bug, and any solutions I thought of like checking for duplicate tasks would prevent legitimate recursive workflows.

**Comment by zwolf** [comment]
@camallen It doesn't error in a useful way. The job just dies, sends nothing useful to HB, and I have to comb through every classification on the console to figure out which one causes the error. This is not better than just catching it and printing "OOPS" as the annotation. One in 35,000 is a bummer to debug. Unless a refactor is on the horizon (and maybe even then) it would be worth catching exceptions thrown by the annotator here: https://github.com/zooniverse/Panoptes/blob/master/lib/formatter/csv/classification.rb#L64

**Comment by camallen** [comment]
I was thinking we should catch these errors and report the classification id and error class + details to HB  manually. That way we can keep abreast of them as we need but still not fail the export. 

I'd probably say just ignore malformed classifications instead of leaving them in for the researcher to deal with. Perhaps here https://github.com/zooniverse/Panoptes/blob/d79d1881615178dfc0f644546424657c87272171/app/models/csv_dumps/dump_processor.rb#L29 for more general error reporting for all csv exports?

**Comment by zwolf** [comment]
That'd work too, so long as researchers don't miss the classifications.

Issue created: https://github.com/zooniverse/Panoptes/issues/2764

**Comment by mcbouslog** [comment]
Not entirely sure they're related, but the following classification also has a duplicate annotation. This workflow consists of two steps, the first a survey task, the second a question task, it does not have a combo task and does not have a dropdown task. It may not be related because this new classification has a partial annotation for the first of the duplicated annotation (issue with update), whereas the initial classification documented in this issue's duplicated annotation includes a default annotation (issue before component mount). The classifications are months apart, different projects. I'm still not sure how this happened given [this code in classifer.jsx](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/classifier.jsx#L220). Documenting for now, I'll follow-up with @trouille on steps forward.

```
{
  "id": "60130010",
  "annotations": [
    {
      "task": "T0",
      "value": [
        {
          "choice": "HUMAN",
          "answers": {
            "HOWMANY": "6"
          },
          "filters": {}
        }
      ]
    },
    {
      "task": "T0",
      "value": [
        {
          "choice": "HUMAN",
          "answers": {
            "HOWMANY": "6"
          },
          "filters": {}
        },
        {
          "choice": "DOGDOMESTIC",
          "answers": {
            "HOWMANY": "1"
          },
          "filters": {}
        }
      ]
    },
    {
      "task": "T1",
      "value": null
    }
  ],
  "created_at": "2017-06-16T17:46:05.722Z",
  "updated_at": "2017-06-16T17:46:05.765Z"
}
```

**Comment by mfidino** [comment]
To add some additional information to what @mcbouslog documented here. The second `T0` was the correct ID for this image while the first `T0` was not.

This was the only bit of JSON in the classifications output for Chicago Wildlife Watch that had multiple instances of `T0`.
