### ISSUE TITLE
Shift+tab into text box should send carat to end of transcription

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/Panoptes-Front-End#4632]
## Expected behavior
Shift+tab into text box should send carat to end of transcription (or where transcriber left off)
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Shift+tab into text box sends carat to the beginning of the transcription box
## Steps to replicate
- Go to a PFE transcription project: https://www.zooniverse.org/projects/tkotwim/the-american-soldier/classify
- Enter transcription, then use any of the text modifiers
- Use Shift+Tab to return to text box
- Carat will default to the start of the text, rather than the end
## Additional information
Original Talk post flagging this up: https://www.zooniverse.org/projects/tkotwim/the-american-soldier/talk/1671/633636?page=1&scrollToLastComment=true
- **Operating system:** Mac OSX High Sierra 10.13.3
- **Browser:** Chrome

**Comment by eatyourgreens** [comment]
The solution to this is that the text modifier buttons should move the text caret to the end of the closing tag, after inserting tags. The browser restores the previous caret position correctly when you enter the text box, but that position is destroyed when a text selection is replaced by the deletion/insertion/unclear tags.

You can verify the expected behaviour by tabbing/shift-tabbing into the box without adding modifiers to the text.

**Comment by eatyourgreens** [comment]
What would be great, I think, is that adding a modifier should restore the caret position, and move focus back to the text input so that you can continue typing. At the moment, focus stays with the modifier button.

**Comment by eatyourgreens** [comment]
From a quick reading of the docs for [HTMLInputElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement), I think setting `element.selectionStart` will move the text caret to the selected position.
