### ISSUE TITLE
Image sizing

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#47]
What governs the sizing of images to users? 
Is it the size of the image that's uploaded?
If the image size uploaded is too big for a screen, are there maximum dimensions for the displayed image?
Will project owners be able to change the size of the displayed images?

I'm just trying to understand the "look" of the project site. On my screen, if I have the full image, the question, and "Finished" all on the screen at once, I can't see any of the header or footer bars. I would like be able for users to see the full image and the option "Finished" at page-load without having to scroll down...

**Comment by brian-c** [comment]
Currently images are stored exactly as they're uploaded. They should be displayed so that they are no taller than the viewport and no wider than about 80% of the working space. The tasks and prev/next/done buttons on the right should also not be taller than the viewport (with prev/next/done anchored at the bottom), but I'm not yet sure what happens if you have more options than what fit in the space.

@heathv hasn't gone through this yet, so it's all totally subject to change.
