### ISSUE TITLE
Field Guide Editor ignores external changes with multiple authors

### ISSUE THREAD

**Issue by taekb** [zooniverse/Panoptes-Front-End#4772]
## Expected behavior
All changes made to the field guides should be saved properly.

## Current behavior
The field guides sometimes become completely overridden with an older version or even get deleted.

## Steps to replicate
Not sure how to replicate but have been noticing the issue when the field guides were checked a few hours after making changes to them. The issue was the same regardless of which computer/account we used to access the field guides.

## Additional information

- **Operating system:** Mac OS
- **Browser:** Google Chrome

**Comment by camallen** [comment]
I just updated a field guide on my test project and the content was updated automatically. After 20 minutes the content is still the same. 

Are you testing on only one computer or across different devices? I.e. change on my desktop and when i check on my colleagues laptop the field guide is gone? 

Is only one person editing the field guide at one via https://www.zooniverse.org/lab/ ?

Any details you can provide to help us reproduce the issue are invaluable, without the ability to determine their is a bug we can't do much.

**Comment by eatyourgreens** [comment]
I can reproduce this if I have the field guide editor open in two different tabs. Edit the field guide in one tab, save, switch tabs to an older version then save that version over the updated version.

My best guess is that this bug happens when more than one person is editing the field guide at the same time, or possibly when more than one person is editing the project at the same time (if they accidentally overwrite the project-field guide link.)

**Comment by eatyourgreens** [comment]
Here's my steps to reproduce this:
1) Open a field guide in two different tabs: https://master.pfe-preview.zooniverse.org/lab/908/guide
2) In Tab A, edit both section titles and save.
3) In Tab B, edit the section two title and save.
4) Refresh Tab A.

The edits to both section one and section two in Tab A are lost. I'd expect the updates to section two to be lost, since two people were working on it at the same time, but not the changes to section one.

**Comment by eatyourgreens** [comment]
A quick fix might be to add a query param to the get request here, forcing the project builder to get the latest version of the field guide from Panoptes.
https://github.com/zooniverse/Panoptes-Front-End/blob/d97921cdbfbd0397db6431a2f9884704f99e6c51/app/pages/lab/field-guide/actions.js#L37-L51

**Comment by eatyourgreens** [comment]
I've updated the PR title to reflect the bug that occurred when editing the field guide sections in multiple tabs/windows.
