### ISSUE TITLE
Highlighter tool styling

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#5099]
## Expected behavior
Better intuitive behavior or styling. The text area could be autofocused instead of the task area. The highlight buttons could be styled very differently to distinguish it from the single choice, multiple choice, and drawing tasks where you select the input first. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Highlighter tool is the opposite from the rest of the tasks. You must first select the text, then hit the highlight buttons to give the selection a color. This is confusing and has confused me each time I've interacted with the highlighter tool. Noted also in #5091

## Steps to replicate
https://master.pfe-preview.zooniverse.org/dev/classifier select "Annotate Text" as well as the last frame for the subject viewer to get a text subject.

## Additional information

@beckyrother asks

> Thanks Sarah! You're right, this is confusing, especially since the drawing task works the opposite way – clicking the type of annotation first and then clicking in the image. Is this possible with text? That is, click the highlight tool first and then select the text?

**Comment by srallen** [comment]
One suggestion from @beckyrother:

> Maybe the highlight button is inactive until text is selected, with a rollover or modal on click that explains that text needs to be selected first before this can be used.

**Comment by eatyourgreens** [comment]
You can't select text and automatically apply formatting with the [Selection API](https://developer.mozilla.org/en-US/docs/Web/API/Selection), because there's no way to tell when a selection is finished. The usual interaction with text selections is to create a selection first then interact with it by performing an action eg. deleting/modifying text or formatting text in an editor.

Here's a few use cases for the different ways a selection might be created:

- select a range of words by dragging the mouse/trackpad.
- select a range by double tapping then dragging the selection drag handles on iOS or Android.
- double click to select a single word, then expand the selection with the keyboard (eg. alt-shift-right arrow.)
- read the text in JAWS, NVDA or VoiceOver and select words at the current cursor position with the keyboard.
- select words using voice commands with Dragon.

OSX and WIndows also support [creating multiple text selections](https://www.cultofmac.com/138782/select-text-like-a-pro-os-x-tips/), but I've never been able to figure out how to do that and guess that most of our volunteers won't know about this either.

**Comment by eatyourgreens** [comment]
Something else to consider: tasks should be able to control the frame viewer in the subject viewer, when the task is limited to a particular type of file. In this case, the task should select the first text frame automatically. Here's an example, where the first question task shows you an image. If you select Yes, and move on to the text task, the subject viewer automatically flips to the first text frame for that subject. https://www.diagnosislondon.org/beta/#/classify
