### ISSUE TITLE
Workflow tasks can show the wrong instructions and answers

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5111]
## Expected behavior
When I classify on a workflow, the task text should match the task.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Under certain circumstances, I can be shown text for a different task than the one that's being recorded in the classification.
![A screenshot showing that the displayed workflow question does not match the text on the workflow resource.](https://user-images.githubusercontent.com/59547/48354797-7bb2f080-e68a-11e8-9c1c-ecba3bb6e8e5.png)
In this screenshot, the question displayed to the volunteer is
>The image to the left shows air and sea surface temperature observations taken during a cargo ship's voyage from the United Kingdom to Australia or New Zealand.

but the actual task question (shown in the Redux dev tools panel) is
>The image to the left shows latitude and longitude observations taken during a cargo ship's voyage from the United Kingdom to Australia or New Zealand.

The classification export for this classification will show the latitude and longitude question, not the question that was actually answered.
## Steps to replicate
Load a workflow resource from Panoptes along with the English translation resource for a different workflow on the same project.

## Additional information
The bug seems to be caused by a race condition in the workflow selection component. Workflow selection is loading workflow A and workflow translation A (say), then almost immediately mounting again and loading workflow B and workflow translation B. Since we can't guarantee the order in which API requests will resolve, this leads to four possible outcomes:
 

1. workflow A with the questions for A
2. workflow B with the questions for B
3. workflow A with the questions for B
4. workflow B with the questions for A

#5107 patched this by skipping workflow selection if an active workflow is already loaded for the current project.

- **Operating system:** n/a
- **Browser:** n/a

**Comment by eatyourgreens** [comment]
Note that best practice in React would be to cancel any unresolved promises when a component unmounts.

This bug could also be completely avoided by allowing projects to link to workflows by ID in the classifier URL.

**Comment by srallen** [comment]
Do we know what lines in the code were the race condition? In the rewrite, the selection code is going to be a part of the store and not involved with component lifecycle and rendering at all. However, I'd like to fully understand what happened here so it can be actively avoided in the rewritten code.

Regarding adding the workflow id back into the URL, do you see this as being a parameterized route, `/classify/1234` or adding back query params `?workflow=1234` support to all projects? I initially removed query params for Gravity Spy workflow promotion so that volunteers couldn't 'cheat' and load up workflows prematurely and break the promotion algorithm. As long as something like this can't break workflow promotion, I'm open to the refactor.

**Comment by eatyourgreens** [comment]
@srallen I think the race condition is workflow selection's `componentDidMount` running twice in quick succession, choosing a different workflow ID each time.

I think it should be okay for Gravity Spy to override default behaviour. I'd prefer Gravity Spy being an exception, rather than Gravity Spy setting the default behaviour for all projects, which we've got at the moment.

**Comment by eatyourgreens** [comment]
This should have been fixed by #5107. This issues is here so we have a place to discuss what the problem was.

**Comment by eatyourgreens** [comment]
This bug might still be triggered if you right click one of those home page workflow links and open in a new tab. That’s something to look at. 

Again, it would be fixed by adding the workflow ID to those links.

**Comment by eatyourgreens** [comment]
I think the UPP bug reported in this [Talk discussion](https://www.zooniverse.org/talk/17/770909) is down to `getSelectedWorkflow` running on mount (fetch the default workflow or a random workflow) then again on props change after the UPP update (fetch the workflow from the UPP.) After clicking those workflow links, which link to `/classify`, I think there's a delay between the component mounting and the preferences change listener firing.

That created the race condition laid out above, but for logged-in users, and explains why we saw two sets of requests for workflows + translations being fired by workflow selection in that case.

**Comment by srallen** [comment]
I'll take a look at the commit around that timeframe. What I can confirm is that on Aug 2 (4feda11ce4491f872ee8aea5666689e4cfc809db), `getSelectedWorkflow` was being fired twice because `componentWillUpdate` and the conditional in it was being evaluated true twice in `WorkflowSelection`. I haven't confirmed what the cause of that lifecycle method and the conditional evaluating true is yet.

**Comment by rogerhutchings** [comment]
cc #5066

**Comment by srallen** [comment]
I've checked the behavior of #5078 and found that Nov introduced a new variant of the bug. Two different workflows are requested; one on classifier mount; one on click of the home page workflow buttons because an API request was added to the onClick handler in #5035. This was fixed in #5107.

**Comment by eatyourgreens** [comment]
Closed by #5107.
