### ISSUE TITLE
Conversation user search

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes-Front-End#513]
@aweiksnar while working on notifications, I found that the conversation started on #/users/parrish was being started with the wrong user:

`GET https://panoptes-staging.zooniverse.org/api/users?display_name=parrish`

```json
{
  "users": [
    {
      "display_name": "parrish2"
    },
    {
      "display_name": "parrish_temp"
    },
    {
      "display_name": "parrish_signup_test"
    },
    {
      "display_name": "parrishv15"
    },
    {
      "display_name": "parrish_testing"
    },
    {
      "display_name": "parrish_serengeti"
    },
    {
      "display_name": "parrish003"
    },
    {
      "display_name": "parrish124"
    },
    {
      "display_name": "parrish123"
    },
    {
      "display_name": "parrishfamily4"
    },
    {
      "display_name": "parrish_ses_test"
    },
    {
      "display_name": "parrish76543210"
    },
    {
      "display_name": "parrish_no_reply_test"
    },
    {
      "display_name": "parrish_sea"
    },
    {
      "display_name": "PARRISH1108"
    },
    {
      "display_name": "Parrishalexandria"
    },
    {
      "display_name": "ParrishCN"
    },
    {
      "display_name": "parrish001"
    },
    {
      "display_name": "parrish"
    },
    {
      "display_name": "parrish_galaxy_zoo_test_123"
    }
  ]
}
```

The exact match is 18th in the results.  Since it's doing a case-insensitive pattern match, this endpoint is not useful to select a user by name.

@camallen, @edpaget We should either provide an actual filter on the serializer and move the search to a separate endpoint or I'll provide the proper response via the talk api.

I don't have a preference, but I can't imagine this won't be a recurring problem.

**Comment by edpaget** [comment]
That should be filtering on the slug parameter if it's being used in a URL.

**Comment by edpaget** [comment]
To elaborate as far as I knew everything in the front-end was going identify users via the 'slug' parameter for finding them in a human-readable way, since display_names of imported users can have spaces, which we don't want in URLs. If there are uses for wanting to uniquely identify a user by display_name I'll change the endpoint back, and allow you to provide a wildcard to do the search.

**Comment by parrish** [comment]
The slug filter is empty: `window.api.type('users').get({ slug: 'parrish' }) // { users: [] }`

It looks like the controller is querying user groups, but the slug for the 'parrish' user group is 'user-parrish-92'.  What chain of API calls would you have to make to arrive at that?

I can't filter user groups on name either: `window.api.type('user_groups').get({ name: 'parrish' }) // => 404`

I'm guessing the only way to approach this is to either

- Use slugged user group names everywhere in talk as the display name (user-parrish-92 doesn't feel great)
- Change the endpoint

**Comment by edpaget** [comment]
I'm not sure why your slug ended up being 'user-parrish-92' that should have only happened for users with names like '((}}))' whose names didn't turn into slugs properly. I'm going to investigate why and see how many accounts are affected. 

How do people arrive at profiles right now? The slug for a user is returned with their API response, so after doing a `GET /users/me` or a `GET /users/1` you'd have a slug you can construct a readable URL from.

**Comment by parrish** [comment]
Users are linked to by display_name.  It looks like user display_names have a validation to prevent spaces.  I thought we had addressed legacy usernames that don't pass validations in the migration?

**Comment by edpaget** [comment]
No the decision, as I understand it, was to just ask migrated users to change their names to something that will validate, but there would be no requirement for them to do so.

Are you linking the names for @-mention stuff? I'm asking since if you're getting the display_names from the API you'll also get the slugs.

**Comment by aweiksnar** [comment]
Any current @username link issues in the parsed markdown are probably my fault. I've still been thinking on how to best handle those; Looking into either redirecting idealized urls to ones that build up with the right info from the api (for subject urls especially), or seeing how promises/react-router-mixins integrate with RegExp#replace

**Comment by parrish** [comment]
@-mentions aren't possible when users have spaces in their names.  I don't think there's a reliable/practical way to disambiguate between the next word and part of the username.

As far as the slugged user names go, that'd be a fairly nasty refactoring.  Do we support users changing their login?  If not, then it's simply not worth it to bother with the slugs.

**Comment by edpaget** [comment]
Yeah I really wanted users to have a permanent non-changeable name with no spaces or special characters to use for urls and @-mentions.

I think the solution might be to make the @ symbol trigger a fuzzy user search and you could just record the user id instead of a name or slug and build a URL from that later.

**Comment by parrish** [comment]
Okay, I think I get what's at the core of this.

This is just the old problem of conflating login and display name.

`login` was renamed to `display_name` and was continued to be treated as the login.  It's still just the login.

`display_name` should only be text used for showing a chosen name and as *part* of the criteria for fuzzy user searches.

Slugs are only useful for pretty urls, we should be disallowing anything that doesn't match `/\w-/`

There's no edict that we can't force users to change their username.

There's no edict that we need to allow users to change their login -- only their displayed name.

Let's look at how github handles login changes:

> Really change your username?
> Unexpected bad things will happen if you don't read this!
>     - We will not set up redirects for your old profile page.
>     - We will not set up redirects for Pages sites.
>     - We will create redirects for your repositories (web and git access).
>     - Renaming may take a few minutes to complete.

It's basically destroying and creating a new account, with a massive update against all associated records -- certainly not a common thing to do.

All this aside, we should probably just be putting the user's ID into the URL.  Apparently that's the only good option at the moment.

**Comment by edpaget** [comment]
I'm not sure why slugs aren't as good as ids?

**Comment by parrish** [comment]
If my login is 'parrish', I have to be publicly identified as 'user-parrish-92'

If I change my login to 'somethingelse', I'm still publicly identified as 'user-parrish-92', which is bad.

Either that or the slug changes and it's not useful as an id.

**Comment by edpaget** [comment]
Since we're having this URL/username discussion again, here are some places we've talked about it on Github:

+ https://github.com/zooniverse/Panoptes/issues/40
+ https://github.com/zooniverse/Panoptes/issues/29
+ https://github.com/zooniverse/Panoptes/issues/8
+ https://github.com/zooniverse/Panoptes-Front-End/issues/197

Unfortunately it looks like most of the talking occurred on HipChat or Hangouts and so is lost to the sands of time. 

I think it's pretty silly to give up having nice URLs people can just type in without having to remember some numbers. I can't think of any website I visit that doesn't have them except HackerNews, and according to @alexbfree they're good for your SEO: https://moz.com/blog/11-best-practices-for-urls but I'm not sure how accurate that is. 

So I'll propose again what I've wanted to do to solve this. A user has two names:

+ `login` alphanumeric with dashes and underscores. 
+ `display_name` literally anything. 

The login is used for the URL fragment and for doing @-mentions. The display_name shows up in their profile, next to posts in Talk, and in places like #503. Users can log in to the Zooniverse with their email, or login, or their display_name, whichever they feel like using. 

Users migrated from old Zooniverse will have their login initially set to a 'sluggified' version of their "ZooniverseHome login". On their first login, they'll be briefly prompted to either confirm that login or to choose a new login. Their display_name will continue being the same as their login from old ZooniverseHome, unless they choose to edit it. 

When a new user registers an account we we only ask for their login and their display_name will initially be set to to be the same as their login. 

Users will be able to edit their display_name at will, but will be strongly discouraged from changing their login. They'll be warned (similar to the github warning Michael posted) that everything will break if they change it. 

This will make everything much much easier than trying to automatically generate URL slugs for users. I think we should decide to do this now, since this is probably the last chance we'll have to make a change like this, so I'm going to ping @brian-c and @camallen for their thoughts as well.

**Comment by edpaget** [comment]
@parrish your slug is 'parrish' now. That change was due to some monkeying about with the user migration script.

**Comment by parrish** [comment]
Awesome - I'm glad we're basically on the same page here.

> So I'll propose again what I've wanted to do to solve this. A user has two names:
>   - login alphanumeric with dashes and underscores.
>   - display_name literally anything.
> The login is used for the URL fragment and for doing @-mentions. The display_name shows up in their profile, next to posts in Talk, and in places like #503.

Agree 100%

> Users can log in to the Zooniverse with their email, or login, or their display_name, whichever they feel like using.

Agree for login and possibly email because they're unique -- display_name isn't

> Users migrated from old Zooniverse will have their login initially set to a 'sluggified' version of their "ZooniverseHome login". On their first login, they'll be briefly prompted to either confirm that login or to choose a new login. Their display_name will continue being the same as their login from old ZooniverseHome, unless they choose to edit it. 

Agree with the caveats:

``` ruby
  login = if valid?(zu.login)
    zu.login
  elsif not_taken?(zu.sanitized_login) # where sanitized_login => login.gsub(INVALID, '')
    zu.sanitized_login
  else
    zu.sluggified_login
  end
```

and

``` ruby
  display_name = zu.display_name || zu.login
```

> When a new user registers an account we we only ask for their login and their display_name will initially be set to to be the same as their login. 

Either way.  We can always test that later too.

> Users will be able to edit their display_name at will, but will be strongly discouraged from changing their login. They'll be warned (similar to the github warning Michael posted) that everything will break if they change it. 

If we even want to bother doing that -- that's a pretty huge number of things to mess with.  I'd recommend punting it and waiting to see if it's requested often enough.

I'll get started on a PR.

**Comment by edpaget** [comment]
> Agree for login and possibly email because they're unique -- display_name isn't

display_names are unique, now, so I'm not sure why would change that if we don't need to. I'd be unfortunate for a user to name themselves Chris Lintott then argue with Chris on talk. We'll also still need to let Zooniverse Home users login with their old names, so the transition isn't too confusing. 

> I'll get started on a PR.

To Panoptes?

**Comment by parrish** [comment]
> display_names are unique, now, so I'm not sure why would change that if we don't need to. I'd be unfortunate for a user to name themselves Chris Lintott then argue with Chris on talk. We'll also still need to let Zooniverse Home users login with their old names, so the transition isn't too confusing. 

Fair point.  Though, we'll still probably have some issues with variants like Chris J Lintott, Dr. Lintott, etc, but I imagine that's really just up to moderators.

> To Panoptes? 

Yep, I'm basically roadblocked until this is resolved.

**Comment by camallen** [comment]
For references, here are some more links from previous discussions:
https://github.com/zooniverse/Panoptes/issues/483#issuecomment-76839428
https://github.com/zooniverse/Panoptes/issues/544#issuecomment-75062414

@edpaget's suggestions look good to me. A login field that restricts the character set sounds good, this will replace the slug field on the user model and will be used for @mentions in talk. I agree @parrish that we don't bother with changing logins unless it's a thing people really want in the future.

**Comment by chrissnyder** [comment]
Am I correct in saying this was solved with the latest user migration?

**Comment by chrislintott** [comment]
@chrissnyder Should this have a First Release tag? It's the only thing open in Talk Beta.

**Comment by chrissnyder** [comment]
Don't know because I don't know what conversation user search refers to. The initial problem was solved and we could close the issue.
