### ISSUE TITLE
workflow test button page broken

### ISSUE THREAD

**Issue by lfortson** [zooniverse/Panoptes-Front-End#5279]
## Expected behavior
Clicked on test workflow at end of workflow set up 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
There was an error retrieving project lucyitswd/cssitest.

undefined is not an object (evaluating 'n.type')

    in t
    in div
    in t
    in styled.div
    in t
 ....

## Steps to replicate

I did not add any tasks to the workflow, but in my defense, I got to the bottom of the screen and the next obvious thing to do (as a newbie) was to click "test workflow"

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Was this fixed by #5280?

**Comment by srallen** [comment]
Sort of. It's disabling the 'test this workflow' button if there are **no** tasks, but doesn't fix the classifier for some kinds of tasks if they are partially setup. For example, if a survey task is added, but has no choices, the test button will be enabled and work, but the loaded classifier will error. This is because we don't have defaults for several expected attributes still. This is I think only an issue for survey task and drawing tasks.

I think for survey task and drawing task we might want to display a more useful error like "No choices setup" or something on the classifier page as well as make improvements to the lab UI, but that's long term.

Perhaps this issue can be closed and a new one be opened for improved error handling for partially setup workflow tasks?

**Comment by eatyourgreens** [comment]
Maybe tasks should have a static validation function that validates the task object against some simple validation rules? Then the editor could check `TaskComponent.isValid(taskDescription)` or similar. The function could return a helpful error message specific to that task if the task is invalid.

**Comment by srallen** [comment]
This would be easier to do with the models we're defining with the MST stores.
