### ISSUE TITLE
Users sent to 'already seen' images before a subject set is finished

### ISSUE THREAD

**Issue by mfidino** [zooniverse/Panoptes-Front-End#5324]
We currently have a single subject set up on Chicago Wildlife Watch with ~32,000 subjects (pictures) attached to our workflow, and tagging is 17% complete. Recently, volunteers [have been getting sent](https://www.zooniverse.org/projects/zooniverse/chicago-wildlife-watch/talk/570/959380?comment=1584316&page=1) to images with an 'already seen' banner instead of other images they have not seen on the subject set.  These are images that the volunteers have tagged within the subject set. 

This may be related to this [issue](https://github.com/zooniverse/Panoptes-Front-End/issues/4435), as they the volunteers who have been receiving this problem do tag lots of images on the site (though we are far from retiring this season of photos).

**Comment by camallen** [comment]
Hi @mfidino - we've added some more information about what a user saw and when to better understand how this issue is happening. 

See
https://github.com/zooniverse/Panoptes/pull/3112
https://github.com/zooniverse/Panoptes-Front-End/pull/5325

Please do encourage the users to report these duplicate subject ids and when they saw them so we can identify the affected users and classifications. Once we have more reports and data on these events we can better debug how our services are behaving.

**Comment by mfidino** [comment]
Will do @camallen. 

We are currently on subject set #72929. The images that have been brought to my attention have the following subject ids:

1. 16305
2. 9850
3. 29068

**Comment by camallen** [comment]
It helps to have the affected user logins / ids as well and if possible when they are seeing the duplicates.

**Comment by mfidino** [comment]
The users are abloss and WillowSkye.

WillowSkye just had the issue with image id 30805856 and 30933815 at around 14:58 CST on 4/11/2019.  They also commented:

'there's a pattern it seems, when I click on Explore Project and then Classify from Talk to return to Classifying, a picture already awaits me with an Already Seen banner. I'm going to refresh the page from Talk and then go back to Classifying to see if that doesn't clear it'

**Comment by mfidino** [comment]
Another user @abloss tagged subject_id 30807474 on June 8, 2019 and then was sent back to the image to tag it again on July 10th 2019 around 3:48 pm.
