### ISSUE TITLE
Tutorials are shared across Projects 

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#5334]
## Expected behavior

I think Tutorials are supposed to be unique to a specific project.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Tutorials are shared across Projects. I made a tutorial in https://www.zooniverse.org/lab/7264/tutorial
and it also shows and is editable in https://www.zooniverse.org/lab/6428/tutorial

## Steps to replicate
See Org. https://lab.zooniverse.org/organizations/16/projects and pages referenced above.

## Additional information
<img width="1260" alt="TutorialGrab" src="https://user-images.githubusercontent.com/2152565/56839338-3d2b7f80-683f-11e9-9734-b8f07b1b5ef8.png">

- **Operating system:**
macOS 10.13.6
- **Browser:**
FireFox 66.0.3

**Comment by srallen** [comment]
Tutorials are linked to workflows (and workflows are linked to projects). They're unique tutorials. I see ids 2349 and 1649 (the ids appear above the display names in the interface). What I don't know is if tutorials are cloned along with projects, which I'm guessing is what happened. So new tutorial, but with the same content. Did you have a project cloned?

**Comment by denslowm** [comment]
I am little unclear on the question, but maybe it helps to know that these projects had no tutorials, I just added them new.

@mcbouslog Do you know if the project was cloned?

**Comment by mcbouslog** [comment]
Neither project 6428 (WeDigFLPlants) nor 7264 (CalBug) was cloned to my knowledge. It appears project 6428's tutorial (id 1649) hasn't been updated since July 25, 2018.

Maybe one got stuck in the browser state when this issue occurred?

@denslowm did you make a unique edit to one tutorial, that was then reflected in the other tutorial? Is it still reflected in both tutorials? If not, that might be worth testing (making a small, temporary unique edit to one tutorial, then checking the other, then if reflected empty cache and refresh one that shouldn't show edit, to see if it still shows).

**Comment by srallen** [comment]
Ok that is my mistake. I thought NfN was going to use project cloning when setting up the new org.

**Comment by denslowm** [comment]
@mcbouslog Good question. I just tried that and the change is not reflected in the other tutorial. I tried both directions.

**Comment by srallen** [comment]
> Maybe one got stuck in the browser state when this issue occurred?

Probably not app state, but more likely the cache in the panoptes javascript client. I wouldn't 100% rule out an invalid app state in the lab, however. It sounds like this would be hard to replicate.
