### ISSUE TITLE
SSL cert misconfigured in docker

### ISSUE THREAD

**Issue by duhaime** [zooniverse/Panoptes-Front-End#5366]
Hi all, I just tried to get started with this codebase using the dockerfile and docker-compose setup you provide, but I'm hitting an SSL invalid error.

I tried grepping around to determine what's meant to install the SSL certs as advertised in the webpack dashboard, but haven't found anything yet. I can tell the browser to accept the risks and proceed anyway, but wanted to record the fact that SSL cert generation doesn't seem to be functioning.

After a fresh clone I tried a `docker-compose build` followed by a `docker-compose run --rm --service-ports dev npm start` (using docker version 18.09.2, build 6247962 and docker-compose version 1.23.2, build 1110ad01).

This builds and runs the container, but doesn't open the browser. Manually navigating to `https://0.0.0.0:3735` throws an SSL error `NET::ERR_CERT_AUTHORITY_INVALID`, and the http protocol returns no data.

It seems unrelated, but, `docker-compose run --rm dev npm run stage` throws a fairly lengthy error too [[full log file](https://gist.github.com/duhaime/dd5953898990af8ac80b2cfb49d76369)].

## Expected behavior
I thought https://0.0.0.0:3735 would serve up the application with ssl certs in place (based on webpack dashboard messaging). 

## Current behavior
https://0.0.0.0:3735 throws an SSL invalid error `NET::ERR_CERT_AUTHORITY_INVALID`.

## Steps to replicate
Install docker versions above, then:
```
git clone https://github.com/zooniverse/Panoptes-Front-End && cd Panoptes-Front-End
docker-compose build
docker-compose run --rm dev npm run stage
open https://localhost:3735
```

## Additional information

- **Operating system:**  OSX 10.13.6 (17G7024)
- **Browser:** recent Chrome, FF, and Safari

**Comment by srallen** [comment]
Here is the webpack documentation about the https setup: https://webpack.js.org/configuration/dev-server/#devserverhttps

We've set it to the simple configuration `https: true` which self signs a certificate. The browser warning is expected because browsers don't trust a self signed certificate, however we know this one is ok since it's just for local development. You can add an exception for the localhost in your browser settings.

Could you open a separate ticket about the docker config? Thanks

**Comment by eatyourgreens** [comment]
The `stage` script builds the HTML, CSS and JS files then copies them to a Zooniverse bucket on S3. Its failing for you because you don’t have write access to our S3 setup. I think there’s a note in the Readme about this, but if not I’ll add one.

If you’d like to deploy to your own S3 bucket, you should be able to edit the `stage` script in `package.json` and change the target.

**Comment by duhaime** [comment]
Ah, thank you both! I didn't see documentation on the AWS config values in the README, but it could be worth noting in case other fools like myself come along. In any event, thank you both for your fast follow-ups.
