### ISSUE TITLE
Make Multi-Answer Workflows able to be Mobile-Friendly

### ISSUE THREAD

**Issue by chelseatroy** [zooniverse/Panoptes-Front-End#5374]
Multi-Answer workflows will shortly be available on mobile! (Pending figuring out the build on the PR). In order for them to show up on the app, we need to make it possible on the front end for multi-answer questions to be labeled mobile-friendly. Currently in the PR I use some hacks to get around this (see projects.js file changes in the following PR):

https://github.com/zooniverse/mobile/pull/258/files#diff-504a093cb0a0dcec9c17dde0dd51873b

**Comment by mcbouslog** [comment]
per Slack/mobile/Will:

This line needs to have `multiple` added as a task type in order for a multiple answer workflow to show up in the project builder. Otherwise, a workflow will immediately be toggled `mobile_friendly: false` to keep the workflow from appearing in the app.

https://github.com/zooniverse/Panoptes-Front-End/blob/f123b8c98c614c4a62e49eba5d74f3867dbbcdfa/app/pages/lab/mobile/mobile-section-container.jsx#L76
