### ISSUE TITLE
'Under Review' tag should be above the title, not next to it

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#5418]
## Expected behavior
At some point the title of the project has moved from below the 'Under review' tag to next to it.

## Current behavior
![image](https://user-images.githubusercontent.com/1392130/60048519-e6e98a00-9691-11e9-9db5-d2a0415e82ac.png)

**Comment by eatyourgreens** [comment]
Have you got a link to that project?

**Comment by eatyourgreens** [comment]
Looks like the problem is here, where 'Under Review' is part of the page heading, before the project title. It should probably be moved out of the H1 element.
https://github.com/zooniverse/Panoptes-Front-End/blob/f17a25b49ad7097b3276f8cb277bc0c328e97df4/app/pages/project/components/ProjectNavbar/components/ProjectTitle/ProjectTitle.jsx#L84-L103

**Comment by beckyrother** [comment]
@eatyourgreens sorry, that screenshot is this one but I've seen it multiple places: https://www.zooniverse.org/projects/trouille/university-of-wyoming-raccoon-project

**Comment by eatyourgreens** [comment]
@beckyrother Thanks! Beta projects are hard to find if you don't know which projects are currently in beta.
