### ISSUE TITLE
Add role label to user avatars in talk

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#553]
- Will probably only show a user's role of highest acclaim to avoid clutter

**Comment by brian-c** [comment]
It'd be cool to have this reused on the project's Science page.

**Comment by mschwamb** [comment]
Also I think owner should have ability to decide what role they want listed on Talk if possible. I'm the owner of P4:Terrains but that's because I started it. the PI of the project is still someone else officially. So my role on Talk would be better as scientist than as owner. I'm not sure if other science teams would feel that way or have similar situations.

**Comment by DarrenMcRoy** [comment]
I think there should be the ability to display multiple roles. Roles are not a strict hierarchy... someone could be a moderator and a translator, for instance. Maybe up to 2 or 3 roles could be displayed?

**Comment by vrooje** [comment]
Probably need some kind of shorthand or icon to take up less space if all roles will be labelled.

I think the opting in/out of visible roles is interesting but I don't want anyone to be an invisible moderator.
