### ISSUE TITLE
Lab: Add 'museum' role checkbox in user roles

### ISSUE THREAD

**Issue by zwolf** [zooniverse/Panoptes-Front-End#5607]
Exhibits in museums are using a new user role to specify certain app behavior in the mobile app. The process to add a user to a project with this role requires using the Rails console to add a new AccessControlList with the 'museum' role. This could be an extra role checkbox in the Collaborators tab to allow it to be set manually by our team and by researchers for testing.

**Comment by shaunanoordin** [comment]
I've added PR #5608 to allow the `museum` role to be listed, but that's waiting on two things:

- confirmation/explanation/justification for the museum role. Do we have an ADR for this, or at least a discussion on why we need it, so I can point my PR to that?
- The Panoptes API adding the museum role.

**Comment by beckyrother** [comment]
Museum mode will need to be enabled for a specific user, so we'll need to note that somewhere. 

copy should be:
Enables a custom interface for the project on the Zooniverse iPad app, specifically designed to be used in a museum or exhibit space. Assign a user to this role to turn on.

**Comment by zwolf** [comment]
There is no Panoptes API requirement for this. There is no restrictions on the contents of the array of strings you send to the `/project_roles/:id`.

This discussion was had a while ago regarding the mobile app and the museum exhibit experience. If there was documentation of such, it might be on the mobile repo.

**Comment by shaunanoordin** [comment]
@beckyrother 👍 Copy has been updated in PR #5608 

@zwolf in regards to...

> There is no Panoptes API requirement for this. There are no restrictions on the contents of the array of strings you send to the /project_roles/:id.

...I'm going to disagree with you. And _also agree with you._

In PR 5608, when I click on the 'Museum' checkbox to add the role to user, I get the following error:

![Screen Shot 2020-01-08 at 17 31 41](https://user-images.githubusercontent.com/13952701/72001475-7543e880-323d-11ea-8a32-f62bad475788.png)

![Screen Shot 2020-01-08 at 17 33 25](https://user-images.githubusercontent.com/13952701/72001485-7c6af680-323d-11ea-9e6c-41453e0c6375.png)

The POST request to `https://talk-staging.zooniverse.org/roles` (wait, talk-staging?) returns a 422 error.

BUT when I reload the page, the GET request from `https://talk-staging.zooniverse.org/roles` DOES show that I've added the `museum` role to `zootester1`

![Screen Shot 2020-01-08 at 17 34 04](https://user-images.githubusercontent.com/13952701/72001628-bdfba180-323d-11ea-9b52-b39523fc2732.png)

So in conclusion: 🤷‍♂ ❓ 😕

**Comment by zwolf** [comment]
I only tested Panoptes, not Talk. A PUT to `/project_roles/:id` with the body
`{ "project_roles": { "roles": [ "expert", "squirrel" ] } }`
will save that role successfully. You are now a squirrel (for that project).

If there's an issue with Talk, then I'd expect it to also complain about the other roles it doesn't know anything about (tester and expert). I don't think that's an error from either API being printed. Talk client, maybe?

**Comment by beckyrother** [comment]
I was maybe confused about where this lives. If it's for a user, the last sentence can be removed. I thought it was to enable museum mode on a project?

**Comment by camallen** [comment]
So talk and panoptes APIs store their own set of roles for terrible historical reasons. In this case panoptes doesn't validate the incoming roles but talk does, hence the error. https://github.com/zooniverse/Talk-Api/blob/c494bd8512e03ce40de33ae9bdd326034cf698ed/app/schemas/role_schema.rb#L26

We can modify talk to accept this role but it makes no sense to have this role for talk due to the behaviour that `museum` is configuring in the mobile app. 

Is it possible to instead avoid the talk POST request on this type of role setting, i.e. only post to panoptes roles end point?

**Comment by shaunanoordin** [comment]
@beckyrother  👍👍 Copy has been re-updated in PR #5608 and now says...

![Screen Shot 2020-01-09 at 16 39 33](https://user-images.githubusercontent.com/13952701/72086347-acc69980-32fe-11ea-8930-29efc43f7054.png)

@camallen @zwolf Righto, changing the Talk API is probably a bad idea, so I've coded in a simple exception (that took longer than usual to figure out because _thanks Coffeescript_ ) on the _front end_ that ensures no 'museum' role is ever transmitted to the Talk API.

However, this does nothing to stop the squirrels that Zach, in his hubris, has unleashed into the Panoptes API. Zach, you fool!!

![mtg-form-of-the-squirrel](https://user-images.githubusercontent.com/13952701/72090835-b3f1a580-3306-11ea-8de6-d9504f65878f.jpeg)
