### ISSUE TITLE
Having a set of default Talk boards and subboards created at project creation

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#570]
From experience most science teams have never really worked with message boards/forums and don't know what they need  for Talk. The current setup still assumes that. As my project still has an empty Talk when I created it. 

 For Planet Four launch, I modeled off of what Rob, Arfon, @chrislintott created for Planet Hunters. I've noticed that some projects don't know that they could create subboards on the New Talk and everything is in the objects subboards. Example Asteroid Zoo: http://talk.asteroidzoo.org/ . Penguin Watch used to be that way, but they've since added a few subboards. 

It would be helpful I think  if Help, Chat, and Science subboards were created by default that are separate than whatever you're doing for objects

**Comment by vrooje** [comment]
Help, Chat and Research

(otherwise I agree, a default set of boards would be useful)

**Comment by mschwamb** [comment]
Help, Chat, and Science were what we've used on other previous - I think we should keep that format for continuity

**Comment by edpaget** [comment]
@mschwamb there are going to be a lot of project's that aren't doing science necessarily like humanities ones.

**Comment by mschwamb** [comment]
good point. how is it handled on non-science projects' Talks currently?

**Comment by eatyourgreens** [comment]
For Science Gossip, we used Research in place of Science on Talk.

This also meant using 'researcher' instead of 'scientist' on the team page.
http://www.sciencegossip.org/#/about/the-team

**Comment by DarrenMcRoy** [comment]
@mschwamb I actually rather strongly oppose any sort of mandated structure of boards, or automatically generated boards. The rigid, inflexible Help/Science/Chat format has been a source of significant frustration for many users, and nobody would be sorry to see it go.

I would support having an option -- an opt-in or opt-out option? -- to have a set of basic boards auto-generated, although I would advise that they be a little more in-depth and better-organized than just "help," "science," and "chat." I've had good results with a basic set that I used for Chimp & See and Science Gossip, including boards like "Questions for the Science Team" and "Technical Support" that avoid everything blending together under "help," or ambiguity about where to post things. I'd be happy to write out that set of boards that would be generated. :-)

Teams should also have the option to customize their Talk from scratch (i.e., not opt for the automatically generated boards), if they feel that they have unique needs.

Thoughts on that?

**Comment by aweiksnar** [comment]
We could have some copy with suggested board titles in the board creation form to get new users up and running

**Comment by DarrenMcRoy** [comment]
I actually like the idea of just clicking a button that instantly generates a basic set of boards, for research teams that don't want to do a ton of work setting up their Talk.

I'd just like it to be a bit more in-depth and not be mandatory.

**Comment by mschwamb** [comment]
@DarrenMcRoy I'm sure it's a frustration for volunteers, but I think giving no guidance to the research teams who have to use them isn't good either. I'm not suggesting this be mandatory, but one thing I've seen on both my projects from both science teams is that Talk has been a source of confusion of knowing how to use it or navigate so giving options so you can see how's it's supposed to work and then being able to opt out of that or change it I think would be very useful.

**Comment by mschwamb** [comment]
Also apologies for not thinking broadly enough re humanities.

**Comment by DarrenMcRoy** [comment]
Well, I don't think anything that I said supports "giving no guidance." :-) Among other things, there's going to be a Best Practices document that should give significant Talk guidance!

But do you agree with the idea of having an option, in the process of creating a new project, to automatically generate a set of boards? I think it should be opt-in. Check a box while creating your Talk, and the basic boards will be generated (that you can then add to or delete from). Don't check it, you set up your boards from scratch. (It reminds me of playing Oregon Trail II as a kid: you could buy a basic recommended set of supplies if you wanted to just get going right away--and then augment it to your liking--or you could buy everything individually. Options are good, right?)

Check out the boards that I created for Science Gossip: http://talk.sciencegossip.org/#/boards (not including the auto-generated "objects" boards, or the "FAQ source" which was created later). That might give an idea of the boards I'd like to generate.

We can also make everything "research" instead of "science," as we have been doing.

**Comment by vrooje** [comment]
I like the idea of presenting owners/collaborators with a choice:

  - I want to create my own boards from scratch
  - Give me a default (editable) set of boards

I think it's worth discussing what those boards should be, and even, perhaps in the future, having a couple of options for pre-packaged board setups. It's at least possible that science projects have a completely different set of standard board needs from humanities.

**Comment by DarrenMcRoy** [comment]
@vrooje +1

**Comment by mschwamb** [comment]
@DarrenMcRoy I'll for options, and agree and my thought was that it would be flexible and there would be opt in or opt out as @vrooje suggests, but in my mind opt-in would be extremely minimal so far less than you made for Science Gossip. I would say 3 starter boards 'Help, Research, Chat', with a subboard in each if that's required to make posts and then let people build from there pointing to examples of Science Gossip and elsewhere that you think work best

**Comment by DarrenMcRoy** [comment]
So, here's the thing about how this new Talk is currently organized:

The current Talk -- current, Ouroboros talk -- has "help," "science," and "chat" as headers under which other boards live, right? They're not really boards and sub-boards, they're just organizers. The boards all exist on one page (http://talk.sciencegossip.org/#/boards), but organized under those three headers.

The new Talk, right now, as you can see (http://demo.zooniverse.org/panoptes-front-end/#/talk) doesn't have those organizers/headers. It doesn't even have sub-boards (neither does the current Talk), although Alex says that the capability exists to build in that functionality, but it doesn't seem to be planned. It just has a list of boards, and then there are discussions within those boards. There's no nesting beyond that right now

So the idea of having a "Help" board, and then sub-boards within "Help" of "Technical Support," "Announcements," etc., doesn't work right now. All boards exist on the same single level. No boards within boards; no headers.

If we have "Help," "Research," and "Chat," then those are going to be either the only boards, or they are going to exist on the same level as any other boards that are created--and then we have specific boards alongside general boards, not within, and that makes no sense. They can't be umbrellas. You can't create a sub-board within Research to pertain to a specific research topic, just a discussion. Two levels: boards and discussions.

If this structure is a concern -- I don't love it, but it seems to be the direction we're going -- then we need to have a larger conversation about that?

And even if you could create a sub-board, that won't be displayed on the front page of Talk, meaning we're sort of hiding the content behind increasing layers of nesting, multiple clicks to get to the actual discussions (which is why I think Alex opted for this system in the first place).

Hence, my suggestion is that if there are only going to be one level of boards, then the auto-generated boards shouldn't be anything that we expect to have more specific boards within them... because right now we don't have that functionality, and I don't know if it's planned. 

Additionally, the specific "help/research/chat" trifecta has led to plenty of confusion and overlap, especially between "help" and "science." For instance, if you have need help with a scientific element of the project, does that go in "help" or "research?" What if it's a bit more casual; does it then go in "chat?" Where do announcements go? Do we need "chat" anyway, for non-project discussion, when we will have Zooniverse Discuss for all things that don't relate to a specific project? The labels are generic, overlapping, and not all-encompassing, and have very often failed to produce any useful degree of organization of discussions; you can find similar threads under all three. They aren't well-liked, either, so I really see no reason to preserve that particular trio.

I personally really think that a new setup is called for with a new system. I'm happy to propose one.

Does this all make sense? @aweiksnar -- am I explaining how the new Talk works properly? @parrish -- is how I described it the intent? @vrooje and @mschwamb -- does that make my concerns clearer at all?

Thanks!!

**Comment by mschwamb** [comment]
I'm not sure I understand. I guess I need to see one set up. I can say, there are definitely non-all Zooniverse non-science specific conversations that happen on my projects -and in your system I'm not sure where they would go. Llike is anyone from Planet Four going to ZooCon? or  introducing yourself on Planet Four - that wouldn't go on the help or science/research type thread and wouldn't go on a Zooniverse wide thread since it's project specific.

There was a whole Talk poling and review which I presume is determining all of of the new Talk design and board structure which I gave my feedback on. Unless asked, I'll refrain from commenting further since my feedback was considered and rolled in without everyone elses when talk design was made.

**Comment by aweiksnar** [comment]
@mschwamb Since project owners can create any board they like, they could make a "Hangout" board or something like that for those disucssions. We're hoping that giving project owners freedom to create their own boards will keep everyone happy without locking them into help/science/the-objects

**Comment by mschwamb** [comment]
@aweiksnar fully agree. My only point is that giving some guidance when building the project I think would be helpful by autogenerating an example set of starter boards and I don't think a new science/research team is going to know what they need or read lengthly documentation so a default starter set of boards if wanted would be a great option.

**Comment by DarrenMcRoy** [comment]
I think we're all in agreement that would be a good idea in the long run. I've marked it as a future plan.

**Comment by aweiksnar** [comment]
@mschwamb Okay cool, Yeah I need to make some improvements to the talk 'empty state' and will absolutely keep that input in mind when doing so

**Comment by mschwamb** [comment]
Documentation does enough likely at this point for my concerns
