### ISSUE TITLE
Enable croatian ("cr : Hrvatski") on PFE

### ISSUE THREAD

**Issue by sandorkruk** [zooniverse/Panoptes-Front-End#5703]
Hi, 

Can someone please enable the Croatian language on the list of languages supported by PFE?
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/constants/languageMenu.js

We have a new croatian translation of PROJECT #10969, but cannot enable it in the lab.

Thank you,
Sandor

**Comment by lcjohnso** [comment]
Happy to help, @sandorkruk. Do you know a translator who would be willing to translate the shared Zooniverse platform content? By default, the new locale file will lead to English being used by default for cases where translated content doesn’t exist.

**Comment by sandorkruk** [comment]
I know someone who translated the project in croatian. Is there an easy way to translate the Zooniverse platform content?

**Comment by lcjohnso** [comment]
@sandorkruk -- There's three different approaches / levels of complexity to how one can submit the platform translations:
1. Submit a PR directly to PFE repo where English content is replaced with Croatian in [hr.js](https://github.com/zooniverse/Panoptes-Front-End/blob/add-locale-hr/app/locales/hr.js) file.
2. Same as 1, but you or I can send the hr.js file via email and support the translator by submitting the PR for them.
3. I'm currently working with another team to produce and use spreadsheets to help better manage and organize the material (easier than editing the JSON-styled *.js file directly).  Basically, I'm writing a little input/output formatting script to support that.  Should be easier, and happy to use that here to assist (since I'm already writing the script).

Let me know how you'd like to proceed.  I can get in touch with the translator directly, or happy for you to manage the back and forth + questions.

**Comment by sandorkruk** [comment]
I can ask the person who translated the project in croatian. She was willing to translate the menu and the simple things on the front page, but looking at the file it looks like there is quite a lot of text in fact (if this is all of it - https://github.com/zooniverse/Panoptes-Front-End/blob/add-locale-hr/app/locales/hr.js). I will enquire and get back to you.

**Comment by eatyourgreens** [comment]
It isn’t necessary to translate it all. That file includes things like the full text of the About pages. You can probably ignore those.

**Comment by lcjohnso** [comment]
Agree with @eatyourgreens, echoing what I said in my Slack DM: "Not all of the content needs to be translated: the bios, privacy + security content, even about page content can be skipped / left in English. As an example, take a look at the French version (fr.js in same dir). Really it is up to her what she’s willing to do."

**Comment by eatyourgreens** [comment]
Here's some advice I wrote for Chimp & See, when they added a German translation. https://github.com/zooniverse/Panoptes-Front-End/issues/5452#issuecomment-510798654

**Comment by lcjohnso** [comment]
@eatyourgreens -- Thanks for the link to that comment.  It sounds like in both cases I'm working with (Sandor here + Wildcam Gorongosa team via Meredith Palmer) that editing via Github is not tenable for translator.  I'm working on a simple input/output python script that will provide translators a spreadsheet-based solution for providing translated content.  Will update on that progress when complete.

@sandorkruk -- Although this initial issue is closed, we can keep the conversation going here for now re: translating content.  Let me know what you find out!
