### ISSUE TITLE
Subjects from other project talks are showing up on Planet Four

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#5710]
The moderators for Planet Four have spotted that there are an increasing number of Talk notes showing up with images that aren't Mars. Here's an example:

<img width="1262" alt="Screen Shot 2020-05-06 at 7 40 34 PM" src="https://user-images.githubusercontent.com/753325/81215854-dc965d00-8fd1-11ea-9aa5-e7a23f5b1858.png">

<img width="1233" alt="Screen Shot 2020-05-06 at 7 52 15 PM" src="https://user-images.githubusercontent.com/753325/81216639-26337780-8fd3-11ea-871d-5d12f56e925e.png">

**Comment by srallen** [comment]
The issue is that subject ids from the url do not get validated for the project context it is in. For example, any subject Talk page can be loaded from any project context: https://www.zooniverse.org/projects/mschwamb/planet-four/talk/subjects/100

What's likely happening is that this volunteer is browsing subjects' Talk pages (possibly loading them directly, maybe incrementing the number at the end of the URL) in the Planet Four Talk context and then leaving comments which creates a threaded discussion on the Notes board for Planet Four. 

The fix would be to validate the subject id belongs to the project, but there might be impacts to projects in organizations that actually DO want to do this and have cross-project Talk threads? We'll have to check what the consequence of doing this would be.

**Comment by mschwamb** [comment]
It's multiple volunteers doing this, so I'm surprised to several of them are doing this on the same day.

**Comment by mschwamb** [comment]
<img width="1257" alt="Screen Shot 2020-05-06 at 8 26 53 PM" src="https://user-images.githubusercontent.com/753325/81219649-fc308400-8fd7-11ea-9d49-d576ef3e692f.png">

A different volunteer doing the same thing, in case that helps with tracking down the issue

**Comment by mschwamb** [comment]
Looks like it's a same small group of people, so I'm guess a class and the students are chatting in a small group on the side and manually updating the subject ID based on what their friend is doing and commenting

**Comment by srallen** [comment]
@mschwamb I'm going to do a bit of investigation to try to fully rule out an unexpected bug scenario for this, but I think it's likely that these volunteers are explicitly loading up these subjects and commenting on them. We do have a few projects that share subjects, so cross-project Talk mentions and threads are desired in those cases. I'm not sure what the solution is that will make everyone happy.

**Comment by mschwamb** [comment]
It's more then we have galaxy images showing in the talk preview on the main page and in the notes lists. It freaked out the moderators, and I got messages that the site was having issues. 

Maybe the ability for the moderators to hide the promotion of the subject content if it doesn't belong to the project explicitly (in a later version of Talk if there is ever an upgrade planned)

**Comment by srallen** [comment]
Ah, ok. I think we can at least restrict what shows up on the home page as belonging to the project? We'll have to double check how this might impact the few projects that do share subjects, but I think this is doable.

As far as the debugging attempt, I did spend some time Friday trying to figure out if there was any other way this might've happened and did not find any unexpected bugs. I think the guess of this being a classroom group manually loading up the subject Talk pages is the most likely scenario still.

**Comment by mschwamb** [comment]
Usually if a project shares subjects someone on the team is related to both projects I would imagine. Maybe that would be a way to prevent this from happening or from showing on the landing page of the project.
