### ISSUE TITLE
Subject notes show up in two projects

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#5796]
## Expected behavior
Subject notes only show up in active projects?

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Subjects were copied via 'panoptes workflow add-subject-sets' from one project to another.

Subject "Notes" for these subjects are also showing up in the previous project (decommissioned now) if the subject was commented on there previously. This means that we have Notes going into two different places. I assume that this is not desired behavior.

Examples:

new subject: https://www.zooniverse.org/projects/md68135/notes-from-nature-herbarium/talk/subjects/32458953

new talk thread: https://www.zooniverse.org/projects/md68135/notes-from-nature-herbarium/talk/2798/1591110

old subject: https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/subjects/32458953

old talk thread: https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/484/1078078

## Steps to replicate
It might require access to those specific workflows in order to replicate?

## Additional information
- **Operating system:**
- **Browser:**
It doesn't seem to be OS or browsers specific, but I a using Mac 10.15.6 with Chrome 85.0.4183.83 and Firefox 80.0

**Comment by srallen** [comment]
@denslowm Since it is the same subject id, I believe that means this subject is linked to both projects and workflows and is being reused. Talk has no concept of a subject's retirement state or a project's completeness state, nor do we have any kind of thread merging feature. The original Talk subject notes page remains linked to the original project and users are free to comment there. The other project's subjects notes board is linked to its project, and thus comments are linked to that board and users are free to comment there as well.

Please correct me if I'm wrong: the expected function is some kind of thread merging feature?

**Comment by denslowm** [comment]
Thanks for the explanation @srallen !

Now that I think about it some more, thread merging seems like the best option. Alternatively, Talk knowing a project's completeness state and acting accordingly might also work. It seems that a thread does get made in the active Project, so perhaps this is a lower priority than I initially thought.

I'll let you decide, but I am OK with you closing this if it seems best at this point.

**Comment by denslowm** [comment]
Again, not really sure how big of an issue this is at this point, but in the interest of documenting this issue I noticed another relevant thing. 

If a user presses Done&Talk and the URL is https://www.zooniverse.org/projects/md68135/notes-from-nature-herbarium/talk/subjects/21481802 they get a URL with the "new" project name and no pre-existing comments. I think that is what we expected based on the conversation above.

However, if they "favorite" this same Subject (either from Classify before submitting, or from Talk after pressing Done&Talk), and open it on my Favorites page, it goes to https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/subjects/21481802 This is the "old" project and a comment from June 2018. 

To me one issue is that from your Favorites page (https://www.zooniverse.org/favorites/md68135) you get directed back to the old project which is no longer active.

**Comment by eatyourgreens** [comment]
The favouriting behaviour sounds like https://github.com/zooniverse/Panoptes-Front-End/issues/5368 so I've re-opened that issue.

**Comment by srallen** [comment]
> Now that I think about it some more, thread merging seems like the best option. Alternatively, Talk knowing a project's completeness state and acting accordingly might also work. It seems that a thread does get made in the active Project, so perhaps this is a lower priority than I initially thought.

We've had interest from other projects for some kind of thread merging feature that mods or project owners and collaborators could do, but unfortunately enhancing Talk is not on our roadmap at the moment and would require funding. 

Since we have another open github issue for the other item you've reported, I'll be closing this one. Thanks!
