### ISSUE TITLE
Need basic contact page

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes-Front-End#592]
Pinging @DarrenMcRoy for the copy.

Nothing fancy necessary. Bit of verbiage saying if somebody wants to work with us, has a project proposal/idea, etc. Can use a Google Form with fields name, email, institution, and comment box.

**Comment by DarrenMcRoy** [comment]
Who/what email should the form feed to?

**Comment by DarrenMcRoy** [comment]
A draft is available in the Zooniverse Copy document: https://docs.google.com/document/d/13sP5U4JRmewpJsNRoSfKt54KvYhiKcxzw3f5kyrUzAA/edit (under "Contact & Social Media.")

Haven't created the form yet; will do after talking with Grant.

I did confirm with the Adler that they are okay with me being the stateside Zooniverse press contact, so as long as nobody else has any issues with that, that's in there now, too, to take some of the load/onus off of Chris L.

**Comment by srallen** [comment]
Reassigned back to @DarrenMcRoy for form content. Contact page component is ready aside from form link at 148094669286baf0ec7f1acc4cd141165bf88108

**Comment by chrislintott** [comment]
Copy is fine with me.

**Comment by DarrenMcRoy** [comment]
The form is now live and accepting responses: https://docs.google.com/a/zooniverse.org/forms/d/1NCx8V_XPQMwtY4oPu_sq47cOfPTQX0F7FLffg6KaMek/viewform

I've set it up so that I get a notification any time anyone submits a form.

Ran it past @chrissnyder, but if anyone else wants to weigh in, feel free... could still be changed.
