### ISSUE TITLE
Drawing subtasks not selectable

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#5979]
## Expected behavior
A drawing task with 3 user questions about what they’ve just drawn.

## Current behavior
I made the task with the 3 questions, but it is not selectable when I try to preview. See task 21 here:
https://www.zooniverse.org/lab/16337/workflows/18964

## Steps to replicate
The workflow can be tested/previewed at the link above.

## Additional information
- **Operating system:**
macOS 10.15.7
 
- **Browser:**
Same behavior on:
Firefox 89.0.2 
and 
Chrome Version 91.0.4472.114

**Comment by mcbouslog** [comment]
I think this is happening because [this line of code](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/dropdown/index.jsx#L147), where the `select` per translations doesn't include the option `value`s that are included in the raw task data, it only includes the `label`s. To be continued...
