### ISSUE TITLE
Invalid email - form-help.error

### ISSUE THREAD

**Issue by mbiesiad** [zooniverse/Panoptes-Front-End#6232]
## Expected behavior
Regex checks email form earlier or the feedback is prepared in better way.

## Current behavior
When user try to register with invalid email, will see `[object Object]`

## Steps to replicate
1. Go to: https://www.zooniverse.org/
2. Click on Register
3. Fill the Required fields (but email as in incorrect form) and click Register button

## Additional information
Screenshot:
![image](https://user-images.githubusercontent.com/18367606/198880447-5c8bcd60-aca2-4f9e-be94-e85f05bcbe09.png)

Best wishes,

**Comment by lcjohnso** [comment]
I was able to replicate this issue -- `[object Object]` in red text appears.  See associated console errors below.

<img width="1298" alt="Screen Shot 2022-11-02 at 10 52 20 AM" src="https://user-images.githubusercontent.com/2006101/199537896-59f8f7a0-8e2a-47f2-a95a-c66bdeb822a8.png">

Unlike #6234, this issue is not resolved by merged-but-not-deployed changes (PFE staging on 1 Nov 2022).

**Comment by eatyourgreens** [comment]
This will be fixed by https://github.com/zooniverse/panoptes-javascript-client/pull/164.

**Comment by eatyourgreens** [comment]
Closed by #6237.

**Comment by eatyourgreens** [comment]
Fixed now on staging. 
https://master.pfe-preview.zooniverse.org/

![Registration form on a phone, showing: Error: email is invalid.](https://user-images.githubusercontent.com/59547/199699301-818cd67f-c227-47fc-bf8d-83324014bbef.jpeg)
