### ISSUE TITLE
View/display the number of classifications you've made?

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#633]
Hello,

Is it possible for a user to see how many classifications they have made in a project?

If not, might this be possible - or is there a good reason not to do this?

Thanks, Tom

**Comment by edpaget** [comment]
We're planning to have something like this available https://www.zooniverse.org/projects/current

**Comment by camallen** [comment]
The total should be on the API projects resource response along with the retired subjects count.

**Comment by twhyntie** [comment]
@edpaget Cool - that'd be ideal. I'm guessing post-launch releases?

@camallen Thanks - is there a trivial way for end-users to see their individual total via the front end?

**Comment by edpaget** [comment]
@twhyntie there's an easy to use endpoint to getting that info, but not for individuals to see their classifications at the moment. 

`GET /project_preferences?user_id={id}&project_id={id}` will give you your classification count for a project.

**Comment by twhyntie** [comment]
@edpaget Thanks. Stoopid question, then - will

http://preview.zooniverse.org/panoptes/#/project_preferences?user_id=twhyntie&project_id=20

or similar give me the number? i.e. is there a way of doing via a URL?

**Comment by edpaget** [comment]
No that URL is just for the API. You could access it in the following way

```bash
curl -H "Accept: application/vnd.api+json; version=1" \
-H "Authorization: Bearer {your token}" \
"https://panoptes.zooniverse.org/api/project_preferences?user_id=607888&project_id=20"
```

But retrieving your token is a bit of process. 

We are planning to let users see their counts as soon as possible after launch.

**Comment by chrissnyder** [comment]
I couldn't see another issue explicitly discussing for this.

"Minimum-viable" functionality in my book:

- List of projects a user has contributed to
- Number of classifications contributed to those projects
- Bit of UI to make it tidy, like the old profile page.

**Comment by twhyntie** [comment]
@chrissnyder Sounds good to me :+1: :-)

**Comment by aliburchard** [comment]
For Number of classifications -- should we display both total classifications across all projects per-project classifications? or just the latter?

**Comment by twhyntie** [comment]
@aliburchard If I had to choose, just the latter. Both would be good though :-)

**Comment by edpaget** [comment]
We're just going to be showing the latter for the moment.

**Comment by vrooje** [comment]
I think this is related: people are really, really keen to be able to see their by-project and total classification counts, *and* their project ribbons, somewhere.

**Comment by camallen** [comment]
Some of this data has been migrated, some is actively coming in and i'm re-doing the migration soon. 

I think a page that summarizes the User's ProjectPreference activity counts via [here](http://docs.panoptes.apiary.io/#reference/projectpreference/projectpreference-collection/list-all-projectpreferences) could easily show a message saying please contact us if your data is missing.

**Comment by brian-c** [comment]
I've got a ribbon ready for the profile settings page as a toggle for whether or not to show it:

> <img width="382" alt="screen shot 2015-07-08 at 11 06 40 am" src="https://cloud.githubusercontent.com/assets/464389/8567967/a9533cd6-2561-11e5-90f6-85315b5b8690.png">

Is it safe to say we'll have this publicly available soon? If not I can remove the checkbox, but then it's kinda weird to have it on the settings page and there isn't really a place for it right now.

**Comment by camallen** [comment]
@brian-c i don't think we've got plans to make that data publicly available anytime soon.

**Comment by vrooje** [comment]
Not the data or number of classifications, but publicly displaying a colour ribbon below the avatar on Talk?

**Comment by camallen** [comment]
Ok - so you'd have to save the ribbon as an image instead of regenerating it from data. 

We can make activity count data public if the user wants to but it's not a priority.

**Comment by DarrenMcRoy** [comment]
Just want to hop in to say that I'm 100% with @chrissnyder on what we need from a page. Sooner is really better than later on this as I am fielding a few questions per day on what happened to one's project page.

Also, with the ribbon, is there any way that it could be tool-tipped to show what each section means (i.e., mouse over one part and it say "Galaxy Zoo?" Maybe even: "Galaxy Zoo: 27% of classifications?" Otherwise the colors threaten to be kind of meaningless after a certain point, especially if the # of projects starts to get up there to the point where one project's color sort of looks like the next's. I believe that the old Projects page had this functionality.

In the long run, I'd like the ability to display numbers if a user wants.

**Comment by brian-c** [comment]
A private ribbon is built and on its way, with project name and classification count on hover. I'll add percent of total as well.

I'm currently sidetracked reworking user profiles, which is where it'll live.

Sounds like public ribbons will come a bit later.

**Comment by DarrenMcRoy** [comment]
Private is definitely the priority; good to hear it's in progress. Thanks!!

**Comment by yshish** [comment]
Please, may I ask you for making some minimum colour line for each project to be visible on the ribbon (no matter what percentage it is in comparison to other projects)? Most of the projects I've participated in didn't appear on my old ribbon since I was too active in a single project. Even after classifying more than 300 classifications in another one, it wasn't much enough to have it displayed there. Here is an [example](https://lh3.googleusercontent.com/-z_QP6LLEJGA/VZ2UPkxhXSI/AAAAAAAAIF4/_dz3d_qRFdo/s0/ysh_2015-06-21.jpg) only 7 colours visible after activity in 15 projects.

**Comment by yshish** [comment]
#1028
