### ISSUE TITLE
Drawing shapes accumulate over a workflow

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#645]
Perhaps this was requested by someone, but I'm noticing now that when I have multiple drawing tasks in a workflow, the shapes drawn in one question remain when I go to the next question. While I can see that this might be useful in some cases, for my project, it means an overly cluttered display. I purposefully separated out drawing tasks into multiple questions so that the many shapes that someone might draw wouldn't get too confusing.

**Comment by chrissnyder** [comment]
Interesting in that http://www.zooniverse.org/#/projects/twhyntie/monopole-quest/classify works better with all marks still being visible.

**Comment by twhyntie** [comment]
@chrissnyder Yes, we thought this was intentional and it does work quite nicely in this case. To be fair, though, we designed the workflow once we realised the markings built up. An alternative we considered was having the two inner and out circle markers tools available in the same task, but this got fiddly pretty quickly (particularly as it involved overlapping shapes).

I guess an option on the tool for something like "keep these markings on the subject between tasks" might help - what do you think @mkosmala?

**Comment by mkosmala** [comment]
@twhyntie Yes. Having the option to go either way would work great. I can see why it's useful in some cases and not in others. (We built our workflow on an older version of Panoptes where the markings didn't accumulate.)

**Comment by eatyourgreens** [comment]
Closing this because drawn marks are intended to persist across all workflow tasks.
