### ISSUE TITLE
Drawing tasks don't work well on mobile devices

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#646]
In the Season Spotter beta (see #443), we had a lot of feedback about how hard the drawing tools were to use on mobile devices. Specific comments, summarized:
- Didn’t render correctly on mobile Firefox
- Drawing tool didn’t work on Safari on iPad
- Difficult to draw shapes, both ovals and polygons, on iPad
- Drawing the outline of trees are very difficult on a tablet
- Didn’t work on mobile
- Would be easier to “paint” the lines when using a non-touch screen with mouse

Just now, trying it on my iPad, I note:
- For the ellipse tool: It's hard to grab the ellipse handles to reshape. Often I end up drawing a new ellipse instead of reshaping. Likewise, it's hard to hit the little "X" to delete the shape. I expect that these complaints are universal across shape types, but this should be tested.

Note that these comments are from several weeks ago. Trying it out on my iPad (Safari) now, and I seem to be able to use the ellipse, point, and polygon tool.

**Comment by DarrenMcRoy** [comment]
I would like to recommend that we test as many things as possible on mobile devices and tablets. It has been a definite concern for our users. :-)

**Comment by itsravenous** [comment]
Suggestion for deleting/moving/selecting objects for reshaping on touch devices: long press on bbox/inner area? This is a fairly common behaviour across platforms ("hold down on this thing to select it").

**Comment by khufkens** [comment]
I fear Jungle Rhythms would only work with a (fine) stylus on 'touch' devices because of the fine nature of the marks at times. This has less to do with the interface. It's dictated by the blunt nature of fingers and some styli. I fear for some tasks even the most mobile friendly approach won't be accurate enough.

**Comment by aliburchard** [comment]
I really like @itsravenous's suggestion for selecting markings -- even if it doesn't address the really fine-scale needs of JungleRhythms

**Comment by mschwamb** [comment]
@khufkens you've got browser information in the raw classification csv dump so you can check this if you're worried.

**Comment by khufkens** [comment]
@mschwamb thanks for the tip. I might use this as a filter should it prove to decrease accuracy.

**Comment by mschwamb** [comment]
@khufkens We have the same issue on Planet Four in terms of its just harder to draw the marker because fingers are bigger and there is less fine control on a tablet. The interface works great on mobile,just the nature of then task. We never found it a huge issue in the data reduction as we combined with the other classifications. The  current Planet Four classification clustering results I reviewed today looked pretty good and we don't separate out mobile classifications from desktop so I think overall you won't have to worry about this, but  you can definitely filter with the browser info/operating system info.

**Comment by khufkens** [comment]
@mschwamb I just downloaded the full dataset. I'll have a look at the results next week or so. I need to do some reporting on user stats anyway.

**Comment by simoneduca** [comment]
This should be superseded once the mobile app is in place. Pinging @robinschaaf but closing for now.
