### ISSUE TITLE
Hard to draw adjacent polygons

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#648]
We had feedback from our Season Spotter beta (see #443) that it's hard to draw adjacent polygons. This is because the user ends up selecting the original shape when trying to draw a new one next to it. Not sure there's an easy fix. Would welcome ideas.

**Comment by aliburchard** [comment]
Should note this isn't just related to polygons (though the multi-click nature of polygons makes them the most problematic). You can't, for example, mark a point over a rectangle, because clicking over the rectangle highlights the rectangle instead of creating a new point (if these tools are in the same task).

**Comment by camallen** [comment]
Sounds like the hide old marks issue again.

**Comment by chrissnyder** [comment]
Hiding old marks does solve it, as long as the volunteer clicks it before they try to make the new mark.

Do we think this is sufficient to solve this problem?

Alternative solutions?

- Only allow teams to ask for one type of mark per task
- "Freeze" all other marks when in the middle of creating a new mark.

**Comment by mkosmala** [comment]
Hiding old marks works for me. 

"Only allow teams to ask for one type of mark per task" doesn't work because we ask, e.g., for them to mark the outline of trees. If two trees are next to each other, it's the same marking tool, just two different marks. 

Freezing works so-so. If the user starts the second shape near the first one, it will be unclear to the GUI whether the user wants to make a new shape or select the old one. This would require the user to start the shape elsewhere. Not terrible, but not very user-friendly, either.

**Comment by alexbfree** [comment]
Just adding a couple of other alternative solutions:
1) have a "hide all other shapes" toggle button so that people can temporarily hide other shapes if they are "in the way"
2) allow vector shapes to be selected by their edges (like in Powerpoint, Illustrator etc) rather than by clicking on the contained area....

**Comment by eatyourgreens** [comment]
Closing this because "Hide previous marks" is an option now for projects.
