### ISSUE TITLE
Projects page 2 shows only 4 across max

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#658]
The first page of projects shows 5 across:

![screen shot 2015-06-22 at 4 23 39 pm](https://cloud.githubusercontent.com/assets/8987864/8293454/20f17c94-18fb-11e5-9aeb-5b0740c9961a.png)

The second page, just 4:

![screen shot 2015-06-22 at 4 23 49 pm](https://cloud.githubusercontent.com/assets/8987864/8293461/295729b0-18fb-11e5-9d40-c25c147394ff.png)

A little awkward... ?

**Comment by srallen** [comment]
I'm not seeing this anymore. @DarrenMcRoy is this is still an issue for you?

**Comment by chrissnyder** [comment]
Pretty sure this was fixed with https://github.com/zooniverse/Panoptes-Front-End/pull/823

**Comment by DarrenMcRoy** [comment]
This was fixed, yeah.

**Comment by DarrenMcRoy** [comment]
This has just reappeared with the live page. Something happen with #823 --?

**Comment by brian-c** [comment]
Just deployed.

**Comment by brian-c** [comment]
Whoops, latest deploy actually breaks this again.

**Comment by srallen** [comment]
It looks like a height constraint needs to be set for the columns to fill 5: https://css-tricks.com/almanac/properties/c/column-fill/

But I don't think this is a desirable solution since the number of projects shown is going to be variable especially once the filters are in place and working and this wouldn't be great for responsiveness.

**Comment by brian-c** [comment]
Maybe columns aren't the way to go here. Flexbox to the rescue?

**Comment by srallen** [comment]
:+1: Feel free to assign the ticket to me if you'd like me to work on it.

**Comment by brian-c** [comment]
Thanks @srallen.
