### ISSUE TITLE
Subject page discussion threads burrying any message board generated thread

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#660]
not sure if Talk design is done yet or if this will be addressed in the future, but I thought I'd point this out in case it's helpful. With the P4: Terrains beta test you can see that the subject page generated discussion threads are dominating over any threads  that's written in the message boards to the point where it's difficult to find something that is supposed to be a more general detailed conversation because it's 3 pages back because of the new subject related threads generated.

**Comment by aweiksnar** [comment]
@DarrenMcRoy Are there any way's you've seen people handle this nicely through board organization, perhaps in the forum-style talks?

**Comment by mschwamb** [comment]
I thought the way the current Talk 2.0  handled this nicely by having the objects subboard so that those discussions are accessible but not overtaking the rest of the boards generated threads. The original problem in Talk 1.0 was that these conversations were never in a single stream so you'd lose them if you didn't catch them in the recents list so I liked having the objects subboard because this side discussions were there but as they are something different were treated differently such that if there was a spike in user activity say due to press release or newsletter it didn't overwhelm or loose the detailed dedicated discussions people were already having.

**Comment by DarrenMcRoy** [comment]
I get where @mschwamb is coming from... the problem with "The Objects" was always that it was the *only* way to have any sort of in-depth discussion about a particular object. You couldn't start a thread anywhere else about a specific object, and have that object appear alongside the thread, which was a frequent use-case frustration. (It was also a very confusing name, plus, you could start "ordinary" discussions in The Objects as well.) That's not a problem anymore, since you can always start a discussion (or even make a post) about any specific featured object, right?

However, what we've also done now is to eliminate the 140-character-style comment area, where people would normally leave quick comments and hashtags. I think this is the real cause of the problem... now, without that option, users are starting all-new subject-page-generated (SPG) discussion threads about objects just in order to leave quick comments and hashtags, and those discussions are flooding the single stream of threads on each board.

I had a feeling that this was going to be a problem when we eliminated the quick-comment area, and, unfortunately, I'm not entirely sure what we can do about it... Could definitely use @parrish input.

Perhaps we could make some boards "protected" from SPG threads? That way, if there's a place that you want to preserve for general discussion, you could remove it from the list of places where a user can start a SPG thread? And if, like Meg, you want to stick all such threads in one place, you can just protect all other boards?

To answer your question, Alex, there's no real parallel with the forums, because the forums don't have a way to generate threads from a subject page... they don't even have subject pages... so we're sort of tracking fresh snow here.

**Comment by parrish** [comment]
I don't know that I have a definitive answer, so I'll just bullet point a list of opinions I have here.

Things we shouldn't do:

- object comments shouldn't create a new discussion every time (that's what it's doing now) -- it's far too noisy
- object comments shouldn't be isolated in some non-board discussion -- discoverability is too low
- new discussions shouldn't be forced into some "The Objects" board.  It felt (organizationally) weird a lot of the time
- sort of tangential, but let's also get away from this weird hangup we've had with help/science/chat.  Every discussion/board should be some combination of those three things -- let's try to embrace that.

Things we should do:

- have some dedicated place to view all object comments -- it's easy enough to [filter to subject comments](https://talk.zooniverse.org/comments?section=project-17&focus_type=Subject), though it looks like the front end isn't setting that field correctly at the moment.  Fixed in zooniverse/Panoptes-Front-End#682.
- be able to join an existing discussion about a subject easily -- currently, the discussions about a subject would have to be clicked on to know the title/board/etc.  That information should probably be on the subject page
- be able to leave a comment without breaking the organizational scheme. e.g. leaving a comment of "cool" shouldn't need to create a new discussion.

So yeah, it's kind of a fine line between discoverability and noise.

I kind of like the idea of having a default, user-specifiable board that comments go into by default, with one discussion per subject -- though that feels like maybe I'm just repeating what I've built before.

I'm certainly open to suggestions on this one.

**Comment by mschwamb** [comment]
I like the 'I kind of like the idea of having a default, user-specifiable board that comments go into by default, with one discussion per subject -- though that feels like maybe I'm just repeating what I've built before.' Might be taking from what's already built, but I don't necessarily think that's a bad thing. This would also avoid some confusion that the 'object' subboard had. I noticed sometimes new people were concerned what board to put their message.

I agree some of this is the removal of the 140 character comments, but if there's a very active super users writing side discussions for every piece of extra information like on Planet Hunters then the same effect will happen as well, I think.

I think it's worth pointing out that most science team checks talk maybe one every few days. I know I'm the rarity in checking three times a day and even then I found it abit overwhelming to try and find my bug thread in with all the help discussions in the beta. Projects with very active volunteers who make side conversations and in this current design when there are huge spikes in traffic that list will be hard to go through, so having a place where you can go back and take a look at them while also being able to be alerted to things like the site is out of data (usually someone would post in the dedicated Help thread rather in a subject discussion/comment) would be helpful from a science team perspective. 

I guess related to the  'noise'  which might help I noticed from the P4 beta that 
many people were confused on commented on this image with the same kinds of comments but none of them know about eachother when the post. 

http://preview.zooniverse.org/panoptes/#/projects/mschwamb/planet-four-terrains/talk/8/80
http://preview.zooniverse.org/panoptes/#/projects/mschwamb/planet-four-terrains/talk/8/39
http://preview.zooniverse.org/panoptes/#/projects/mschwamb/planet-four-terrains/talk/10/38

So part of the solution might be dealing with that but I'd see vote to whatever solution include having at least the shorter subject side discussions go into a dedicated board.

**Comment by DarrenMcRoy** [comment]
I agree with pretty much everything that @parrish wrote, and most of what @mschwamb wrote as well. It seems like we at least have a universal agreement that the status quo for this is untenable, which is a good place to start from. :-)

I have the vaguest idea of a suggestion... Going to write it up once I get into the office today. Give me a few hours. Just wanted to get it out there ASAP that I think it's good that we're on the same page here!

**Comment by eatyourgreens** [comment]
+1 for what @parrish said. Wellcome would appreciate a comment stream (or similar) for each page of text in their project, along the same lines as Operation War Diary, to catch things that aren't directly addressed by the annotation tasks. I'm not sure if they need full commenting, or just the ability to hashtag a page without generating a new discussion.

**Comment by DarrenMcRoy** [comment]
Okay, so here's my proposal. I don't know how much of it is feasible, but it aligns well with what was said above...

So, exactly like @parrish said, we have "a default... board that [object] comments go into by default, with one discussion per subject." Just one board, not three.

Each discussion only starts when someone posts the first comment about that object.

That board is locked from any other discussions being started in it. It will only have discussions about specific subject pages.

Then--this is the tricky part--we find a way to embed that thread on the subject page, allowing for people to leave quick comments into that discussion without leaving the subject page. This way, we maintain the quick-comment flow of the current 140-character system, while still placing all discussions, great and small, within the context of the same boards.

And then--also critical--we still leave the option to, from the subject page, start a new discussion anywhere else about the object. (Basically, that button starts a new thread in a place of the user's choosing, using the object as the featured image.)

Somewhere on the subject page, you see a list of all the places where that object has been mentioned and/or used as a featured image.

The effect of this is:

- there's an obvious place for quick comments and hashtags, and most such things will be put right there
- you can see and contribute to the stream of basic discussion without leaving the subject page, as it is now
- quick comments and tags don't clog up the general-discussion boards
- but the quick comments and tag comments are still integrated into the same overall board system, and can be seen from the boards as well as from the subject page (and are thus searchable through the same search)
- if you want to start a greater discussion using an object as your starting point, you can, and it's obvious how to do that; you're not locked into just the single stream
- it's easy to quickly see the all discussion taking place about a single object on said object's subject page
- the board with all the basic object comments doesn't have any other threads/discussions in it to be confusing.

This actually works much like the system we have, with the most obvious flaws/annoyances ironed out. So even though this is indeed similar to what Michael built before, it's tweaked just enough to make it workable.

If, that is, I'm not overlooking obvious flaws, or if this is even a feasible design. Thoughts? @parrish @mschwamb @eatyourgreens @aweiksnar and anyone else?

**Comment by aweiksnar** [comment]
For first release perhaps I'll add a line of text encouraging users to join existing discussions about subjects in favor of creating new ones, since they have those links handy. Right now the messaging isn't clear that those existing comments all link to their discussions. 

But yeah @DarrenMcRoy I'm up for testing out the system you proposed for quick object comments

**Comment by mschwamb** [comment]
I think  having some of these features would at least be a help towards fixing this issue. There still needs to be a mechanism to generate a conversation that's separate from these short comments/ proxy for the 140 character comments which it sounds like there will be. 

Another quick help would be if featuring or pinning discussions can be implemented so that if there is a push in discussions, mods could pin an important thread to the top. Not sure how feasible that is for launch

**Comment by DarrenMcRoy** [comment]
> There still needs to be a mechanism to generate a conversation that's separate from these short comments/ proxy for the 140 character comments which it sounds like there will be. 

Yep, that's a key part of my proposal. :-) To reiterate:

> And then--also critical--we still leave the option to, from the subject page, start a new discussion anywhere else about the object. (Basically, that button starts a new thread in a place of the user's choosing, using the object as the featured image.)

Featuring/pinning is an obvious thing, and a must. @aweiksnar -- is it not incorporated yet?

@parrish will have the best perspective on if my overall proposal above is feasible.

**Comment by parrish** [comment]
It sounds reasonable, though I'd like to avoid any special case type situations in the backend -- we suffered a lot from those in the past.

I think the best thing we could do would be to have the project owner create a board and specify it as the default place for subject discussions to go.  In terms of disallowing other discussions there, I'm not sure that really matters, but that could be setup if testing shows it's important.

Sticky/pinning/featured is setup on the backend, but it still needs a bit of work to integrate them into the responses.

I really doubt it's going to happen by tomorrow, but it's definitely in the scope of near-term releases.

**Comment by mschwamb** [comment]
if you can't get the subject discussions to a separate board, then getting sticky working so things like  a Talk feedback thread, bugs thread, etc can be up at the top above the noise would be a big help for launch if that's doable for launch day

**Comment by DarrenMcRoy** [comment]
Agree with Meg. The Zoo Talk could get a little nuts if the important stuff can't be pinned. Really would call that important for tomorrow.

@parrish -- Define "special case type situations?"

I say "disallowing other discussions" because that was a big problem with the current "The Objects" boards... all sorts of things would go in there. If we're concerned about general discussion being overwhelmed by subject comments, why not just make sure that where the subject comments go, only the subject comments go?

Also, what's the logic behind having the project owner create the board, rather than having it autocreate? What happens if they don't create the board? I'd rather have it autocreate and then let them edit it to call  it what they want (though not delete it).

**Comment by vrooje** [comment]
I think it's valuable to retain different behavior for comments coming from the in-classification Talk button and everything else. 

I think the ability to sticky an FAQ would be good, and I think enabling team members and mods to have something like the Recents page from old Talk is really, really important. That doesn't exist yet, right?

**Comment by DarrenMcRoy** [comment]
> I think it's valuable to retain different behavior for comments coming from the in-classification Talk button and everything else. 

Does the in-classification Talk button generate an automatic field to add a comment in, or does it take you to the subject page? The problem with the former is that you can't see the other comments that have already been left, so you end up with very repetitive comments.

But, yes, that's the point behind my proposal: all those "quick" comments, the "140-proxy" as Meg called them, filter into this special thread in a special board, a thread also displayed on the subject page itself.

I would also like a Recents-type page as well (why not for everyone?), although I hope that people will eventually find their feeds more useful, once feeds are set up.

**Comment by vrooje** [comment]
Agreed everyone should be able to see a Recents page - a bit distracted today and my wording was poor. I meant to say that most mods and research team members I know find that The Most Useful thing on Talk. A page that answers "what have I missed?" is vitally important for those roles especially.

**Comment by DarrenMcRoy** [comment]
I also hope that eventually there will be a way for moderators to flag stuff for scientists.

And a way to view posts from the last 24 hours, week, etc., sorted by upvotes.

**Comment by mschwamb** [comment]
Perhaps these other suggestions should be a separate ticket/issue?

**Comment by aweiksnar** [comment]
I'll take a good try at stickies today, should be possible if there are no major hangups

**Comment by parrish** [comment]
@aweiksnar I've got an implementation idea I'm working on.  I'll chat with you on slack.

**Comment by chrislintott** [comment]
I think fixing this is essential and am changing the flag on the issue to a 'must solve' for release. We simply can't have the default behaviour being that boards are swamped with comments on objects; I'll take any solution, including creating a default board that the object discussions go on to. @aweiksnar Sorry I didn't catch this before.

**Comment by aweiksnar** [comment]
I'll try and combine Darren's idea with the current system. So object comments will go to a default discussion by default, but user's can still opt-in to start a new discussion about an object.

I'll also make it clearer that the existing discussions about objects can be joined from that page.

**Comment by DarrenMcRoy** [comment]
I'm sure that we can and will iterate on it post-launch, but it sounds like we can get something workable up today, and that's good. :+1:

**Comment by chrissnyder** [comment]
Closed by https://github.com/zooniverse/Panoptes-Front-End/pull/825
