### ISSUE TITLE
SLOW homepage: Please optimize page load experience for slow connections

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#693]
I just experienced a pretty horrible page load experience on Zoo Home. The page as a whole is way too large at 2.4Mb. The whole page took nearly 1 minute to load.

![network requests data from my browser](https://cloud.githubusercontent.com/assets/1473244/8331017/8a757e94-1a7d-11e5-80b5-7c085f5ccd7b.png)

The zoo home image is the main culprit at 673k, this could be optimized to probably a tenth of its size without a significant/noticeable loss in quality, but a massive boost in load time. But all the images and css and JS should be optimized...

Worse still, until the background loads, the page is unreadable, because the background is grey. 

![illegible during load](https://cloud.githubusercontent.com/assets/1473244/8331049/db313e5e-1a7d-11e5-988d-f5247d4017f5.png)

Please change the background to a dark black-like colour so that it is at least legible while the background loads.

Also, the "loading" flash is highly erratic, with numbers that jump up and down instead of descending.

**Comment by alexbfree** [comment]
Future plans? can't we at least change the background today @chrissnyder to make it a bit less painful . It'll take 30 seconds! And shrinking the image will only take a minute or two.

**Comment by chrissnyder** [comment]
"Future plans" is a bit vague and unhelpful, but here's my current philosophy when I tag issues into milestones.

If there issue is not materially blocking us from making a soft launch of PFE to zooniverse.org within the next couple of days, then it gets punted to Future plans. If it is blocking, then I put it in First Release. Everything else I leave untagged because I don't know where to put it.

Should we do this? Of course. Would it take much time? No. Are there potentially 1,000 of issues such as these to tackle in the coming weeks? Probably. My tagging it as Future plans shouldn't be taken as a desire to punt it to some nebulous time years from now, but just to separate out the blocking/non-blocking issues.

I could be wrong about all the above and am very willing to discuss.

**Comment by alexbfree** [comment]
OK fair enough. I assume if I were to create a PR which fixes it that might change things :-)

**Comment by chrissnyder** [comment]
it might! Be careful with the background color change though, that might have consequences elsewhere on the site.

**Comment by srallen** [comment]
I added the highest quality jpg assets when I was building the pages. I assumed the build script was doing some sort of image optimization, but it is not. JS and CSS are being minified/uglified, though. I swapped out the background image on the homepage for a more compressed one. Imagemin or something like that should be added to the build script.

**Comment by chrissnyder** [comment]
Fixed in 472d9e88fcc97b94a88dbeb31c5d5a0783bf3e59
