### ISSUE TITLE
getting the dimensions of an image

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes-Front-End#714]
right now to get the dimensions of an image (in order to remove bad markings) I seem to need to download the image. This is obviously not scalable for production. Can we think of a better way?
related to #712

**Comment by ggdhines** [comment]
alright - I am going to assume that all images in a workflow are the same size. I realize that is definitely not the case but I need to do something to check if markings are valid. This way I only need to download one image per workflow instead of possibly thousands. Alternatives most welcome

**Comment by eatyourgreens** [comment]
The front-end gets the full pixel height and width of each image on load, so that the marking tools can render properly.
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/subject-viewer.cjsx#L160

I guess it would be straightforward to add those numbers to the classification too? Assuming they aren't already stored with each subject anyway.

**Comment by ggdhines** [comment]
@eatyourgreens - yeah, those values would be exactly what I need and they are not currently stored with the subject

**Comment by camallen** [comment]
This can be stored in the classification metadata hash. We can extract it to it's own field if needed.

**Comment by ggdhines** [comment]
@camallen - metadata would be fine. Own field might be slightly more efficient in the long term

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes-Front-End/pull/991
