### ISSUE TITLE
"Recents"-style page for viewing all most recent posts

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#726]
Not too many details yet, but science teams do like having a way to view posts in chronological order. Users like that too.

Could also be "posts from the last X amount of time, ranked by upvotes." A good use for upvotes. Could filter by last 24 hours, last week, last month.

Definitely a future plan for Talk.

**Comment by vrooje** [comment]
I know this isn't in the plan for the release for tomorrow purely due to practical reasons, but I think it should be the next thing on the list. It is critically important for moderators. I cannot stress this enough.

I also think these are 2 different things - there is the "show me everything I missed" view, and there is the "show me the important stuff" view, and they both have value because people use Talk differently.

**Comment by vrooje** [comment]
Also: I think the priority is - fire hose first, upvote-weighted stuff second. But they are both important.

**Comment by DarrenMcRoy** [comment]
I like the descriptor of "fire hose." :+1:

**Comment by aweiksnar** [comment]
added in https://github.com/zooniverse/Panoptes-Front-End/pull/1501
