### ISSUE TITLE
Style descriptions for project cards

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#756]
Descriptions are now in for all existing projects, but they look a little bleak (light gray on white?) and the line spacing/font/font size are causing them to not quite fit. (It's more compact on the current/old Zoo Home.) The cards don't stretch to fit, either, which may be a good thing. (http://preview.zooniverse.org/panoptes/#/projects?page=1)

Could we get a styling update for these cards so that the text looks awesome and fits, and hopefully the project name also pops a bit more? @heathv ?

**Comment by mschwamb** [comment]
I actually like the descriptions as is in style, just that text is being cutoff on a few

**Comment by DarrenMcRoy** [comment]
I'd at least like a font color change, and for the project title to be a bit bolder, IMO.

**Comment by alexbfree** [comment]
Maybe something like this?

![css improvement](https://cloud.githubusercontent.com/assets/1473244/8350464/d8a89fce-1b1d-11e5-9042-6cd35dbee5fd.png)


Title: 
```
font: 400 15px/1.5 "Open Sans","Gill Sans",Arial,sans-serif;
text-align: center;
color: #000000;
```

Description:
```
color: #616161;
```

**Comment by DarrenMcRoy** [comment]
@alexbfree That's alright, but the description still doesn't fit. The line spacing is too great, and I still think like the light-gray text color is hard to read.

The spacing between the lines needs to be condensed, something closer to the current cards:

![screen shot 2015-06-25 at 8 38 48 am](https://cloud.githubusercontent.com/assets/8987864/8355679/2583c538-1b16-11e5-9001-1886bf0ec5fb.png)

**Comment by heathv** [comment]
Project titles can be bold in addition to @alexbfree  changes. I don't think the gray text is too light or hard to read, but thats me. Shows up with plenty of contrast on my display, but it could very well appear as low contrast on older displays.

I think in general we will have to iterate on project card design for future releases.

**Comment by chrissnyder** [comment]
This issue is conflating two separate issues.

- Problems with the design of the cards themselves
- The text is too long for the current design.

We've already made a couple changes to this in the last couple days and I don't think it's necessary to do another iteration before launch. You also should really involve @heathv if you have problems with the design.

@DarrenMcRoy I'll make an issue to truncate the text to fit in the current space allowed. This will do for now, as the only projects in the list will be ours. When we start opening this up, we'll need to make sure this is rock solid.
