### ISSUE TITLE
Not all Zooniverse team members are labeled so in Talk

### ISSUE THREAD

**Issue by kellinora** [zooniverse/Panoptes-Front-End#817]
my user name (kellinora) is an example.

**Comment by mschwamb** [comment]
Also on a related note, it might be good if you're on a project science team to also be denoted so people are aware you're associated with the Zooniverse. Currently that the researcher title is only the associated project talk.

**Comment by vrooje** [comment]
This is a bit of a grey area, though. For people like @aliburchard who are both Zooniverse Team and on a specific science team, it makes sense, but most science team members shouldn't be tagged as a Zoo Team member in the way e.g. @kellinora or @DarrenMcRoy should.

If you mean there should be a totally separate "this person has built a live project before" tag, that could be useful.

**Comment by mschwamb** [comment]
Sorry poor choice of words. Wasn't suggested Zooniverse team tag be denoted to someone's a science team member. I meant that it might be good if the researcher tag that's current in play on the project boards be extended on Talk with the zooniverse team tag reserved for those who deserve it/should be denoted that way. Apologies for any confusion.

**Comment by vrooje** [comment]
No worries, I suspect that wasn't you at all; it was me failing to make sense of anything whatsoever at 3:30 am! :)

**Comment by DarrenMcRoy** [comment]
I still believe that people should have the ability to have multiple tags. Where did we land on that, @aweiksnar ...?

**Comment by aweiksnar** [comment]
Researchers will only show up as having the researcher role in their own projects, not in zooniverse wide talk. Since anyone who creates a project has a researcher role, that could be a potentially high percentage of users and become valueless outside of the context of the project. 
But yes, if you have a zooniverse team role and additional roles in a project, both will show up in the project.

And just so it's clear for everyone here is how things are being displayed as of today, with project roles only showing up in the project. This should be as we decided last week @DarrenMcRoy 

Role Assignment | Display
---------- | -------------
Zooniverse Talk Admin | Zooniverse Team
Project Scientist | Researcher
Project Talk Admin | Researcher
Project Owner | Researcher
Translator | Translator
Other Roles | Other Roles

**Comment by DarrenMcRoy** [comment]
Moderators, too, right? Moderator displays as Moderator?

**Comment by aweiksnar** [comment]
Ah sorry forgot moderators in the table. Yep that's correct I'll add it in

**Comment by DarrenMcRoy** [comment]
It looks like a lot of people don't have the Team role yet... @bumishness and even you, @aweiksnar ... Were you still working on importing that? Is there a place where I can add roles?

**Comment by DarrenMcRoy** [comment]
http://preview.zooniverse.org/panoptes/#/talk/13/102

**Comment by mschwamb** [comment]
I guess I'm finding it strange that if I am having a conversation about something in the Zooniverse Talk, that people wouldn't realize I'm on a science team for an approved active project. I think their first reaction would be I'm a volunteer, and I do think there's a difference in perspective, but perhaps that's more the in the days of the old system. Maybe there's no good solution for the moment.

**Comment by vrooje** [comment]
I would love to have the problem that so many volunteers have created active projects that a label of "project owner" becomes valueless.

Until then I think there's some value in a label, but on the other hand this could become another way of stratifying users and encouraging cliques, which I think we should avoid.

Perhaps a middle ground is to have this information viewable in a user's profile but not in a label that displays on every post?

**Comment by mschwamb** [comment]
@mrniaboc is also not showing up on Zooniverse Talk as Zooniverse Team

**Comment by aliburchard** [comment]
@aweiksnar @DarrenMcRoy can we make a change to the way that talk roles are being displayed? Such that "collaborators" (or "owners") on a project only appear as "researchers"  if they also are marked as "researchers"? 

I am a collaborator on Whales, but know absolutely nothing about the science. I would really like to be able to join in the discussion on Talk (responding to people while waiting for the science team), but having a "researcher" label under my name is really misleading.

**Comment by aliburchard** [comment]
Noticing that if the project owner is marked as a researcher, they have two "researcher" tags below their name on talk.

**Comment by DarrenMcRoy** [comment]
Hm, I hadn't considered that use case.

How many roles can display right now? As many as you have?

If so, I would have no trouble changing "project owner" back to displaying as "Project Owner" if that person could also be displayed as a "Researcher." I was worried before because we were talking about only displaying one role at a time.

**Comment by mschwamb** [comment]
I'm an owner and a researcher and only one 'researcher' label is showing below my avatar in Talk. Maybe it's because you're a collaborator on two projects that's causing this? It's the only immediate difference I could think of between @aliburchard's account and mine at the moment  - see [here](https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/10/8?page=1&comment=12)

**Comment by mrniaboc** [comment]
I would love to be labelled as 'Zooniverse Team'

**Comment by mrniaboc** [comment]
I tried on all 4 new projects and it worked fine for me. This of course does not mean that's the case for everyone!

**Comment by vrooje** [comment]
I'm starting to come around to the idea that on Zooniverse Talk all the people listed on the Team page should be labelled with "Zooniverse Team". I don't think I currently have any status whatsoever on Zoo Talk and I'm wondering if that looks a little weird to people I'm giving advice on project building to. Time will tell, I suppose!

**Comment by mrniaboc** [comment]
This is a valid point and Cam has been working to make the happen.

**Comment by DarrenMcRoy** [comment]
Fixed now with the assistance of @camallen I believe.
