### ISSUE TITLE
Select how much of a post you want to quote in a reply

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#888]
Currently, the only thing you can do as far as replying to a post is to quote the entire post in your reply, in one huge chunk, at the very beginning.

This is cumbersome and limiting, especially if you want to reply to an extremely long post, or if you want to reply to a post in bits and pieces, or if you want to reply to multiple posts.

Most forums manage this by having the "reply" button add code inline to your post, code that you can then manage, crop, break apart, etc. ... any chance we could have our system work similarly?

**Comment by mschwamb** [comment]
Perhaps this would help. I really liked the way Talk 2.0 did this while it it as a reply but didn't always copy the text and had a link above that worked and then dropped down the comment you're replying to

**Comment by mschwamb** [comment]
The text quote gets cumbersome when you reply to a reply of a post.

**Comment by DarrenMcRoy** [comment]
I would strongly advocate for this to be in whatever the next sprint is.

I have some ideas about how this could work better and probably much more simply. :+1:

**Comment by mschwamb** [comment]
replies of replies of replies take up a large chunk of a page. Currently, I stop using the reply button after a few times because it becomes too cumbersome to scroll through the text, that's it easy just write a post. Maybe a temp solution is just to quote no-quoted text in the reply rather than everything that came before including the previous messages? 

See link below for an example

https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/8/120?comment=3834

**Comment by mschwamb** [comment]
@chrissnyder Thought I'd bring you the discussion with you first since since it might involve the Talk graphic design pass just in case, but I don't think it significantly does.  I'm slowly stopping using the reply in long conversations since I've become accustomed to the way Talk 2.0 hides the conversation and you hit a link to see the previous post. It becomes easier to post without the reply linking since you don't have to scroll through all the previous conversations. 

With the current setup replies of replies make long blocks you have to scroll through to get down to where you can write your response: an example of a recent conversation I've had with a volunteer about collections:

![screen shot 2015-08-16 at 11 20 50 pm](https://cloud.githubusercontent.com/assets/753325/9293889/fbd92152-446d-11e5-8189-19a0960529a9.png)
![screen shot 2015-08-16 at 11 21 22 pm](https://cloud.githubusercontent.com/assets/753325/9293891/fc5d36c2-446d-11e5-8e27-59018cb87e63.png)
![screen shot 2015-08-16 at 11 21 31 pm](https://cloud.githubusercontent.com/assets/753325/9293892/fdcb451c-446d-11e5-813f-67021368694f.png)

I know there are graphic design upgrades to happen, but I think this issue is independent of how the reply is formatted. Instead of editing how much text is in the reply,would it be straightforward to leave the currently reply history format but make it  hidden and then you click a button/link to reveal the replies when you're both writing and viewing a reply to a previous comment . I think this would be huge step in getting the ease in usability and equivalence in features that is currently available in Talk 2.0. 

Talk 2.0 does this something like this

![screen shot 2015-08-16 at 11 18 29 pm](https://cloud.githubusercontent.com/assets/753325/9293862/4df476b8-446d-11e5-8703-3cf4f9f32289.png)

click the in response to link and this shows up

![screen shot 2015-08-16 at 11 18 32 pm](https://cloud.githubusercontent.com/assets/753325/9293865/59a32b6c-446d-11e5-8622-18445007c87c.png)

**Comment by DarrenMcRoy** [comment]
I would really like to +1 this. It's a real usability problem for Talk right now.

**Comment by vrooje** [comment]
I like the threading of Talk 2.0 but also I really like the flexibility of being able to quote partial replies, or to quote-reply-quote-reply in the same message.

I know it's not that easy to do that right now using the Official Button on Talk, but it's easy enough to work around it, either with copy-paste and ">" or by editing the post after it's submitted.

Alternative suggestion: right now clicking the "Reply" button makes the quoted message appear above the input text box for the new comment. What if instead it made the quoted text appear in the input text box with ">" and set the cursor beneath it? That would allow people to edit as needed/wanted immediately. It's also forum-like behavior so I think the old hands would accept it.

I have no idea whether that's easier to code than other suggestions above, whether it would be additionally helpful at squashing other bugs (e.g. #922), or whether it fits into broader future plans for Talk, but I thought I'd throw the suggestion out there.

**Comment by DarrenMcRoy** [comment]
Actually, I like Brooke's idea as well, for the reason stated: quoting partial replies, or doing quote-reply-quote, is very powerful.

I would just add that it would also be useful if the quoted text included an automatic link back to the original post.

**Comment by mschwamb** [comment]
Since I'm the differing opinion I wanted to say I'm only suggesting a hide button since  I think that would be easier to implement.  Whatever is quickest to implement I'm fine with. There are other things (like the subject pages) I think need attention to get Talk fully functional and I'm sure development time is at a premium.

**Comment by aweiksnar** [comment]
Yeah I can make replies prepend the text-box. My thinking initially was that this way would prevent people from editing each others' comments, but clearly that comes with drawbacks.
Otherwise, if there's consensus about keeping the previous-talk's version of replies, I'll need to ping Michael about adding that column to the api

**Comment by DarrenMcRoy** [comment]
If someone edits someone else's comment while quoting it in a reply, it's immediately apparent that they've done so by clicking the link to the original comment, and moderators could take appropriate action.

**Comment by vrooje** [comment]
I think it's okay to trust that the vast majority of people won't maliciously mis-quote. I do like the idea of also having a direct link back to the full reply-to post (that would allow people to just reply without quoting), but if it's going to take a lot more dev time I don't think it's urgent.

**Comment by mschwamb** [comment]
Though still having replies of replies of replies show up will happen. Is there a solution for that bit?

**Comment by DarrenMcRoy** [comment]
@mschwamb -- it will happen, but it will be less common. Volunteers generally realize when something looks crummy and over-long, and will trim it down appropriately (my experience from many other sites that use this functionality). I don't think we'll need to police it any more than we need to police people copying entire Wikipedia articles and leaving that as a comment. :-) (If I'm wrong and it becomes a big issue, we can revisit!)

Made issue #1434 for the link-backs, which really should not be that hard I can't imagine?

**Comment by mschwamb** [comment]
@DarrenMcRoy I disagree with that a bit. If I have to scroll through two screens to edit get to the actual reply part and to go back through and edit it to trim down to what I'm actually discussing I think people will just hit reply. I'm fine if it wants to be an edit box, but I don't think that solution solves that part of the issue.

**Comment by DarrenMcRoy** [comment]
The other option that I can see would be to limit the number of nested replies somehow, after which point (2-3 replies or so) you only have links to the original comments, not the complete comments, so you can't end up with dozens of replies all nested in one comment. I've seen functionality similar to this as well.

I'd be curious to see how this is actually used, because there are many online forums that allow for unlimited reply-nesting, but don't generally see that function abused.

**Comment by mschwamb** [comment]
@DarrenMcRoy I think that would be a big help since I use replies in the help threads and feedback threads, where if there is a continuing issue will be replies of replies of replies.
