### ISSUE TITLE
Set up Jenkins to deploy

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#889]
Jenkins should run `npm run deploy` instead of `stage` when master changes.

P.S. Until this happens, @chrissnyder @aweiksnar @edpaget (or anybody else doing deploys), it's a good idea to `rm -rf node_modules && npm install` before deploying.

**Comment by astopy** [comment]
@brian-c This is set up now. Did you want to make a staging branch to deploy to staging automatically too? Or will you just manually deploy stuff for testing?

**Comment by brian-c** [comment]
Thanks!

@aweiksnar @chrissnyder what do you guys think of having a separate staging branch? I could go either way.

**Comment by aweiksnar** [comment]
I'm up to give it a try, but have no issues with manual deploys for staging. We could always stick the branch/commit-hash into the deploy comment that you added so we know what's on there

**Comment by chrissnyder** [comment]
Also don't have any issues with manual deploys for staging branches. The primary purpose I can see for an auto-deployed staging if master already auto-deployed would be so non-developers can play with the latest and greatest. Then again, staging would never be different than master in that case would it?

As we work on feature branches, would the thought be to merge them into staging, then merge staging into master when we are ready for a deploy? I'd be for this, as it gives us control over when we push new versions to users, rather than anytime we merge even minor PRs.

**Comment by edpaget** [comment]
If master is being constantly deployed what would a staging branch do? You'd want to manually push feature branches you want other people to try out somewhere, instead of having to figure out how to make them co-exist with other experimental features on a single staging branch.

**Comment by brian-c** [comment]
I was thinking staging would auto deploy, and then we'd merge staging into master and deploy new stuff in batches.

But I do like the idea of staging features separately better. `npm run stage-branch` is nice for this.

**Comment by chrissnyder** [comment]
> I was thinking staging would auto deploy, and then we'd merge staging into master and deploy new stuff in batches.

This would be my preferred approach.
