### ISSUE TITLE
Can't click through to individual image from a collection

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#898]
I can't seem to click through to the individual comment page for any image when I view them in a collection.

**Comment by mschwamb** [comment]
Reposting here, since I missed this ticket. Currently all you can see is the smaller thumbnail version of a subject in a collection. You should be able to somehow get to seeing a larger version of the image in a collection. I think the ideal thing which I used on Planet Four Talk frequently when looking about volunteer-made collections was that you clicked and it took you to the subject's Talk page and there you could see other collections the image was in and hashtags and discussions associated with the subject. I think this would be useful having the same ability in panoptes. I think it will be by science teams and volunteers doing their own investigations (if that information is going to be displayed eventually on the subject's Talk page).
