### ISSUE TITLE
Move 'done' and 'back' buttons up closer to yes/no buttons

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#95]

**Comment by ttfnrob** [comment]
I think relates to a broader issue of how to handle things that are bigger
than the height of the screen. Should there be a maximum height of 100% of
this interface, or will that cause bother? It's annoying that the buttons
and image go below he fold on my 13" screen.

**Comment by mkosmala** [comment]
@ttfnrob, I've been told that images are a maximum of 100% of screen height. But I think they should probably be sized a bit smaller than that so we can keep the header on screen. Otherwise, it's not obvious when the screen first loads where the buttons are / what you're supposed to do.

But the button location is a problem even when images are the height of the screen. Yes, please move the buttons up under the question. We need it to be super clear to users how to answer the questions and move through the work flow!

**Comment by aliburchard** [comment]
I like the idea of having the "done"/"next" buttons tied more to the questions. So the subject appears as large as it needs to (up to 100% of just less of screen height, depending on what you decide), but that the  done buttons are glued a certain distance from the bottom of the questions.
