### ISSUE TITLE
Hyperlinks go wrong in the Talk

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#966]
Every hyperlink made in the Talk adds *https://www.zooniverse.org/* to the beginning - bbefore the URL typed in the brackets, so it won't take you to the page it should.

**Comment by DarrenMcRoy** [comment]
Just a note that this only happens if you leave off the "http://", but it should still really be fixed.

**Comment by mschwamb** [comment]
I've been instructed that's a behavior so all the links to project pages on Planet Four: Terrains that refer to local pages use this feature to navigate so if this gets fixed I'll have to change that.

**Comment by DarrenMcRoy** [comment]
@mschwamb Would that be hard?

I admit, if I post a link to www.google.com, I do expect that link to go to Google, not to have to post "http://www.google.com"

**Comment by mschwamb** [comment]
@DarrenMcRoy I'm posting so I'll be notified when the thread gets closed so I do know what to do once the development team makes a decision on what they want to do

**Comment by vrooje** [comment]
I prefer this behavior so that relative links are enabled. If you do this in a plain HTML link you get the same behavior -- you need http:// so that it knows it's not a relative link. I don't think this is a bug.

**Comment by DarrenMcRoy** [comment]
How often do we use relative links? How do relative links even work? We never had such things on the old Talk, did we?

**Comment by vrooje** [comment]
Yes, we did and do. If you write
     `[test1](www.zooniverse.org)`
on talk.galaxyzoo.org, the link goes to http://talk.galaxyzoo.org/www.zooniverse.org, whereas if you write
     `[test2](http://www.zooniverse.org)`
it goes to the right place. 

Note: it works the same way on this Issues page ([test3](www.zooniverse.org)). This is standard behavior on the web.

**Comment by DarrenMcRoy** [comment]
Hm, you're right that this appears to be bog standard web behavior! Somehow I never noticed because I pretty much always copy-paste my links.

But the question remains: do we ever actually use the functionality where we just want to link the extension? e.g.:

`[test1](#/subjects/AGZ0002soi)' to go to http://talk.galaxyzoo.org/#/subjects/AGZ0002soi -- I get that it works, but does it need to? Do we actually use that behavior on any sort of regular basis?

I noticed that some systems have a way to prevent against leaving broken links by forgetting the hypertext transfer protocol. For instance, on Reddit, if you post something without the http://, the code just doesn't even turn into hyperlink (since Reddit has no need for the extension-linking as mentioned above). And Talk 2.0 uses a modal for adding links that automatically adds the http:// if you forget, the same way your browser will turn "google.com" into "http://www.google.com."

Just thoughts here. If this all seems unnecessary, we can close the issue.

**Comment by vrooje** [comment]
I just don't see why we should break the standard functionality of markdown (and the standard way the web deals with links) in order to *reduce* what you can do on the site. 

Maybe @edpaget has another opportunity to mark something wontfix? ;)

**Comment by DarrenMcRoy** [comment]
I'm convinced. Closing.
